/* eslint-disable */
'use client';
import { Icon, } from './chunk-W3OFBK3Q.js';
import { defaultEvents, NullState, useIconSelection, } from './chunk-KA64PIU2.js';
import './chunk-MLKGABMK.js';

// https :https://framerusercontent.com/modules/5RKlpLgYNk7duxXcZDXd/6Z8wlYy6uR0TX0tUNvYW/Wk_vueg3a.js
import { jsx as _jsx3, jsxs as _jsxs2, } from 'react/jsx-runtime';
import {
  addFonts as addFonts2,
  addPropertyControls as addPropertyControls3,
  ComponentViewportProvider,
  ControlType as ControlType3,
  cx as cx2,
  getFonts as getFonts2,
  getFontsFromSharedStyle,
  getPropertyControls,
  Image,
  Link as Link2,
  RichText as RichText2,
  useComponentViewport,
  useLocaleInfo as useLocaleInfo2,
  useVariantState as useVariantState2,
  withCSS as withCSS2,
} from 'unframer';
import { LayoutGroup as LayoutGroup2, motion as motion3, MotionConfigContext as MotionConfigContext2, } from 'unframer';
import * as React3 from 'react';

// https :https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
import { jsx as _jsx, } from 'react/jsx-runtime';
import * as React from 'react';
import { useEffect, useRef, useState, } from 'react';
import { addPropertyControls, ControlType, RenderTarget, } from 'unframer';
import { motion, } from 'unframer';

// https :https://framer.com/m/phosphor-icons/House.js@0.0.53
var Component;
var House_default = (React4,) => {
  if (!Component) {
    const weights = /* @__PURE__ */ new Map([
      [
        'bold',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M221.56,100.85,141.61,25.38l-.16-.15a19.93,19.93,0,0,0-26.91,0l-.17.15L34.44,100.85A20.07,20.07,0,0,0,28,115.55V208a20,20,0,0,0,20,20H96a20,20,0,0,0,20-20V164h24v44a20,20,0,0,0,20,20h48a20,20,0,0,0,20-20V115.55A20.07,20.07,0,0,0,221.56,100.85ZM204,204H164V160a20,20,0,0,0-20-20H112a20,20,0,0,0-20,20v44H52V117.28l76-71.75,76,71.75Z',
          },),
        ),
      ],
      [
        'duotone',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement(
            'path',
            {
              d: 'M216,115.54V208a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.54a8,8,0,0,1,2.62-5.92l80-75.54a8,8,0,0,1,10.77,0l80,75.54A8,8,0,0,1,216,115.54Z',
              opacity: '0.2',
            },
          ),
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z',
          },),
        ),
      ],
      [
        'fill',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M224,115.55V208a16,16,0,0,1-16,16H168a16,16,0,0,1-16-16V168a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v40a16,16,0,0,1-16,16H48a16,16,0,0,1-16-16V115.55a16,16,0,0,1,5.17-11.78l80-75.48.11-.11a16,16,0,0,1,21.53,0,1.14,1.14,0,0,0,.11.11l80,75.48A16,16,0,0,1,224,115.55Z',
          },),
        ),
      ],
      [
        'light',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M217.47,105.24l-80-75.5-.09-.08a13.94,13.94,0,0,0-18.83,0l-.09.08-80,75.5A14,14,0,0,0,34,115.55V208a14,14,0,0,0,14,14H96a14,14,0,0,0,14-14V160a2,2,0,0,1,2-2h32a2,2,0,0,1,2,2v48a14,14,0,0,0,14,14h48a14,14,0,0,0,14-14V115.55A14,14,0,0,0,217.47,105.24ZM210,208a2,2,0,0,1-2,2H160a2,2,0,0,1-2-2V160a14,14,0,0,0-14-14H112a14,14,0,0,0-14,14v48a2,2,0,0,1-2,2H48a2,2,0,0,1-2-2V115.55a2,2,0,0,1,.65-1.48l.09-.08,79.94-75.48a2,2,0,0,1,2.63,0L209.26,114l.08.08a2,2,0,0,1,.66,1.48Z',
          },),
        ),
      ],
      [
        'regular',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z',
          },),
        ),
      ],
      [
        'thin',
        /* @__PURE__ */ React4.createElement(
          React4.Fragment,
          null,
          /* @__PURE__ */ React4.createElement('path', {
            d: 'M216.13,106.72,136.07,31.13a12,12,0,0,0-16.2.05L39.93,106.67A12,12,0,0,0,36,115.54V208a12,12,0,0,0,12,12H96a12,12,0,0,0,12-12V160a4,4,0,0,1,4-4h32a4,4,0,0,1,4,4v48a12,12,0,0,0,12,12h48a12,12,0,0,0,12-12V115.54A12,12,0,0,0,216.13,106.72ZM212,208a4,4,0,0,1-4,4H160a4,4,0,0,1-4-4V160a12,12,0,0,0-12-12H112a12,12,0,0,0-12,12v48a4,4,0,0,1-4,4H48a4,4,0,0,1-4-4V115.54a4.09,4.09,0,0,1,1.36-3L125.3,37.05a4,4,0,0,1,5.33,0l80.06,75.58a4,4,0,0,1,1.31,3Z',
          },),
        ),
      ],
    ],);
    const House = React4.forwardRef((props, ref,) =>
      /* @__PURE__ */ React4.createElement('g', { ref, ...props, }, weights.get(props.weight,),)
    );
    House.displayName = 'House';
    Component = House;
  }
  return Component;
};

// https :https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
var iconKeys = [
  'AddressBook',
  'AirTrafficControl',
  'Airplane',
  'AirplaneInFlight',
  'AirplaneLanding',
  'AirplaneTakeoff',
  'AirplaneTilt',
  'Airplay',
  'Alarm',
  'Alien',
  'AlignBottom',
  'AlignBottomSimple',
  'AlignCenterVertical',
  'AlignLeft',
  'AlignLeftSimple',
  'AlignRight',
  'AlignRightSimple',
  'AlignTop',
  'AlignTopSimple',
  'AmazonLogo',
  'Anchor',
  'AnchorSimple',
  'AndroidLogo',
  'AngularLogo',
  'Aperture',
  'AppStoreLogo',
  'AppWindow',
  'AppleLogo',
  'ApplePodcastsLogo',
  'Archive',
  'ArchiveBox',
  'ArchiveTray',
  'Armchair',
  'ArrowArcLeft',
  'ArrowArcRight',
  'ArrowBendDownLeft',
  'ArrowBendDownRight',
  'ArrowBendLeftDown',
  'ArrowBendLeftUp',
  'ArrowBendRightDown',
  'ArrowBendRightUp',
  'ArrowBendUpLeft',
  'ArrowBendUpRight',
  'ArrowCircleDown',
  'ArrowCircleDownLeft',
  'ArrowCircleDownRight',
  'ArrowCircleLeft',
  'ArrowCircleRight',
  'ArrowCircleUp',
  'ArrowCircleUpLeft',
  'ArrowCircleUpRight',
  'ArrowClockwise',
  'ArrowDown',
  'ArrowDownLeft',
  'ArrowDownRight',
  'ArrowElbowDownLeft',
  'ArrowElbowDownRight',
  'ArrowElbowLeft',
  'ArrowElbowLeftDown',
  'ArrowElbowLeftUp',
  'ArrowElbowRight',
  'ArrowElbowRightDown',
  'ArrowElbowRightUp',
  'ArrowElbowUpLeft',
  'ArrowElbowUpRight',
  'ArrowFatDown',
  'ArrowFatLeft',
  'ArrowFatLineDown',
  'ArrowFatLineLeft',
  'ArrowFatLineRight',
  'ArrowFatLineUp',
  'ArrowFatLinesDown',
  'ArrowFatLinesLeft',
  'ArrowFatLinesRight',
  'ArrowFatLinesUp',
  'ArrowFatRight',
  'ArrowFatUp',
  'ArrowLeft',
  'ArrowLineDown',
  'ArrowLineDownLeft',
  'ArrowLineDownRight',
  'ArrowLineLeft',
  'ArrowLineRight',
  'ArrowLineUp',
  'ArrowLineUpLeft',
  'ArrowLineUpRight',
  'ArrowRight',
  'ArrowSquareDown',
  'ArrowSquareDownLeft',
  'ArrowSquareDownRight',
  'ArrowSquareIn',
  'ArrowSquareLeft',
  'ArrowSquareOut',
  'ArrowSquareRight',
  'ArrowSquareUp',
  'ArrowSquareUpLeft',
  'ArrowSquareUpRight',
  'ArrowUDownLeft',
  'ArrowUDownRight',
  'ArrowULeftDown',
  'ArrowULeftUp',
  'ArrowURightDown',
  'ArrowURightUp',
  'ArrowUUpLeft',
  'ArrowUUpRight',
  'ArrowUp',
  'ArrowUpLeft',
  'ArrowUpRight',
  'ArrowsClockwise',
  'ArrowsDownUp',
  'ArrowsHorizontal',
  'ArrowsIn',
  'ArrowsInCardinal',
  'ArrowsInLineVertical',
  'ArrowsInSimple',
  'ArrowsLeftRight',
  'ArrowsMerge',
  'ArrowsOut',
  'ArrowsOutCardinal',
  'ArrowsOutSimple',
  'ArrowsSplit',
  'ArrowsVertical',
  'Article',
  'ArticleMedium',
  'ArticleNyTimes',
  'Asterisk',
  'AsteriskSimple',
  'At',
  'Atom',
  'Baby',
  'Backpack',
  'Backspace',
  'Bag',
  'BagSimple',
  'Balloon',
  'Bandaids',
  'Bank',
  'Barbell',
  'Barcode',
  'Barricade',
  'Baseball',
  'BaseballCap',
  'Basket',
  'Basketball',
  'Bathtub',
  'BatteryCharging',
  'BatteryEmpty',
  'BatteryFull',
  'BatteryHigh',
  'BatteryLow',
  'BatteryMedium',
  'BatteryPlus',
  'BatteryPlusVertical',
  'BatteryVerticalEmpty',
  'BatteryVerticalFull',
  'BatteryVerticalHigh',
  'BatteryVerticalLow',
  'BatteryWarning',
  'Bed',
  'BeerBottle',
  'BeerStein',
  'BehanceLogo',
  'Bell',
  'BellRinging',
  'BellSimple',
  'BellSimpleRinging',
  'BellSimpleSlash',
  'BellSimpleZ',
  'BellSlash',
  'BellZ',
  'BezierCurve',
  'Bicycle',
  'Binoculars',
  'Bird',
  'Bluetooth',
  'BluetoothConnected',
  'BluetoothSlash',
  'BluetoothX',
  'Boat',
  'Bone',
  'Book',
  'BookBookmark',
  'BookOpen',
  'BookOpenText',
  'Bookmark',
  'BookmarkSimple',
  'Bookmarks',
  'BookmarksSimple',
  'Books',
  'Boot',
  'BoundingBox',
  'BowlFood',
  'BracketsAngle',
  'BracketsCurly',
  'BracketsRound',
  'BracketsSquare',
  'Brain',
  'Brandy',
  'Bridge',
  'Briefcase',
  'BriefcaseMetal',
  'Broadcast',
  'Broom',
  'Browser',
  'Browsers',
  'Bug',
  'BugBeetle',
  'BugDroid',
  'Buildings',
  'Bus',
  'Butterfly',
  'Cactus',
  'Cake',
  'Calculator',
  'Calendar',
  'CalendarBlank',
  'CalendarCheck',
  'CalendarPlus',
  'CalendarX',
  'CallBell',
  'Camera',
  'CameraPlus',
  'CameraRotate',
  'CameraSlash',
  'Campfire',
  'Car',
  'CarProfile',
  'CarSimple',
  'Cardholder',
  'Cards',
  'CaretCircleDoubleUp',
  'CaretCircleDown',
  'CaretCircleLeft',
  'CaretCircleRight',
  'CaretCircleUp',
  'CaretCircleUpDown',
  'CaretDoubleDown',
  'CaretDoubleLeft',
  'CaretDoubleRight',
  'CaretDoubleUp',
  'CaretDown',
  'CaretLeft',
  'CaretRight',
  'CaretUp',
  'CaretUpDown',
  'Carrot',
  'CassetteTape',
  'CastleTurret',
  'Cat',
  'CellSignalFull',
  'CellSignalHigh',
  'CellSignalLow',
  'CellSignalMedium',
  'CellSignalNone',
  'CellSignalSlash',
  'CellSignalX',
  'Certificate',
  'Chair',
  'Chalkboard',
  'ChalkboardSimple',
  'ChalkboardTeacher',
  'Champagne',
  'ChargingStation',
  'ChartBar',
  'ChartBarHorizontal',
  'ChartDonut',
  'ChartLine',
  'ChartLineDown',
  'ChartLineUp',
  'ChartPie',
  'ChartPieSlice',
  'ChartPolar',
  'ChartScatter',
  'Chat',
  'ChatCentered',
  'ChatCenteredDots',
  'ChatCenteredText',
  'ChatCircle',
  'ChatCircleDots',
  'ChatCircleText',
  'ChatDots',
  'ChatTeardrop',
  'ChatTeardropDots',
  'ChatTeardropText',
  'ChatText',
  'Chats',
  'ChatsCircle',
  'ChatsTeardrop',
  'Check',
  'CheckCircle',
  'CheckFat',
  'CheckSquare',
  'CheckSquareOffset',
  'Checks',
  'Church',
  'Circle',
  'CircleDashed',
  'CircleHalf',
  'CircleHalfTilt',
  'CircleNotch',
  'CirclesFour',
  'CirclesThree',
  'CirclesThreePlus',
  'Circuitry',
  'Clipboard',
  'ClipboardText',
  'Clock',
  'ClockAfternoon',
  'ClockClockwise',
  'ClockCounterClockwise',
  'ClockCountdown',
  'ClosedCaptioning',
  'Cloud',
  'CloudArrowDown',
  'CloudArrowUp',
  'CloudCheck',
  'CloudFog',
  'CloudLightning',
  'CloudMoon',
  'CloudRain',
  'CloudSlash',
  'CloudSnow',
  'CloudSun',
  'CloudWarning',
  'CloudX',
  'Club',
  'CoatHanger',
  'CodaLogo',
  'Code',
  'CodeBlock',
  'CodeSimple',
  'CodepenLogo',
  'CodesandboxLogo',
  'Coffee',
  'Coin',
  'CoinVertical',
  'Coins',
  'Columns',
  'Command',
  'Compass',
  'CompassTool',
  'ComputerTower',
  'Confetti',
  'ContactlessPayment',
  'Control',
  'Cookie',
  'CookingPot',
  'Copy',
  'CopySimple',
  'Copyleft',
  'Copyright',
  'CornersIn',
  'CornersOut',
  'Couch',
  'Cpu',
  'CreditCard',
  'Crop',
  'Cross',
  'Crosshair',
  'CrosshairSimple',
  'Crown',
  'CrownSimple',
  'Cube',
  'CubeFocus',
  'CubeTransparent',
  'CurrencyBtc',
  'CurrencyCircleDollar',
  'CurrencyCny',
  'CurrencyDollar',
  'CurrencyDollarSimple',
  'CurrencyEth',
  'CurrencyEur',
  'CurrencyGbp',
  'CurrencyInr',
  'CurrencyJpy',
  'CurrencyKrw',
  'CurrencyKzt',
  'CurrencyNgn',
  'CurrencyRub',
  'Cursor',
  'CursorClick',
  'CursorText',
  'Cylinder',
  'Database',
  'Desktop',
  'DesktopTower',
  'Detective',
  'DevToLogo',
  'DeviceMobile',
  'DeviceMobileCamera',
  'DeviceMobileSpeaker',
  'DeviceTablet',
  'DeviceTabletCamera',
  'DeviceTabletSpeaker',
  'Devices',
  'Diamond',
  'DiamondsFour',
  'DiceFive',
  'DiceFour',
  'DiceOne',
  'DiceSix',
  'DiceThree',
  'DiceTwo',
  'Disc',
  'DiscordLogo',
  'Divide',
  'Dna',
  'Dog',
  'Door',
  'DoorOpen',
  'Dot',
  'DotOutline',
  'DotsNine',
  'DotsSix',
  'DotsSixVertical',
  'DotsThree',
  'DotsThreeCircle',
  'DotsThreeOutline',
  'DotsThreeVertical',
  'Download',
  'DownloadSimple',
  'Dress',
  'DribbbleLogo',
  'Drop',
  'DropHalf',
  'DropHalfBottom',
  'DropboxLogo',
  'Ear',
  'EarSlash',
  'Egg',
  'EggCrack',
  'Eject',
  'EjectSimple',
  'Elevator',
  'Engine',
  'Envelope',
  'EnvelopeOpen',
  'EnvelopeSimple',
  'EnvelopeSimpleOpen',
  'Equalizer',
  'Equals',
  'Eraser',
  'EscalatorDown',
  'EscalatorUp',
  'Exam',
  'Exclude',
  'ExcludeSquare',
  'Export',
  'Eye',
  'EyeClosed',
  'EyeSlash',
  'Eyedropper',
  'EyedropperSample',
  'Eyeglasses',
  'FaceMask',
  'FacebookLogo',
  'Factory',
  'Faders',
  'FadersHorizontal',
  'Fan',
  'FastForward',
  'FastForwardCircle',
  'Feather',
  'FigmaLogo',
  'File',
  'FileArchive',
  'FileArrowDown',
  'FileArrowUp',
  'FileAudio',
  'FileCloud',
  'FileCode',
  'FileCss',
  'FileCsv',
  'FileDashed',
  'FileDoc',
  'FileHtml',
  'FileImage',
  'FileJpg',
  'FileJs',
  'FileJsx',
  'FileLock',
  'FileMagnifyingGlass',
  'FileMinus',
  'FilePdf',
  'FilePlus',
  'FilePng',
  'FilePpt',
  'FileRs',
  'FileSql',
  'FileSvg',
  'FileText',
  'FileTs',
  'FileTsx',
  'FileVideo',
  'FileVue',
  'FileX',
  'FileXls',
  'FileZip',
  'Files',
  'FilmReel',
  'FilmScript',
  'FilmSlate',
  'FilmStrip',
  'Fingerprint',
  'FingerprintSimple',
  'FinnTheHuman',
  'Fire',
  'FireExtinguisher',
  'FireSimple',
  'FirstAid',
  'FirstAidKit',
  'Fish',
  'FishSimple',
  'Flag',
  'FlagBanner',
  'FlagCheckered',
  'FlagPennant',
  'Flame',
  'Flashlight',
  'Flask',
  'FloppyDisk',
  'FloppyDiskBack',
  'FlowArrow',
  'Flower',
  'FlowerLotus',
  'FlowerTulip',
  'FlyingSaucer',
  'Folder',
  'FolderDashed',
  'FolderLock',
  'FolderMinus',
  'FolderNotch',
  'FolderNotchMinus',
  'FolderNotchOpen',
  'FolderNotchPlus',
  'FolderOpen',
  'FolderPlus',
  'FolderSimple',
  'FolderSimpleDashed',
  'FolderSimpleLock',
  'FolderSimpleMinus',
  'FolderSimplePlus',
  'FolderSimpleStar',
  'FolderSimpleUser',
  'FolderStar',
  'FolderUser',
  'Folders',
  'Football',
  'Footprints',
  'ForkKnife',
  'FrameCorners',
  'FramerLogo',
  'Function',
  'Funnel',
  'FunnelSimple',
  'GameController',
  'Garage',
  'GasCan',
  'GasPump',
  'Gauge',
  'Gavel',
  'Gear',
  'GearFine',
  'GearSix',
  'GenderFemale',
  'GenderIntersex',
  'GenderMale',
  'GenderNeuter',
  'GenderNonbinary',
  'GenderTransgender',
  'Ghost',
  'Gif',
  'Gift',
  'GitBranch',
  'GitCommit',
  'GitDiff',
  'GitFork',
  'GitMerge',
  'GitPullRequest',
  'GithubLogo',
  'GitlabLogo',
  'GitlabLogoSimple',
  'Globe',
  'GlobeHemisphereEast',
  'GlobeHemisphereWest',
  'GlobeSimple',
  'GlobeStand',
  'Goggles',
  'GoodreadsLogo',
  'GoogleCardboardLogo',
  'GoogleChromeLogo',
  'GoogleDriveLogo',
  'GoogleLogo',
  'GooglePhotosLogo',
  'GooglePlayLogo',
  'GooglePodcastsLogo',
  'Gradient',
  'GraduationCap',
  'Grains',
  'GrainsSlash',
  'Graph',
  'GridFour',
  'GridNine',
  'Guitar',
  'Hamburger',
  'Hammer',
  'Hand',
  'HandCoins',
  'HandEye',
  'HandFist',
  'HandGrabbing',
  'HandHeart',
  'HandPalm',
  'HandPointing',
  'HandSoap',
  'HandSwipeLeft',
  'HandSwipeRight',
  'HandTap',
  'HandWaving',
  'Handbag',
  'HandbagSimple',
  'HandsClapping',
  'HandsPraying',
  'Handshake',
  'HardDrive',
  'HardDrives',
  'Hash',
  'HashStraight',
  'Headlights',
  'Headphones',
  'Headset',
  'Heart',
  'HeartBreak',
  'HeartHalf',
  'HeartStraight',
  'HeartStraightBreak',
  'Heartbeat',
  'Hexagon',
  'HighHeel',
  'HighlighterCircle',
  'Hoodie',
  'Horse',
  'Hourglass',
  'HourglassHigh',
  'HourglassLow',
  'HourglassMedium',
  'HourglassSimple',
  'HourglassSimpleHigh',
  'HourglassSimpleLow',
  'House',
  'HouseLine',
  'HouseSimple',
  'IceCream',
  'IdentificationBadge',
  'IdentificationCard',
  'Image',
  'ImageSquare',
  'Images',
  'ImagesSquare',
  'Infinity',
  'Info',
  'InstagramLogo',
  'Intersect',
  'IntersectSquare',
  'IntersectThree',
  'Jeep',
  'Kanban',
  'Key',
  'KeyReturn',
  'Keyboard',
  'Keyhole',
  'Knife',
  'Ladder',
  'LadderSimple',
  'Lamp',
  'Laptop',
  'Layout',
  'Leaf',
  'Lifebuoy',
  'Lightbulb',
  'LightbulbFilament',
  'Lighthouse',
  'Lightning',
  'LightningA',
  'LightningSlash',
  'LineSegment',
  'LineSegments',
  'Link',
  'LinkBreak',
  'LinkSimple',
  'LinkSimpleBreak',
  'LinkSimpleHorizontal',
  'LinkedinLogo',
  'LinuxLogo',
  'List',
  'ListBullets',
  'ListChecks',
  'ListDashes',
  'ListMagnifyingGlass',
  'ListNumbers',
  'ListPlus',
  'Lock',
  'LockKey',
  'LockKeyOpen',
  'LockLaminated',
  'LockLaminatedOpen',
  'LockOpen',
  'LockSimple',
  'LockSimpleOpen',
  'Lockers',
  'MagicWand',
  'Magnet',
  'MagnetStraight',
  'MagnifyingGlass',
  'MagnifyingGlassMinus',
  'MagnifyingGlassPlus',
  'MapPin',
  'MapPinLine',
  'MapTrifold',
  'MarkerCircle',
  'Martini',
  'MaskHappy',
  'MaskSad',
  'MathOperations',
  'Medal',
  'MedalMilitary',
  'MediumLogo',
  'Megaphone',
  'MegaphoneSimple',
  'MessengerLogo',
  'MetaLogo',
  'Metronome',
  'Microphone',
  'MicrophoneSlash',
  'MicrophoneStage',
  'MicrosoftExcelLogo',
  'MicrosoftOutlookLogo',
  'MicrosoftTeamsLogo',
  'MicrosoftWordLogo',
  'Minus',
  'MinusCircle',
  'MinusSquare',
  'Money',
  'Monitor',
  'MonitorPlay',
  'Moon',
  'MoonStars',
  'Moped',
  'MopedFront',
  'Mosque',
  'Motorcycle',
  'Mountains',
  'Mouse',
  'MouseSimple',
  'MusicNote',
  'MusicNoteSimple',
  'MusicNotes',
  'MusicNotesPlus',
  'MusicNotesSimple',
  'NavigationArrow',
  'Needle',
  'Newspaper',
  'NewspaperClipping',
  'Notches',
  'Note',
  'NoteBlank',
  'NotePencil',
  'Notebook',
  'Notepad',
  'Notification',
  'NotionLogo',
  'NumberCircleEight',
  'NumberCircleFive',
  'NumberCircleFour',
  'NumberCircleNine',
  'NumberCircleOne',
  'NumberCircleSeven',
  'NumberCircleSix',
  'NumberCircleThree',
  'NumberCircleTwo',
  'NumberCircleZero',
  'NumberEight',
  'NumberFive',
  'NumberFour',
  'NumberNine',
  'NumberOne',
  'NumberSeven',
  'NumberSix',
  'NumberSquareEight',
  'NumberSquareFive',
  'NumberSquareFour',
  'NumberSquareNine',
  'NumberSquareOne',
  'NumberSquareSeven',
  'NumberSquareSix',
  'NumberSquareThree',
  'NumberSquareTwo',
  'NumberSquareZero',
  'NumberThree',
  'NumberTwo',
  'NumberZero',
  'Nut',
  'NyTimesLogo',
  'Octagon',
  'OfficeChair',
  'Option',
  'OrangeSlice',
  'Package',
  'PaintBrush',
  'PaintBrushBroad',
  'PaintBrushHousehold',
  'PaintBucket',
  'PaintRoller',
  'Palette',
  'Pants',
  'PaperPlane',
  'PaperPlaneRight',
  'PaperPlaneTilt',
  'Paperclip',
  'PaperclipHorizontal',
  'Parachute',
  'Paragraph',
  'Parallelogram',
  'Park',
  'Password',
  'Path',
  'PatreonLogo',
  'Pause',
  'PauseCircle',
  'PawPrint',
  'PaypalLogo',
  'Peace',
  'Pen',
  'PenNib',
  'PenNibStraight',
  'Pencil',
  'PencilCircle',
  'PencilLine',
  'PencilSimple',
  'PencilSimpleLine',
  'PencilSimpleSlash',
  'PencilSlash',
  'Pentagram',
  'Pepper',
  'Percent',
  'Person',
  'PersonArmsSpread',
  'PersonSimple',
  'PersonSimpleBike',
  'PersonSimpleRun',
  'PersonSimpleThrow',
  'PersonSimpleWalk',
  'Perspective',
  'Phone',
  'PhoneCall',
  'PhoneDisconnect',
  'PhoneIncoming',
  'PhoneOutgoing',
  'PhonePlus',
  'PhoneSlash',
  'PhoneX',
  'PhosphorLogo',
  'Pi',
  'PianoKeys',
  'PictureInPicture',
  'PiggyBank',
  'Pill',
  'PinterestLogo',
  'Pinwheel',
  'Pizza',
  'Placeholder',
  'Planet',
  'Plant',
  'Play',
  'PlayCircle',
  'PlayPause',
  'Playlist',
  'Plug',
  'PlugCharging',
  'Plugs',
  'PlugsConnected',
  'Plus',
  'PlusCircle',
  'PlusMinus',
  'PlusSquare',
  'PokerChip',
  'PoliceCar',
  'Polygon',
  'Popcorn',
  'PottedPlant',
  'Power',
  'Prescription',
  'Presentation',
  'PresentationChart',
  'Printer',
  'Prohibit',
  'ProhibitInset',
  'ProjectorScreen',
  'ProjectorScreenChart',
  'Pulse',
  'PushPin',
  'PushPinSimple',
  'PushPinSimpleSlash',
  'PushPinSlash',
  'PuzzlePiece',
  'QrCode',
  'Question',
  'Queue',
  'Quotes',
  'Radical',
  'Radio',
  'RadioButton',
  'Radioactive',
  'Rainbow',
  'RainbowCloud',
  'ReadCvLogo',
  'Receipt',
  'ReceiptX',
  'Record',
  'Rectangle',
  'Recycle',
  'RedditLogo',
  'Repeat',
  'RepeatOnce',
  'Rewind',
  'RewindCircle',
  'RoadHorizon',
  'Robot',
  'Rocket',
  'RocketLaunch',
  'Rows',
  'Rss',
  'RssSimple',
  'Rug',
  'Ruler',
  'Scales',
  'Scan',
  'Scissors',
  'Scooter',
  'Screencast',
  'ScribbleLoop',
  'Scroll',
  'Seal',
  'SealCheck',
  'SealQuestion',
  'SealWarning',
  'Selection',
  'SelectionAll',
  'SelectionBackground',
  'SelectionForeground',
  'SelectionInverse',
  'SelectionPlus',
  'SelectionSlash',
  'Shapes',
  'Share',
  'ShareFat',
  'ShareNetwork',
  'Shield',
  'ShieldCheck',
  'ShieldCheckered',
  'ShieldChevron',
  'ShieldPlus',
  'ShieldSlash',
  'ShieldStar',
  'ShieldWarning',
  'ShirtFolded',
  'ShootingStar',
  'ShoppingBag',
  'ShoppingBagOpen',
  'ShoppingCart',
  'ShoppingCartSimple',
  'Shower',
  'Shrimp',
  'Shuffle',
  'ShuffleAngular',
  'ShuffleSimple',
  'Sidebar',
  'SidebarSimple',
  'Sigma',
  'SignIn',
  'SignOut',
  'Signature',
  'Signpost',
  'SimCard',
  'Siren',
  'SketchLogo',
  'SkipBack',
  'SkipBackCircle',
  'SkipForward',
  'SkipForwardCircle',
  'Skull',
  'SlackLogo',
  'Sliders',
  'SlidersHorizontal',
  'Slideshow',
  'Smiley',
  'SmileyAngry',
  'SmileyBlank',
  'SmileyMeh',
  'SmileyNervous',
  'SmileySad',
  'SmileySticker',
  'SmileyWink',
  'SmileyXEyes',
  'SnapchatLogo',
  'Sneaker',
  'SneakerMove',
  'Snowflake',
  'SoccerBall',
  'SortAscending',
  'SortDescending',
  'SoundcloudLogo',
  'Spade',
  'Sparkle',
  'SpeakerHifi',
  'SpeakerHigh',
  'SpeakerLow',
  'SpeakerNone',
  'SpeakerSimpleHigh',
  'SpeakerSimpleLow',
  'SpeakerSimpleNone',
  'SpeakerSimpleSlash',
  'SpeakerSimpleX',
  'SpeakerSlash',
  'SpeakerX',
  'Spinner',
  'SpinnerGap',
  'Spiral',
  'SplitHorizontal',
  'SplitVertical',
  'SpotifyLogo',
  'Square',
  'SquareHalf',
  'SquareHalfBottom',
  'SquareLogo',
  'SquareSplitVertical',
  'SquaresFour',
  'Stack',
  'StackOverflowLogo',
  'StackSimple',
  'Stairs',
  'Stamp',
  'Star',
  'StarAndCrescent',
  'StarFour',
  'StarHalf',
  'StarOfDavid',
  'SteeringWheel',
  'Steps',
  'Stethoscope',
  'Sticker',
  'Stool',
  'Stop',
  'StopCircle',
  'Storefront',
  'Strategy',
  'StripeLogo',
  'Student',
  'Subtitles',
  'Subtract',
  'SubtractSquare',
  'Suitcase',
  'SuitcaseRolling',
  'SuitcaseSimple',
  'Sun',
  'SunDim',
  'SunHorizon',
  'Sunglasses',
  'Swap',
  'Swatches',
  'SwimmingPool',
  'Sword',
  'Synagogue',
  'Syringe',
  'TShirt',
  'Table',
  'Tabs',
  'Tag',
  'TagChevron',
  'TagSimple',
  'Target',
  'Taxi',
  'TelegramLogo',
  'Television',
  'TelevisionSimple',
  'TennisBall',
  'Tent',
  'Terminal',
  'TerminalWindow',
  'TestTube',
  'TextAUnderline',
  'TextAa',
  'TextAlignCenter',
  'TextAlignJustify',
  'TextAlignLeft',
  'TextAlignRight',
  'TextB',
  'TextColumns',
  'TextH',
  'TextHFive',
  'TextHFour',
  'TextHOne',
  'TextHSix',
  'TextHThree',
  'TextHTwo',
  'TextIndent',
  'TextItalic',
  'TextOutdent',
  'TextStrikethrough',
  'TextT',
  'TextUnderline',
  'Textbox',
  'Thermometer',
  'ThermometerCold',
  'ThermometerHot',
  'ThermometerSimple',
  'ThumbsDown',
  'ThumbsUp',
  'Ticket',
  'TidalLogo',
  'TiktokLogo',
  'Timer',
  'Tipi',
  'ToggleLeft',
  'ToggleRight',
  'Toilet',
  'ToiletPaper',
  'Toolbox',
  'Tooth',
  'Tote',
  'ToteSimple',
  'Trademark',
  'TrademarkRegistered',
  'TrafficCone',
  'TrafficSign',
  'TrafficSignal',
  'Train',
  'TrainRegional',
  'TrainSimple',
  'Tram',
  'Translate',
  'Trash',
  'TrashSimple',
  'Tray',
  'Tree',
  'TreeEvergreen',
  'TreePalm',
  'TreeStructure',
  'TrendDown',
  'TrendUp',
  'Triangle',
  'Trophy',
  'Truck',
  'TwitchLogo',
  'TwitterLogo',
  'Umbrella',
  'UmbrellaSimple',
  'Unite',
  'UniteSquare',
  'Upload',
  'UploadSimple',
  'Usb',
  'User',
  'UserCircle',
  'UserCircleGear',
  'UserCircleMinus',
  'UserCirclePlus',
  'UserFocus',
  'UserGear',
  'UserList',
  'UserMinus',
  'UserPlus',
  'UserRectangle',
  'UserSquare',
  'UserSwitch',
  'Users',
  'UsersFour',
  'UsersThree',
  'Van',
  'Vault',
  'Vibrate',
  'Video',
  'VideoCamera',
  'VideoCameraSlash',
  'Vignette',
  'VinylRecord',
  'VirtualReality',
  'Virus',
  'Voicemail',
  'Volleyball',
  'Wall',
  'Wallet',
  'Warehouse',
  'Warning',
  'WarningCircle',
  'WarningDiamond',
  'WarningOctagon',
  'Watch',
  'WaveSawtooth',
  'WaveSine',
  'WaveSquare',
  'WaveTriangle',
  'Waveform',
  'Waves',
  'Webcam',
  'WebcamSlash',
  'WebhooksLogo',
  'WechatLogo',
  'WhatsappLogo',
  'Wheelchair',
  'WheelchairMotion',
  'WifiHigh',
  'WifiLow',
  'WifiMedium',
  'WifiNone',
  'WifiSlash',
  'WifiX',
  'Wind',
  'WindowsLogo',
  'Wine',
  'Wrench',
  'X',
  'XCircle',
  'XSquare',
  'YinYang',
  'YoutubeLogo',
];
var moduleBaseUrl = 'https://framer.com/m/phosphor-icons/';
var weightOptions = ['thin', 'light', 'regular', 'bold', 'fill', 'duotone',];
var lowercaseIconKeyPairs = iconKeys.reduce((res, key,) => {
  res[key.toLowerCase()] = key;
  return res;
}, {},);
function Icon2(props,) {
  const { color, selectByList, iconSearch, iconSelection, onClick, onMouseDown, onMouseUp, onMouseEnter, onMouseLeave, weight, mirrored, } =
    props;
  const isMounted = useRef(false,);
  const iconKey = useIconSelection(iconKeys, selectByList, iconSearch, iconSelection, lowercaseIconKeyPairs,);
  const [SelectedIcon, setSelectedIcon,] = useState(iconKey === 'Home' ? House_default(React,) : null,);
  async function importModule() {
    try {
      const version = '0.0.53';
      const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`;
      const module = await import(
        /* webpackIgnore: true */
        /* @vite-ignore */
        iconModuleUrl
      );
      if (isMounted.current) setSelectedIcon(module.default(React,),);
    } catch (err) {
      if (isMounted.current) setSelectedIcon(null,);
    }
  }
  useEffect(() => {
    isMounted.current = true;
    importModule();
    return () => {
      isMounted.current = false;
    };
  }, [iconKey,],);
  const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
  const emptyState = isOnCanvas ? /* @__PURE__ */ _jsx(NullState, {},) : null;
  return /* @__PURE__ */ _jsx(motion.div, {
    style: { display: 'contents', },
    onClick,
    onMouseEnter,
    onMouseLeave,
    onMouseDown,
    onMouseUp,
    children: SelectedIcon
      ? /* @__PURE__ */ _jsx('svg', {
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 256 256',
        style: {
          userSelect: 'none',
          width: '100%',
          height: '100%',
          display: 'inline-block',
          fill: color,
          color,
          flexShrink: 0,
          transform: mirrored ? 'scale(-1, 1)' : void 0,
        },
        focusable: 'false',
        color,
        children: /* @__PURE__ */ _jsx(SelectedIcon, { color, weight, },),
      },)
      : emptyState,
  },);
}
Icon2.displayName = 'Phosphor';
Icon2.defaultProps = {
  width: 24,
  height: 24,
  iconSelection: 'House',
  iconSearch: 'House',
  color: '#66F',
  selectByList: true,
  weight: 'regular',
  mirrored: false,
};
addPropertyControls(Icon2, {
  selectByList: {
    type: ControlType.Boolean,
    title: 'Select',
    enabledTitle: 'List',
    disabledTitle: 'Search',
    defaultValue: Icon2.defaultProps.selectByList,
  },
  iconSelection: {
    type: ControlType.Enum,
    options: iconKeys,
    defaultValue: Icon2.defaultProps.iconSelection,
    title: 'Name',
    hidden: ({ selectByList, },) => !selectByList,
    description: 'Find every icon name on the [Phosphor site](https://phosphoricons.com/)',
  },
  iconSearch: {
    type: ControlType.String,
    title: 'Name',
    placeholder: 'Menu, Wifi, Box\u2026',
    hidden: ({ selectByList, },) => selectByList,
  },
  color: { type: ControlType.Color, title: 'Color', defaultValue: Icon2.defaultProps.color, },
  weight: {
    type: ControlType.Enum,
    title: 'Weight',
    optionTitles: weightOptions.map((piece,) => piece.charAt(0,).toUpperCase() + piece.slice(1,)),
    options: weightOptions,
    defaultValue: Icon2.defaultProps.weight,
  },
  mirrored: { type: ControlType.Boolean, enabledTitle: 'Yes', disabledTitle: 'No', defaultValue: Icon2.defaultProps.mirrored, },
  ...defaultEvents,
},);

// https :https://framerusercontent.com/modules/5eRz6tq1Npk5vmhePrXU/n3ElTPIomZl8KvIAfB6e/GPDKd6Ic6.js
import { fontStore, } from 'unframer';
fontStore.loadFonts(['FS;Switzer-semibold', 'FS;Switzer-black', 'FS;Switzer-black italic', 'FS;Switzer-semibold italic',],);
var fonts = [{
  explicitInter: true,
  fonts: [{
    family: 'Switzer',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/5SZVFDB7V52TI6ULVC6J3WQZQCIZVDV5/ODYPSTCUDMKSTYIPTV4CLQ7URIK7XYBJ/YS3VPNVO4B3TOJMEXDGFZQ4TLZGGSRZC.woff2',
    weight: '600',
  }, {
    family: 'Switzer',
    source: 'fontshare',
    style: 'normal',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/A54N3N7J5AY6YOPYJKLHF5VH7G7HSSUN/ERWIWIB434FMFHQFSSBD233EP3C62HOI/TOHQHMLIEIPKVF2JPM6SVKXFYGO5G2TJ.woff2',
    weight: '900',
  }, {
    family: 'Switzer',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/FQHNKZEV35SAMFWVFCFSORJXUNHNILL4/X4YCR4COAQTK5XB6JCDDBS7Q33AQWUAE/J7XVDQ2IJENINPUAVBDJNH3VEXVDSPQQ.woff2',
    weight: '900',
  }, {
    family: 'Switzer',
    source: 'fontshare',
    style: 'italic',
    url:
      'https://framerusercontent.com/third-party-assets/fontshare/wf/2UC2M25RQ2XRSGCBJRQ2G5SNXCROECQB/QJT3T33NN372363FJY5EO5D63GKDKLDK/IOAFMDAPNX3S6OL2GYQQJ2FFJIRSVB3N.woff2',
    weight: '600',
  },],
},];
var css = [
  '.framer-QXuyB .framer-styles-preset-13rf66x:not(.rich-text-wrapper), .framer-QXuyB .framer-styles-preset-13rf66x.rich-text-wrapper h5 { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.1px; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-QXuyB .framer-styles-preset-13rf66x:not(.rich-text-wrapper), .framer-QXuyB .framer-styles-preset-13rf66x.rich-text-wrapper h5 { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.1px; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-QXuyB .framer-styles-preset-13rf66x:not(.rich-text-wrapper), .framer-QXuyB .framer-styles-preset-13rf66x.rich-text-wrapper h5 { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", sans-serif; --framer-font-family-bold-italic: "Switzer", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 600; --framer-letter-spacing: -0.1px; --framer-line-height: 1.3em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className = 'framer-QXuyB';

// https :https://framerusercontent.com/modules/gCvR1QYSauSuqLNl6iXN/qhRKJCOtHZtL8Fc6ZC8o/PWn1k_MD2.js
import { fontStore as fontStore2, } from 'unframer';
fontStore2.loadFonts(['FS;Satoshi-regular', 'FS;Satoshi-bold', 'FS;Satoshi-bold italic', 'FS;Satoshi-italic',],);
var fonts2 = [{
  family: 'Satoshi',
  source: 'fontshare',
  style: 'normal',
  url:
    'https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2',
  weight: '400',
}, {
  family: 'Satoshi',
  source: 'fontshare',
  style: 'normal',
  url:
    'https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2',
  weight: '700',
}, {
  family: 'Satoshi',
  source: 'fontshare',
  style: 'italic',
  url:
    'https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2',
  weight: '700',
}, {
  family: 'Satoshi',
  source: 'fontshare',
  style: 'italic',
  url:
    'https://framerusercontent.com/third-party-assets/fontshare/wf/MPIFA4B3XXRNY2MJDGP6GOOOAF6EOCLO/W5E4ZFYPJ3V6JKMBGHB6YMITK6EWS2XA/QOMBWPST76ICDYF6WOBS7SQ7RBT67QW2.woff2',
  weight: '400',
},];
var css2 = [
  '.framer-0Y23w .framer-styles-preset-1cc56zh:not(.rich-text-wrapper), .framer-0Y23w .framer-styles-preset-1cc56zh.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0px; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: #000000; --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className2 = 'framer-0Y23w';

// https :https://framerusercontent.com/modules/2kAzXUriLe8jCJ21lwbH/U3fVOCM1YhAggVQivs7o/ygZFiHa3w.js
import { fontStore as fontStore3, } from 'unframer';
fontStore3.loadFonts([],);
var fonts3 = [];
var css3 = [
  '.framer-PeTIw .framer-styles-preset-1636swi:not(.rich-text-wrapper), .framer-PeTIw .framer-styles-preset-1636swi.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: #000000; --framer-link-hover-text-decoration: none; --framer-link-text-color: rgba(0, 0, 0, 0.7); --framer-link-text-decoration: none; }',
];
var className3 = 'framer-PeTIw';

// https :https://framerusercontent.com/modules/AO0ropceTgrkWLzadaTB/66aD3wpUPVI4b9ZsqDI2/FLXzApIyg.js
import { jsx as _jsx2, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ControlType as ControlType2,
  cx,
  getFonts,
  Link,
  RichText,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion as motion2, MotionConfigContext, } from 'unframer';
import * as React2 from 'react';
var PhosphorFonts = getFonts(Icon2,);
var enabledGestures = { d77WtBORe: { hover: true, }, I27BjI0db: { hover: true, }, uvXz5tOXs: { hover: true, }, };
var cycleOrder = ['d77WtBORe', 'uvXz5tOXs', 'I27BjI0db',];
var serializationHash = 'framer-TnArR';
var variantClassNames = { d77WtBORe: 'framer-v-os1iv6', I27BjI0db: 'framer-v-1s908fg', uvXz5tOXs: 'framer-v-2sp4oc', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transitions = { default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', }, };
var Transition = ({ value, children, },) => {
  const config = React2.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React2.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx2(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion2(React2.Fragment,);
var humanReadableVariantMap = { Large: 'd77WtBORe', Medium: 'uvXz5tOXs', Small: 'I27BjI0db', };
var getProps = ({ color, height, id, link, title, width, ...props },) => {
  var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
  return {
    ...props,
    bVToBLBTS: (_ref = title !== null && title !== void 0 ? title : props.bVToBLBTS) !== null && _ref !== void 0 ? _ref : 'Learn more',
    KqeH5xil_: (_ref1 = color !== null && color !== void 0 ? color : props.KqeH5xil_) !== null && _ref1 !== void 0 ? _ref1 : 'rgb(0, 0, 0)',
    MJWWsEY26: link !== null && link !== void 0 ? link : props.MJWWsEY26,
    variant:
      (_ref2 =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref2 !== void 0
        ? _ref2
        : 'd77WtBORe',
  };
};
var createLayoutDependency = (props, variants,) => variants.join('-',) + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className: className4, layoutId, variant, bVToBLBTS, KqeH5xil_, MJWWsEY26, ...restProps } = getProps(props,);
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, transition, variants, } = useVariantState({
    cycleOrder,
    defaultVariant: 'd77WtBORe',
    enabledGestures,
    transitions,
    variant,
    variantClassNames,
  },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React2.useRef(null,);
  const defaultLayoutId = React2.useId();
  const sharedStyleClassNames = [];
  return /* @__PURE__ */ _jsx2(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx2(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx2(Transition, {
        value: transition,
        children: /* @__PURE__ */ _jsx2(Link, {
          ...addPropertyOverrides({ I27BjI0db: { href: MJWWsEY26, }, uvXz5tOXs: { href: MJWWsEY26, }, }, baseVariant, gestureVariant,),
          children: /* @__PURE__ */ _jsxs(motion2.a, {
            ...restProps,
            className: `${cx(serializationHash, ...sharedStyleClassNames, 'framer-os1iv6', className4, classNames,)} framer-1o3ofrl`,
            'data-framer-name': 'Large',
            layoutDependency,
            layoutId: 'd77WtBORe',
            onHoverEnd: () => setGestureState({ isHovered: false, },),
            onHoverStart: () => setGestureState({ isHovered: true, },),
            onTap: () => setGestureState({ isPressed: false, },),
            onTapCancel: () => setGestureState({ isPressed: false, },),
            onTapStart: () => setGestureState({ isPressed: true, },),
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: { opacity: 1, ...style, },
            variants: { 'd77WtBORe-hover': { opacity: 0.5, }, 'I27BjI0db-hover': { opacity: 0.5, }, 'uvXz5tOXs-hover': { opacity: 0.5, }, },
            ...addPropertyOverrides(
              {
                'd77WtBORe-hover': { 'data-framer-name': void 0, },
                'I27BjI0db-hover': { 'data-framer-name': void 0, },
                'uvXz5tOXs-hover': { 'data-framer-name': void 0, },
                I27BjI0db: { 'data-framer-name': 'Small', },
                uvXz5tOXs: { 'data-framer-name': 'Medium', },
              },
              baseVariant,
              gestureVariant,
            ),
            children: [
              /* @__PURE__ */ _jsx2(RichText, {
                __fromCanvasComponent: true,
                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                    style: {
                      '--font-selector': 'RlM7U2F0b3NoaS1tZWRpdW0=',
                      '--framer-font-family': '"Satoshi", "Satoshi Placeholder", sans-serif',
                      '--framer-font-size': '20px',
                      '--framer-font-weight': '500',
                      '--framer-letter-spacing': '0px',
                      '--framer-line-height': '1.5em',
                      '--framer-text-alignment': 'center',
                      '--framer-text-color': 'var(--extracted-r6o4lv, var(--variable-reference-KqeH5xil_-FLXzApIyg))',
                    },
                    children: 'Learn more',
                  },),
                },),
                className: 'framer-td2eub',
                fonts: ['FS;Satoshi-medium',],
                layoutDependency,
                layoutId: 'PdZp_BQW6',
                style: {
                  '--extracted-r6o4lv': 'var(--variable-reference-KqeH5xil_-FLXzApIyg)',
                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                  '--framer-link-text-decoration': 'underline',
                  '--variable-reference-KqeH5xil_-FLXzApIyg': KqeH5xil_,
                },
                text: bVToBLBTS,
                verticalAlignment: 'top',
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    I27BjI0db: {
                      children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                        children: /* @__PURE__ */ _jsx2(motion2.p, {
                          style: {
                            '--font-selector': 'RlM7U2F0b3NoaS1tZWRpdW0=',
                            '--framer-font-family': '"Satoshi", "Satoshi Placeholder", sans-serif',
                            '--framer-font-size': '14px',
                            '--framer-font-weight': '500',
                            '--framer-letter-spacing': '-0.2px',
                            '--framer-line-height': '1.4em',
                            '--framer-text-alignment': 'center',
                            '--framer-text-color': 'var(--extracted-r6o4lv, var(--variable-reference-KqeH5xil_-FLXzApIyg))',
                          },
                          children: 'Learn more',
                        },),
                      },),
                    },
                    uvXz5tOXs: {
                      children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                        children: /* @__PURE__ */ _jsx2(motion2.p, {
                          style: {
                            '--font-selector': 'RlM7U2F0b3NoaS1tZWRpdW0=',
                            '--framer-font-family': '"Satoshi", "Satoshi Placeholder", sans-serif',
                            '--framer-font-weight': '500',
                            '--framer-letter-spacing': '0px',
                            '--framer-line-height': '1.5em',
                            '--framer-text-alignment': 'center',
                            '--framer-text-color': 'var(--extracted-r6o4lv, var(--variable-reference-KqeH5xil_-FLXzApIyg))',
                          },
                          children: 'Learn more',
                        },),
                      },),
                    },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              },),
              /* @__PURE__ */ _jsx2(motion2.div, {
                className: 'framer-1xgmqj0',
                'data-framer-name': 'Icon',
                layoutDependency,
                layoutId: 'btakL8rlb',
                children: /* @__PURE__ */ _jsx2(motion2.div, {
                  className: 'framer-169dxvj-container',
                  layoutDependency,
                  layoutId: 'VjoCq4H5g-container',
                  children: /* @__PURE__ */ _jsx2(Icon2, {
                    color: KqeH5xil_,
                    height: '100%',
                    iconSearch: 'House',
                    iconSelection: 'ArrowRight',
                    id: 'VjoCq4H5g',
                    layoutId: 'VjoCq4H5g',
                    mirrored: false,
                    selectByList: true,
                    style: { height: '100%', width: '100%', },
                    weight: 'bold',
                    width: '100%',
                  },),
                },),
              },),
            ],
          },),
        },),
      },),
    },),
  },);
},);
var css4 = [
  '.framer-TnArR[data-border="true"]::after, .framer-TnArR [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-TnArR.framer-1o3ofrl, .framer-TnArR .framer-1o3ofrl { display: block; }',
  '.framer-TnArR.framer-os1iv6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }',
  '.framer-TnArR .framer-td2eub { flex: none; height: auto; position: relative; white-space: pre; width: auto; }',
  '.framer-TnArR .framer-1xgmqj0 { flex: none; height: 20px; overflow: visible; position: relative; width: 20px; }',
  '.framer-TnArR .framer-169dxvj-container { bottom: -1px; flex: none; height: 20px; left: 0px; position: absolute; right: 0px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TnArR.framer-os1iv6 { gap: 0px; } .framer-TnArR.framer-os1iv6 > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-TnArR.framer-os1iv6 > :first-child { margin-left: 0px; } .framer-TnArR.framer-os1iv6 > :last-child { margin-right: 0px; } }',
  '.framer-TnArR.framer-v-2sp4oc.framer-os1iv6 { gap: 4px; text-decoration: none; }',
  '.framer-TnArR.framer-v-2sp4oc .framer-169dxvj-container { bottom: 1px; height: 16px; right: unset; width: 16px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TnArR.framer-v-2sp4oc.framer-os1iv6 { gap: 0px; } .framer-TnArR.framer-v-2sp4oc.framer-os1iv6 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-TnArR.framer-v-2sp4oc.framer-os1iv6 > :first-child { margin-left: 0px; } .framer-TnArR.framer-v-2sp4oc.framer-os1iv6 > :last-child { margin-right: 0px; } }',
  '.framer-TnArR.framer-v-1s908fg.framer-os1iv6 { gap: 2px; text-decoration: none; }',
  '.framer-TnArR.framer-v-1s908fg .framer-1xgmqj0 { height: 16px; width: 16px; }',
  '.framer-TnArR.framer-v-1s908fg .framer-169dxvj-container { bottom: 1px; height: 13px; left: calc(50.00000000000002% - 13px / 2); right: unset; width: 13px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TnArR.framer-v-1s908fg.framer-os1iv6 { gap: 0px; } .framer-TnArR.framer-v-1s908fg.framer-os1iv6 > * { margin: 0px; margin-left: calc(2px / 2); margin-right: calc(2px / 2); } .framer-TnArR.framer-v-1s908fg.framer-os1iv6 > :first-child { margin-left: 0px; } .framer-TnArR.framer-v-1s908fg.framer-os1iv6 > :last-child { margin-right: 0px; } }',
  '.framer-TnArR.framer-v-os1iv6.hover .framer-169dxvj-container { left: unset; right: -3px; width: 20px; }',
  '.framer-TnArR.framer-v-2sp4oc.hover .framer-169dxvj-container { left: calc(50.00000000000002% - 16px / 2); right: unset; }',
  '.framer-TnArR.framer-v-1s908fg.hover .framer-169dxvj-container { left: unset; right: 0px; }',
];
var FramerFLXzApIyg = withCSS(Component2, css4, 'framer-TnArR',);
var stdin_default = FramerFLXzApIyg;
FramerFLXzApIyg.displayName = 'CTA';
FramerFLXzApIyg.defaultProps = { height: 30, width: 128.5, };
addPropertyControls2(FramerFLXzApIyg, {
  variant: {
    options: ['d77WtBORe', 'uvXz5tOXs', 'I27BjI0db',],
    optionTitles: ['Large', 'Medium', 'Small',],
    title: 'Variant',
    type: ControlType2.Enum,
  },
  bVToBLBTS: { defaultValue: 'Learn more', displayTextArea: false, title: 'Title', type: ControlType2.String, },
  KqeH5xil_: { defaultValue: 'rgb(0, 0, 0)', title: 'Color', type: ControlType2.Color, },
  MJWWsEY26: { title: 'Link', type: ControlType2.Link, },
},);
addFonts(FramerFLXzApIyg, [{
  family: 'Satoshi',
  source: 'fontshare',
  style: 'normal',
  url:
    'https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2',
  weight: '500',
}, ...PhosphorFonts,],);

// https :https://framerusercontent.com/modules/5RKlpLgYNk7duxXcZDXd/6Z8wlYy6uR0TX0tUNvYW/Wk_vueg3a.js
var PhosphorFonts2 = getFonts2(Icon,);
var CTAFonts = getFonts2(stdin_default,);
var Phosphor1Controls = getPropertyControls(Icon2,);
var cycleOrder2 = ['s4zc08oCU', 'FGm07QIce', 'Gp4GjxKpI', 'EsJzlpnfQ',];
var serializationHash2 = 'framer-UJJ9E';
var variantClassNames2 = {
  EsJzlpnfQ: 'framer-v-ku9xom',
  FGm07QIce: 'framer-v-1iom2qn',
  Gp4GjxKpI: 'framer-v-i118qm',
  s4zc08oCU: 'framer-v-x9hesa',
};
function addPropertyOverrides2(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var toResponsiveImage = (value,) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value;
  }
  return typeof value === 'string' ? { src: value, } : void 0;
};
var Transition2 = ({ value, children, },) => {
  const config = React3.useContext(MotionConfigContext2,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React3.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx3(MotionConfigContext2.Provider, { value: contextValue, children, },);
};
var Variants2 = motion3(React3.Fragment,);
var humanReadableVariantMap2 = {
  '\u26AA\uFE0F Day Left': 'FGm07QIce',
  '\u26AA\uFE0F Day Middle': 's4zc08oCU',
  '\u26AB\uFE0F Night Left': 'EsJzlpnfQ',
  '\u26AB\uFE0F Night Middle': 'Gp4GjxKpI',
};
var getProps2 = ({ cTA, cTA1, height, icon, icon1, icon2, iconBackground, id, image, image1, link, text, title, width, ...props },) => {
  var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _humanReadableVariantMap_props_variant, _ref7, _ref8;
  return {
    ...props,
    aa5hKvvkV: (_ref = icon1 !== null && icon1 !== void 0 ? icon1 : props.aa5hKvvkV) !== null && _ref !== void 0 ? _ref : 'Leaf',
    BFuTBK47u: (_ref1 = text !== null && text !== void 0 ? text : props.BFuTBK47u) !== null && _ref1 !== void 0
      ? _ref1
      : 'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
    cX1P9xQse: link !== null && link !== void 0 ? link : props.cX1P9xQse,
    jFgwazo_q: (_ref2 = icon2 !== null && icon2 !== void 0 ? icon2 : props.jFgwazo_q) !== null && _ref2 !== void 0
      ? _ref2
      : 'rgb(255, 255, 255)',
    oc_8kOa9a: (_ref3 = title !== null && title !== void 0 ? title : props.oc_8kOa9a) !== null && _ref3 !== void 0
      ? _ref3
      : 'Integration ecosystem',
    OLqpcuIeL: image !== null && image !== void 0 ? image : props.OLqpcuIeL,
    PFec_i8Ff: (_ref4 = image1 !== null && image1 !== void 0 ? image1 : props.PFec_i8Ff) !== null && _ref4 !== void 0 ? _ref4 : {
      src: 'https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg?scale-down-to=512',
      srcSet:
        'https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/WwuSEtN77IMXeoOP6vheQadgDRA.jpg 9600w',
    },
    qkbS0bCx8: (_ref5 = cTA1 !== null && cTA1 !== void 0 ? cTA1 : props.qkbS0bCx8) !== null && _ref5 !== void 0 ? _ref5 : 'Learn more',
    UaS05r1yh:
      (_ref6 = iconBackground !== null && iconBackground !== void 0 ? iconBackground : props.UaS05r1yh) !== null && _ref6 !== void 0
        ? _ref6
        : 'rgb(0, 0, 0)',
    variant:
      (_ref7 =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap2[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref7 !== void 0
        ? _ref7
        : 's4zc08oCU',
    Y3X4CKI40: (_ref8 = icon !== null && icon !== void 0 ? icon : props.Y3X4CKI40) !== null && _ref8 !== void 0 ? _ref8 : true,
    ZA2T3dGW4: cTA !== null && cTA !== void 0 ? cTA : props.ZA2T3dGW4,
  };
};
var createLayoutDependency2 = (props, variants,) => variants.join('-',) + props.layoutDependency;
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo2();
  const {
    style,
    className: className4,
    layoutId,
    variant,
    OLqpcuIeL,
    PFec_i8Ff,
    Y3X4CKI40,
    aa5hKvvkV,
    UaS05r1yh,
    jFgwazo_q,
    oc_8kOa9a,
    BFuTBK47u,
    ZA2T3dGW4,
    qkbS0bCx8,
    cX1P9xQse,
    ...restProps
  } = getProps2(props,);
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, variants, } = useVariantState2({
    cycleOrder: cycleOrder2,
    defaultVariant: 's4zc08oCU',
    variant,
    variantClassNames: variantClassNames2,
  },);
  const layoutDependency = createLayoutDependency2(props, variants,);
  const ref1 = React3.useRef(null,);
  const defaultLayoutId = React3.useId();
  const sharedStyleClassNames = [className, className3, className2,];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx3(LayoutGroup2, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx3(Variants2, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx3(Transition2, {
        value: transition1,
        children: /* @__PURE__ */ _jsxs2(motion3.div, {
          ...restProps,
          className: cx2(serializationHash2, ...sharedStyleClassNames, 'framer-x9hesa', className4, classNames,),
          'data-border': true,
          'data-framer-name': '\u26AA\uFE0F Day Middle',
          layoutDependency,
          layoutId: 's4zc08oCU',
          onHoverEnd: () => setGestureState({ isHovered: false, },),
          onHoverStart: () => setGestureState({ isHovered: true, },),
          onTap: () => setGestureState({ isPressed: false, },),
          onTapCancel: () => setGestureState({ isPressed: false, },),
          onTapStart: () => setGestureState({ isPressed: true, },),
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            '--border-bottom-width': '1px',
            '--border-color': 'var(--token-700a1961-c2b8-4f37-ad37-e3c28ea0fc93, rgba(34, 34, 34, 0.1))',
            '--border-left-width': '1px',
            '--border-right-width': '1px',
            '--border-style': 'solid',
            '--border-top-width': '1px',
            backgroundColor: 'var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgb(255, 255, 255))',
            borderBottomLeftRadius: 20,
            borderBottomRightRadius: 20,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            boxShadow: '0px 10px 20px 0px rgba(0, 0, 0, 0.1)',
            ...style,
          },
          variants: {
            EsJzlpnfQ: {
              '--border-color': 'var(--token-58a904ff-197a-49b3-8356-adaa464e1642, rgba(255, 255, 255, 0.12))',
              backgroundColor: 'var(--token-fae2c128-35fb-45de-a6c2-32169f920c68, rgb(13, 13, 13))',
            },
            Gp4GjxKpI: {
              '--border-color': 'var(--token-58a904ff-197a-49b3-8356-adaa464e1642, rgba(255, 255, 255, 0.12))',
              backgroundColor: 'var(--token-fae2c128-35fb-45de-a6c2-32169f920c68, rgb(13, 13, 13))',
            },
          },
          ...addPropertyOverrides2(
            {
              EsJzlpnfQ: { 'data-framer-name': '\u26AB\uFE0F Night Left', },
              FGm07QIce: { 'data-framer-name': '\u26AA\uFE0F Day Left', },
              Gp4GjxKpI: { 'data-framer-name': '\u26AB\uFE0F Night Middle', },
            },
            baseVariant,
            gestureVariant,
          ),
          children: [
            OLqpcuIeL && /* @__PURE__ */ _jsx3(Image, {
              background: {
                alt: '',
                fit: 'fill',
                intrinsicHeight: 5400,
                intrinsicWidth: 9600,
                pixelHeight: 5400,
                pixelWidth: 9600,
                sizes: `calc(${
                  (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                } - 80px)`,
                ...toResponsiveImage(PFec_i8Ff,),
              },
              className: 'framer-1vknc1w',
              'data-border': true,
              layoutDependency,
              layoutId: 'MR2TfNxSa',
              style: {
                '--border-bottom-width': '1px',
                '--border-color': 'var(--token-700a1961-c2b8-4f37-ad37-e3c28ea0fc93, rgba(34, 34, 34, 0.1))',
                '--border-left-width': '1px',
                '--border-right-width': '1px',
                '--border-style': 'solid',
                '--border-top-width': '1px',
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
              },
            },),
            Y3X4CKI40 && /* @__PURE__ */ _jsx3(motion3.div, {
              className: 'framer-1hypwoz',
              'data-framer-name': 'Icon',
              layoutDependency,
              layoutId: 'w1rINmHsZ',
              style: {
                backgroundColor: UaS05r1yh,
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
              },
              children: /* @__PURE__ */ _jsx3(ComponentViewportProvider, {
                children: /* @__PURE__ */ _jsx3(motion3.div, {
                  className: 'framer-5o30rf-container',
                  layoutDependency,
                  layoutId: 'eGjgS4oFq-container',
                  children: /* @__PURE__ */ _jsx3(Icon, {
                    color: jFgwazo_q,
                    height: '100%',
                    iconSearch: 'House',
                    iconSelection: aa5hKvvkV,
                    id: 'eGjgS4oFq',
                    layoutId: 'eGjgS4oFq',
                    mirrored: false,
                    selectByList: true,
                    style: { height: '100%', width: '100%', },
                    weight: 'regular',
                    width: '100%',
                  },),
                },),
              },),
            },),
            /* @__PURE__ */ _jsxs2(motion3.div, {
              className: 'framer-2bn85y',
              layoutDependency,
              layoutId: 'WrCPpjaHj',
              children: [
                /* @__PURE__ */ _jsx3(RichText2, {
                  __fromCanvasComponent: true,
                  children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                    children: /* @__PURE__ */ _jsx3(motion3.h5, {
                      className: 'framer-styles-preset-13rf66x',
                      'data-styles-preset': 'GPDKd6Ic6',
                      style: { '--framer-text-color': 'var(--extracted-1lwpl3i, rgb(0, 0, 0))', },
                      children: /* @__PURE__ */ _jsx3(Link2, {
                        href: '/another-page?',
                        openInNewTab: false,
                        smoothScroll: false,
                        children: /* @__PURE__ */ _jsx3(motion3.a, {
                          className: 'framer-styles-preset-1636swi',
                          'data-styles-preset': 'ygZFiHa3w',
                          children: 'Integration ecosystem',
                        },),
                      },),
                    },),
                  },),
                  className: 'framer-1qfo9mb',
                  fonts: ['Inter',],
                  layoutDependency,
                  layoutId: 'VDM1CnOXu',
                  style: { '--extracted-1lwpl3i': 'rgb(0, 0, 0)', },
                  text: oc_8kOa9a,
                  variants: {
                    EsJzlpnfQ: { '--extracted-1lwpl3i': 'rgb(255, 255, 255)', },
                    Gp4GjxKpI: { '--extracted-1lwpl3i': 'rgb(255, 255, 255)', },
                  },
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                  ...addPropertyOverrides2(
                    {
                      EsJzlpnfQ: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.h5, {
                            className: 'framer-styles-preset-13rf66x',
                            'data-styles-preset': 'GPDKd6Ic6',
                            style: {
                              '--framer-text-alignment': 'left',
                              '--framer-text-color': 'var(--extracted-1lwpl3i, rgb(255, 255, 255))',
                            },
                            children: /* @__PURE__ */ _jsx3(Link2, {
                              href: '/another-page?',
                              openInNewTab: false,
                              smoothScroll: false,
                              children: /* @__PURE__ */ _jsx3(motion3.a, {
                                className: 'framer-styles-preset-1636swi',
                                'data-styles-preset': 'ygZFiHa3w',
                                children: 'Integration ecosystem',
                              },),
                            },),
                          },),
                        },),
                      },
                      FGm07QIce: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.h5, {
                            className: 'framer-styles-preset-13rf66x',
                            'data-styles-preset': 'GPDKd6Ic6',
                            style: { '--framer-text-alignment': 'left', '--framer-text-color': 'var(--extracted-1lwpl3i, rgb(0, 0, 0))', },
                            children: /* @__PURE__ */ _jsx3(Link2, {
                              href: '/another-page?',
                              openInNewTab: false,
                              smoothScroll: false,
                              children: /* @__PURE__ */ _jsx3(motion3.a, {
                                className: 'framer-styles-preset-1636swi',
                                'data-styles-preset': 'ygZFiHa3w',
                                children: 'Integration ecosystem',
                              },),
                            },),
                          },),
                        },),
                      },
                      Gp4GjxKpI: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.h5, {
                            className: 'framer-styles-preset-13rf66x',
                            'data-styles-preset': 'GPDKd6Ic6',
                            style: { '--framer-text-color': 'var(--extracted-1lwpl3i, rgb(255, 255, 255))', },
                            children: /* @__PURE__ */ _jsx3(Link2, {
                              href: '/another-page?',
                              openInNewTab: false,
                              smoothScroll: false,
                              children: /* @__PURE__ */ _jsx3(motion3.a, {
                                className: 'framer-styles-preset-1636swi',
                                'data-styles-preset': 'ygZFiHa3w',
                                children: 'Integration ecosystem',
                              },),
                            },),
                          },),
                        },),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                },),
                /* @__PURE__ */ _jsx3(RichText2, {
                  __fromCanvasComponent: true,
                  children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                    children: /* @__PURE__ */ _jsx3(motion3.p, {
                      className: 'framer-styles-preset-1cc56zh',
                      'data-styles-preset': 'PWn1k_MD2',
                      style: { '--framer-text-alignment': 'center', '--framer-text-color': 'var(--extracted-r6o4lv, hsl(0, 0%, 0%))', },
                      children:
                        'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
                    },),
                  },),
                  className: 'framer-mz35j0',
                  fonts: ['Inter',],
                  layoutDependency,
                  layoutId: 'DKc1gyg4g',
                  style: {
                    '--extracted-r6o4lv': 'hsl(0, 0%, 0%)',
                    '--framer-link-text-color': 'rgb(0, 153, 255)',
                    '--framer-link-text-decoration': 'underline',
                    opacity: 0.8,
                  },
                  text: BFuTBK47u,
                  variants: {
                    EsJzlpnfQ: { '--extracted-r6o4lv': 'rgb(255, 255, 255)', },
                    FGm07QIce: { '--extracted-r6o4lv': 'rgb(0, 0, 0)', },
                    Gp4GjxKpI: { '--extracted-r6o4lv': 'rgb(255, 255, 255)', },
                  },
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                  ...addPropertyOverrides2(
                    {
                      EsJzlpnfQ: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.p, {
                            className: 'framer-styles-preset-1cc56zh',
                            'data-styles-preset': 'PWn1k_MD2',
                            style: {
                              '--framer-text-alignment': 'left',
                              '--framer-text-color': 'var(--extracted-r6o4lv, rgb(255, 255, 255))',
                            },
                            children:
                              'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
                          },),
                        },),
                      },
                      FGm07QIce: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.p, {
                            className: 'framer-styles-preset-1cc56zh',
                            'data-styles-preset': 'PWn1k_MD2',
                            style: { '--framer-text-alignment': 'left', '--framer-text-color': 'var(--extracted-r6o4lv, rgb(0, 0, 0))', },
                            children:
                              'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
                          },),
                        },),
                      },
                      Gp4GjxKpI: {
                        children: /* @__PURE__ */ _jsx3(React3.Fragment, {
                          children: /* @__PURE__ */ _jsx3(motion3.p, {
                            className: 'framer-styles-preset-1cc56zh',
                            'data-styles-preset': 'PWn1k_MD2',
                            style: {
                              '--framer-text-alignment': 'center',
                              '--framer-text-color': 'var(--extracted-r6o4lv, rgb(255, 255, 255))',
                            },
                            children:
                              'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
                          },),
                        },),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                },),
                ZA2T3dGW4 && /* @__PURE__ */ _jsx3(ComponentViewportProvider, {
                  children: /* @__PURE__ */ _jsx3(motion3.div, {
                    className: 'framer-14ygfl1-container',
                    layoutDependency,
                    layoutId: 'hqHfwdps7-container',
                    children: /* @__PURE__ */ _jsx3(stdin_default, {
                      bVToBLBTS: qkbS0bCx8,
                      height: '100%',
                      id: 'hqHfwdps7',
                      KqeH5xil_: 'rgb(0, 0, 0)',
                      layoutId: 'hqHfwdps7',
                      MJWWsEY26: cX1P9xQse,
                      variant: 'uvXz5tOXs',
                      width: '100%',
                    },),
                  },),
                },),
              ],
            },),
          ],
        },),
      },),
    },),
  },);
},);
var css5 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-UJJ9E.framer-qu831b, .framer-UJJ9E .framer-qu831b { display: block; }',
  '.framer-UJJ9E.framer-x9hesa { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; max-width: 400px; overflow: hidden; padding: 40px 40px 40px 40px; position: relative; width: 360px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-UJJ9E .framer-1vknc1w { flex: none; height: 200px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }',
  '.framer-UJJ9E .framer-1hypwoz { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 56px); justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 56px; will-change: var(--framer-will-change-override, transform); }',
  '.framer-UJJ9E .framer-5o30rf-container { flex: none; height: 32px; position: relative; width: 32px; }',
  '.framer-UJJ9E .framer-2bn85y { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-UJJ9E .framer-1qfo9mb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-UJJ9E .framer-mz35j0 { flex: none; height: auto; max-width: 400px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-UJJ9E .framer-14ygfl1-container { flex: none; height: auto; position: relative; width: auto; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-UJJ9E.framer-x9hesa, .framer-UJJ9E .framer-1hypwoz, .framer-UJJ9E .framer-2bn85y { gap: 0px; } .framer-UJJ9E.framer-x9hesa > * { margin: 0px; margin-bottom: calc(30px / 2); margin-top: calc(30px / 2); } .framer-UJJ9E.framer-x9hesa > :first-child, .framer-UJJ9E .framer-2bn85y > :first-child { margin-top: 0px; } .framer-UJJ9E.framer-x9hesa > :last-child, .framer-UJJ9E .framer-2bn85y > :last-child { margin-bottom: 0px; } .framer-UJJ9E .framer-1hypwoz > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-UJJ9E .framer-1hypwoz > :first-child { margin-left: 0px; } .framer-UJJ9E .framer-1hypwoz > :last-child { margin-right: 0px; } .framer-UJJ9E .framer-2bn85y > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }',
  '.framer-UJJ9E.framer-v-1iom2qn.framer-x9hesa, .framer-UJJ9E.framer-v-1iom2qn .framer-2bn85y, .framer-UJJ9E.framer-v-ku9xom.framer-x9hesa, .framer-UJJ9E.framer-v-ku9xom .framer-2bn85y { align-content: flex-start; align-items: flex-start; }',
  ...css,
  ...css3,
  ...css2,
  '.framer-UJJ9E[data-border="true"]::after, .framer-UJJ9E [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerWk_vueg3a = withCSS2(Component3, css5, 'framer-UJJ9E',);
var stdin_default2 = FramerWk_vueg3a;
FramerWk_vueg3a.displayName = 'Feature Card';
FramerWk_vueg3a.defaultProps = { height: 270, width: 360, };
addPropertyControls3(FramerWk_vueg3a, {
  variant: {
    options: ['s4zc08oCU', 'FGm07QIce', 'Gp4GjxKpI', 'EsJzlpnfQ',],
    optionTitles: ['\u26AA\uFE0F Day Middle', '\u26AA\uFE0F Day Left', '\u26AB\uFE0F Night Middle', '\u26AB\uFE0F Night Left',],
    title: 'Variant',
    type: ControlType3.Enum,
  },
  OLqpcuIeL: { defaultValue: false, title: 'Image', type: ControlType3.Boolean, },
  PFec_i8Ff: {
    __defaultAssetReference:
      'data:framer/asset-reference,WwuSEtN77IMXeoOP6vheQadgDRA.jpg?originalFilename=photo-1709274296402-f6e96caaa1eb%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfGFsbHwzfHx8fHx8Mnx8MTcwOTI4OTA5OXw%26ixlib%3Drb-4.0.jpg&preferredSize=auto',
    title: 'Image',
    type: ControlType3.ResponsiveImage,
  },
  Y3X4CKI40: { defaultValue: true, title: 'Icon', type: ControlType3.Boolean, },
  aa5hKvvkV: (Phosphor1Controls === null || Phosphor1Controls === void 0 ? void 0 : Phosphor1Controls['iconSelection']) &&
    { ...Phosphor1Controls['iconSelection'], defaultValue: 'Leaf', description: void 0, hidden: void 0, title: 'Icon', },
  UaS05r1yh: { defaultValue: 'rgb(0, 0, 0)', title: 'Icon Background', type: ControlType3.Color, },
  jFgwazo_q: { defaultValue: 'rgb(255, 255, 255)', title: 'Icon', type: ControlType3.Color, },
  oc_8kOa9a: { defaultValue: 'Integration ecosystem', displayTextArea: true, title: 'Title', type: ControlType3.String, },
  BFuTBK47u: {
    defaultValue: 'Enhance your productivity by connecting with your favorite tools, keeping all your essentials in one place.',
    displayTextArea: true,
    title: 'Text',
    type: ControlType3.String,
  },
  ZA2T3dGW4: { defaultValue: false, title: 'CTA', type: ControlType3.Boolean, },
  qkbS0bCx8: { defaultValue: 'Learn more', displayTextArea: false, title: 'CTA', type: ControlType3.String, },
  cX1P9xQse: { title: 'Link', type: ControlType3.Link, },
},);
addFonts2(FramerWk_vueg3a, [
  {
    explicitInter: true,
    fonts: [{
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2',
      weight: '400',
    },],
  },
  ...PhosphorFonts2,
  ...CTAFonts,
  ...getFontsFromSharedStyle(fonts,),
  ...getFontsFromSharedStyle(fonts3,),
  ...getFontsFromSharedStyle(fonts2,),
], { supportsExplicitInterCodegen: true, },);

// virtual:card
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
stdin_default2.Responsive = (props,) => {
  return /* @__PURE__ */ jsx(WithFramerBreakpoints, { Component: stdin_default2, ...props, },);
};
var card_default = stdin_default2;
export { card_default as default, };
