'use client';
import { defaultEvents, NullState, useIconSelection, } from './chunk-E2XMAXEX.js';
import './chunk-6C3VEZWH.js';

// https:https://framerusercontent.com/modules/YPPQaawwYaqGsNWuaEiH/SqAKJIFKTXoDzFa1Z6rs/q64yDrOL3.js
import { jsx as _jsx2, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx,
  getFonts,
  Image,
  Link,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from 'unframer/dist/framer';
import { LayoutGroup, motion as motion2, MotionConfigContext, } from 'unframer';
import * as React2 from 'react';

// https:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/H4OHcdXxZyPVKySUy1y2/Phosphor.js
import { jsx as _jsx, } from 'react/jsx-runtime';
import * as React from 'react';
import { useEffect, useRef, useState, } from 'react';
import { addPropertyControls, ControlType, RenderTarget, } from 'unframer/dist/framer';
import { motion, } from 'unframer';

// https:https://framer.com/m/phosphor-icons/House.js@0.0.50
var Component;
var House_default = (React3,) => {
  if (!Component) {
    const renderPathForWeight = (weight, color, pathsByWeight2,) =>
      !!pathsByWeight2.get(weight,) ? pathsByWeight2.get(weight,)(color,) : null;
    const pathsByWeight = /* @__PURE__ */ new Map();
    pathsByWeight.set(
      'bold',
      (color,) =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            fill: 'none',
            stroke: color,
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            strokeWidth: '24',
          },),
        ),
    );
    pathsByWeight.set(
      'duotone',
      (color,) =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            opacity: '0.2',
          },),
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            fill: 'none',
            stroke: color,
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            strokeWidth: '16',
          },),
        ),
    );
    pathsByWeight.set(
      'fill',
      () =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M218.8,103.7,138.8,31a16,16,0,0,0-21.6,0l-80,72.7A16,16,0,0,0,32,115.5v92.1a16.4,16.4,0,0,0,4,11A15.9,15.9,0,0,0,48,224H96a8,8,0,0,0,8-8V168a8,8,0,0,1,8-8h32a8,8,0,0,1,8,8v48a8,8,0,0,0,8,8h48a15.6,15.6,0,0,0,7.6-1.9A16.1,16.1,0,0,0,224,208V115.5A16,16,0,0,0,218.8,103.7Z',
          },),
        ),
    );
    pathsByWeight.set(
      'light',
      (color,) =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            fill: 'none',
            stroke: color,
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            strokeWidth: '12',
          },),
        ),
    );
    pathsByWeight.set(
      'thin',
      (color,) =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            fill: 'none',
            stroke: color,
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            strokeWidth: '8',
          },),
        ),
    );
    pathsByWeight.set(
      'regular',
      (color,) =>
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement('path', {
            d: 'M152,208V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.5a8.3,8.3,0,0,1,2.6-5.9l80-72.7a8,8,0,0,1,10.8,0l80,72.7a8.3,8.3,0,0,1,2.6,5.9V208a8,8,0,0,1-8,8H160A8,8,0,0,1,152,208Z',
            fill: 'none',
            stroke: color,
            strokeLinecap: 'round',
            strokeLinejoin: 'round',
            strokeWidth: '16',
          },),
        ),
    );
    const renderPath = (weight, color,) => renderPathForWeight(weight, color, pathsByWeight,);
    const House = React3.forwardRef((props, ref,) =>
      /* @__PURE__ */ React3.createElement('g', {
        ref,
        ...props,
      }, renderPath(props.weight, props.color,),)
    );
    House.displayName = 'House';
    Component = House;
  }
  return Component;
};

// https:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/H4OHcdXxZyPVKySUy1y2/Phosphor.js
var iconKeys = [
  'Activity',
  'AddressBook',
  'Airplane',
  'AirplaneInFlight',
  'AirplaneLanding',
  'AirplaneTakeoff',
  'AirplaneTilt',
  'Airplay',
  'Alarm',
  'Alien',
  'AlignBottom',
  'AlignBottomSimple',
  'AlignCenterVertical',
  'AlignLeft',
  'AlignLeftSimple',
  'AlignRight',
  'AlignRightSimple',
  'AlignTop',
  'AlignTopSimple',
  'Anchor',
  'AnchorSimple',
  'AndroidLogo',
  'AngularLogo',
  'Aperture',
  'AppStoreLogo',
  'AppWindow',
  'AppleLogo',
  'ApplePodcastsLogo',
  'Archive',
  'ArchiveBox',
  'ArchiveTray',
  'Armchair',
  'ArrowArcLeft',
  'ArrowArcRight',
  'ArrowBendDownLeft',
  'ArrowBendDownRight',
  'ArrowBendLeftDown',
  'ArrowBendLeftUp',
  'ArrowBendRightDown',
  'ArrowBendRightUp',
  'ArrowBendUpLeft',
  'ArrowBendUpRight',
  'ArrowCircleDown',
  'ArrowCircleDownLeft',
  'ArrowCircleDownRight',
  'ArrowCircleLeft',
  'ArrowCircleRight',
  'ArrowCircleUp',
  'ArrowCircleUpLeft',
  'ArrowCircleUpRight',
  'ArrowClockwise',
  'ArrowDown',
  'ArrowDownLeft',
  'ArrowDownRight',
  'ArrowElbowDownLeft',
  'ArrowElbowDownRight',
  'ArrowElbowLeft',
  'ArrowElbowLeftDown',
  'ArrowElbowLeftUp',
  'ArrowElbowRight',
  'ArrowElbowRightDown',
  'ArrowElbowRightUp',
  'ArrowElbowUpLeft',
  'ArrowElbowUpRight',
  'ArrowFatDown',
  'ArrowFatLeft',
  'ArrowFatLineDown',
  'ArrowFatLineLeft',
  'ArrowFatLineRight',
  'ArrowFatLineUp',
  'ArrowFatLinesDown',
  'ArrowFatLinesLeft',
  'ArrowFatLinesRight',
  'ArrowFatLinesUp',
  'ArrowFatRight',
  'ArrowFatUp',
  'ArrowLeft',
  'ArrowLineDown',
  'ArrowLineDownLeft',
  'ArrowLineDownRight',
  'ArrowLineLeft',
  'ArrowLineRight',
  'ArrowLineUp',
  'ArrowLineUpLeft',
  'ArrowLineUpRight',
  'ArrowRight',
  'ArrowSquareDown',
  'ArrowSquareDownLeft',
  'ArrowSquareDownRight',
  'ArrowSquareIn',
  'ArrowSquareLeft',
  'ArrowSquareOut',
  'ArrowSquareRight',
  'ArrowSquareUp',
  'ArrowSquareUpLeft',
  'ArrowSquareUpRight',
  'ArrowUDownLeft',
  'ArrowUDownRight',
  'ArrowULeftDown',
  'ArrowULeftUp',
  'ArrowURightDown',
  'ArrowURightUp',
  'ArrowUUpLeft',
  'ArrowUUpRight',
  'ArrowUp',
  'ArrowUpLeft',
  'ArrowUpRight',
  'ArrowsClockwise',
  'ArrowsDownUp',
  'ArrowsHorizontal',
  'ArrowsIn',
  'ArrowsInCardinal',
  'ArrowsInLineVertical',
  'ArrowsInSimple',
  'ArrowsLeftRight',
  'ArrowsOut',
  'ArrowsOutCardinal',
  'ArrowsOutSimple',
  'ArrowsVertical',
  'Article',
  'ArticleMedium',
  'ArticleNyTimes',
  'Asterisk',
  'AsteriskSimple',
  'At',
  'Atom',
  'Baby',
  'Backpack',
  'Backspace',
  'Bag',
  'BagSimple',
  'Balloon',
  'Bandaids',
  'Bank',
  'Barbell',
  'Barcode',
  'Barricade',
  'Baseball',
  'Basketball',
  'Bathtub',
  'BatteryCharging',
  'BatteryEmpty',
  'BatteryFull',
  'BatteryHigh',
  'BatteryLow',
  'BatteryMedium',
  'BatteryPlus',
  'BatteryWarning',
  'Bed',
  'BeerBottle',
  'BehanceLogo',
  'Bell',
  'BellRinging',
  'BellSimple',
  'BellSimpleRinging',
  'BellSimpleSlash',
  'BellSimpleZ',
  'BellSlash',
  'BellZ',
  'BezierCurve',
  'Bicycle',
  'Binoculars',
  'Bird',
  'Bluetooth',
  'BluetoothConnected',
  'BluetoothSlash',
  'BluetoothX',
  'Boat',
  'Book',
  'BookBookmark',
  'BookOpen',
  'Bookmark',
  'BookmarkSimple',
  'Bookmarks',
  'BookmarksSimple',
  'Books',
  'BoundingBox',
  'BracketsAngle',
  'BracketsCurly',
  'BracketsRound',
  'BracketsSquare',
  'Brain',
  'Brandy',
  'Briefcase',
  'BriefcaseMetal',
  'Broadcast',
  'Browser',
  'Browsers',
  'Bug',
  'BugBeetle',
  'BugDroid',
  'Buildings',
  'Bus',
  'Butterfly',
  'Cactus',
  'Cake',
  'Calculator',
  'Calendar',
  'CalendarBlank',
  'CalendarCheck',
  'CalendarPlus',
  'CalendarX',
  'Camera',
  'CameraRotate',
  'CameraSlash',
  'Campfire',
  'Car',
  'CarSimple',
  'Cardholder',
  'Cards',
  'CaretCircleDoubleUp',
  'CaretCircleDown',
  'CaretCircleLeft',
  'CaretCircleRight',
  'CaretCircleUp',
  'CaretDoubleDown',
  'CaretDoubleLeft',
  'CaretDoubleRight',
  'CaretDoubleUp',
  'CaretDown',
  'CaretLeft',
  'CaretRight',
  'CaretUp',
  'Cat',
  'CellSignalFull',
  'CellSignalHigh',
  'CellSignalLow',
  'CellSignalMedium',
  'CellSignalNone',
  'CellSignalSlash',
  'CellSignalX',
  'Chalkboard',
  'ChalkboardSimple',
  'ChalkboardTeacher',
  'ChartBar',
  'ChartBarHorizontal',
  'ChartLine',
  'ChartLineUp',
  'ChartPie',
  'ChartPieSlice',
  'Chat',
  'ChatCentered',
  'ChatCenteredDots',
  'ChatCenteredText',
  'ChatCircle',
  'ChatCircleDots',
  'ChatCircleText',
  'ChatDots',
  'ChatTeardrop',
  'ChatTeardropDots',
  'ChatTeardropText',
  'ChatText',
  'Chats',
  'ChatsCircle',
  'ChatsTeardrop',
  'Check',
  'CheckCircle',
  'CheckSquare',
  'CheckSquareOffset',
  'Checks',
  'Circle',
  'CircleDashed',
  'CircleHalf',
  'CircleHalfTilt',
  'CircleNotch',
  'CircleWavy',
  'CircleWavyCheck',
  'CircleWavyQuestion',
  'CircleWavyWarning',
  'CirclesFour',
  'CirclesThree',
  'CirclesThreePlus',
  'Clipboard',
  'ClipboardText',
  'Clock',
  'ClockAfternoon',
  'ClockClockwise',
  'ClosedCaptioning',
  'Cloud',
  'CloudArrowDown',
  'CloudArrowUp',
  'CloudCheck',
  'CloudFog',
  'CloudLightning',
  'CloudMoon',
  'CloudRain',
  'CloudSlash',
  'CloudSnow',
  'CloudSun',
  'Club',
  'CoatHanger',
  'Code',
  'CodeSimple',
  'CodepenLogo',
  'CodesandboxLogo',
  'Coffee',
  'Coin',
  'CoinVertical',
  'Coins',
  'Columns',
  'Command',
  'Compass',
  'ComputerTower',
  'Confetti',
  'Cookie',
  'CookingPot',
  'Copy',
  'CopySimple',
  'Copyleft',
  'Copyright',
  'CornersIn',
  'CornersOut',
  'Cpu',
  'CreditCard',
  'Crop',
  'Crosshair',
  'CrosshairSimple',
  'Crown',
  'CrownSimple',
  'Cube',
  'CurrencyBtc',
  'CurrencyCircleDollar',
  'CurrencyCny',
  'CurrencyDollar',
  'CurrencyDollarSimple',
  'CurrencyEth',
  'CurrencyEur',
  'CurrencyGbp',
  'CurrencyInr',
  'CurrencyJpy',
  'CurrencyKrw',
  'CurrencyKzt',
  'CurrencyNgn',
  'CurrencyRub',
  'Cursor',
  'CursorText',
  'Cylinder',
  'Database',
  'Desktop',
  'DesktopTower',
  'Detective',
  'DeviceMobile',
  'DeviceMobileCamera',
  'DeviceMobileSpeaker',
  'DeviceTablet',
  'DeviceTabletCamera',
  'DeviceTabletSpeaker',
  'Diamond',
  'DiamondsFour',
  'DiceFive',
  'DiceFour',
  'DiceOne',
  'DiceSix',
  'DiceThree',
  'DiceTwo',
  'Disc',
  'DiscordLogo',
  'Divide',
  'Dog',
  'Door',
  'DotsNine',
  'DotsSix',
  'DotsSixVertical',
  'DotsThree',
  'DotsThreeCircle',
  'DotsThreeOutline',
  'DotsThreeVertical',
  'Download',
  'DownloadSimple',
  'DribbbleLogo',
  'Drop',
  'DropHalf',
  'DropHalfBottom',
  'Ear',
  'EarSlash',
  'Egg',
  'EggCrack',
  'Eject',
  'EjectSimple',
  'Envelope',
  'EnvelopeOpen',
  'EnvelopeSimple',
  'EnvelopeSimpleOpen',
  'Equalizer',
  'Equals',
  'Eraser',
  'Exam',
  'Export',
  'Eye',
  'EyeClosed',
  'EyeSlash',
  'Eyedropper',
  'EyedropperSample',
  'Eyeglasses',
  'FaceMask',
  'FacebookLogo',
  'Factory',
  'Faders',
  'FadersHorizontal',
  'FastForward',
  'FastForwardCircle',
  'FigmaLogo',
  'File',
  'FileArrowDown',
  'FileArrowUp',
  'FileAudio',
  'FileCloud',
  'FileCode',
  'FileCss',
  'FileCsv',
  'FileDoc',
  'FileDotted',
  'FileHtml',
  'FileImage',
  'FileJpg',
  'FileJs',
  'FileJsx',
  'FileLock',
  'FileMinus',
  'FilePdf',
  'FilePlus',
  'FilePng',
  'FilePpt',
  'FileRs',
  'FileSearch',
  'FileText',
  'FileTs',
  'FileTsx',
  'FileVideo',
  'FileVue',
  'FileX',
  'FileXls',
  'FileZip',
  'Files',
  'FilmScript',
  'FilmSlate',
  'FilmStrip',
  'Fingerprint',
  'FingerprintSimple',
  'FinnTheHuman',
  'Fire',
  'FireSimple',
  'FirstAid',
  'FirstAidKit',
  'Fish',
  'FishSimple',
  'Flag',
  'FlagBanner',
  'FlagCheckered',
  'Flame',
  'Flashlight',
  'Flask',
  'FloppyDisk',
  'FloppyDiskBack',
  'FlowArrow',
  'Flower',
  'FlowerLotus',
  'FlyingSaucer',
  'Folder',
  'FolderDotted',
  'FolderLock',
  'FolderMinus',
  'FolderNotch',
  'FolderNotchMinus',
  'FolderNotchOpen',
  'FolderNotchPlus',
  'FolderOpen',
  'FolderPlus',
  'FolderSimple',
  'FolderSimpleDotted',
  'FolderSimpleLock',
  'FolderSimpleMinus',
  'FolderSimplePlus',
  'FolderSimpleStar',
  'FolderSimpleUser',
  'FolderStar',
  'FolderUser',
  'Folders',
  'Football',
  'ForkKnife',
  'FrameCorners',
  'FramerLogo',
  'Function',
  'Funnel',
  'FunnelSimple',
  'GameController',
  'GasPump',
  'Gauge',
  'Gear',
  'GearSix',
  'GenderFemale',
  'GenderIntersex',
  'GenderMale',
  'GenderNeuter',
  'GenderNonbinary',
  'GenderTransgender',
  'Ghost',
  'Gif',
  'Gift',
  'GitBranch',
  'GitCommit',
  'GitDiff',
  'GitFork',
  'GitMerge',
  'GitPullRequest',
  'GithubLogo',
  'GitlabLogo',
  'GitlabLogoSimple',
  'Globe',
  'GlobeHemisphereEast',
  'GlobeHemisphereWest',
  'GlobeSimple',
  'GlobeStand',
  'GoogleChromeLogo',
  'GoogleLogo',
  'GooglePhotosLogo',
  'GooglePlayLogo',
  'GooglePodcastsLogo',
  'Gradient',
  'GraduationCap',
  'Graph',
  'GridFour',
  'Hamburger',
  'Hand',
  'HandEye',
  'HandFist',
  'HandGrabbing',
  'HandPalm',
  'HandPointing',
  'HandSoap',
  'HandWaving',
  'Handbag',
  'HandbagSimple',
  'HandsClapping',
  'Handshake',
  'HardDrive',
  'HardDrives',
  'Hash',
  'HashStraight',
  'Headlights',
  'Headphones',
  'Headset',
  'Heart',
  'HeartBreak',
  'HeartStraight',
  'HeartStraightBreak',
  'Heartbeat',
  'Hexagon',
  'HighlighterCircle',
  'Horse',
  'Hourglass',
  'HourglassHigh',
  'HourglassLow',
  'HourglassMedium',
  'HourglassSimple',
  'HourglassSimpleHigh',
  'HourglassSimpleLow',
  'House',
  'HouseLine',
  'HouseSimple',
  'IdentificationBadge',
  'IdentificationCard',
  'Image',
  'ImageSquare',
  'Infinity',
  'Info',
  'InstagramLogo',
  'Intersect',
  'Jeep',
  'Kanban',
  'Key',
  'KeyReturn',
  'Keyboard',
  'Keyhole',
  'Knife',
  'Ladder',
  'LadderSimple',
  'Lamp',
  'Laptop',
  'Layout',
  'Leaf',
  'Lifebuoy',
  'Lightbulb',
  'LightbulbFilament',
  'Lightning',
  'LightningSlash',
  'LineSegment',
  'LineSegments',
  'Link',
  'LinkBreak',
  'LinkSimple',
  'LinkSimpleBreak',
  'LinkSimpleHorizontal',
  'LinkedinLogo',
  'LinuxLogo',
  'List',
  'ListBullets',
  'ListChecks',
  'ListDashes',
  'ListNumbers',
  'ListPlus',
  'Lock',
  'LockKey',
  'LockKeyOpen',
  'LockLaminated',
  'LockLaminatedOpen',
  'LockOpen',
  'LockSimple',
  'LockSimpleOpen',
  'MagicWand',
  'Magnet',
  'MagnetStraight',
  'MagnifyingGlass',
  'MagnifyingGlassMinus',
  'MagnifyingGlassPlus',
  'MapPin',
  'MapPinLine',
  'MapTrifold',
  'MarkerCircle',
  'Martini',
  'MaskHappy',
  'MaskSad',
  'MathOperations',
  'Medal',
  'MediumLogo',
  'Megaphone',
  'MegaphoneSimple',
  'MessengerLogo',
  'Microphone',
  'MicrophoneSlash',
  'MicrophoneStage',
  'MicrosoftExcelLogo',
  'MicrosoftTeamsLogo',
  'MicrosoftWordLogo',
  'Minus',
  'MinusCircle',
  'Money',
  'Monitor',
  'MonitorPlay',
  'Moon',
  'MoonStars',
  'Mountains',
  'Mouse',
  'MouseSimple',
  'MusicNote',
  'MusicNoteSimple',
  'MusicNotes',
  'MusicNotesPlus',
  'MusicNotesSimple',
  'NavigationArrow',
  'Needle',
  'Newspaper',
  'NewspaperClipping',
  'Note',
  'NoteBlank',
  'NotePencil',
  'Notebook',
  'Notepad',
  'Notification',
  'NumberCircleEight',
  'NumberCircleFive',
  'NumberCircleFour',
  'NumberCircleNine',
  'NumberCircleOne',
  'NumberCircleSeven',
  'NumberCircleSix',
  'NumberCircleThree',
  'NumberCircleTwo',
  'NumberCircleZero',
  'NumberEight',
  'NumberFive',
  'NumberFour',
  'NumberNine',
  'NumberOne',
  'NumberSeven',
  'NumberSix',
  'NumberSquareEight',
  'NumberSquareFive',
  'NumberSquareFour',
  'NumberSquareNine',
  'NumberSquareOne',
  'NumberSquareSeven',
  'NumberSquareSix',
  'NumberSquareThree',
  'NumberSquareTwo',
  'NumberSquareZero',
  'NumberThree',
  'NumberTwo',
  'NumberZero',
  'Nut',
  'NyTimesLogo',
  'Octagon',
  'Option',
  'Package',
  'PaintBrush',
  'PaintBrushBroad',
  'PaintBrushHousehold',
  'PaintBucket',
  'PaintRoller',
  'Palette',
  'PaperPlane',
  'PaperPlaneRight',
  'PaperPlaneTilt',
  'Paperclip',
  'PaperclipHorizontal',
  'Parachute',
  'Password',
  'Path',
  'Pause',
  'PauseCircle',
  'PawPrint',
  'Peace',
  'Pen',
  'PenNib',
  'PenNibStraight',
  'Pencil',
  'PencilCircle',
  'PencilLine',
  'PencilSimple',
  'PencilSimpleLine',
  'Percent',
  'Person',
  'PersonSimple',
  'PersonSimpleRun',
  'PersonSimpleWalk',
  'Perspective',
  'Phone',
  'PhoneCall',
  'PhoneDisconnect',
  'PhoneIncoming',
  'PhoneOutgoing',
  'PhoneSlash',
  'PhoneX',
  'PhosphorLogo',
  'PianoKeys',
  'PictureInPicture',
  'Pill',
  'PinterestLogo',
  'Pinwheel',
  'Pizza',
  'Placeholder',
  'Planet',
  'Play',
  'PlayCircle',
  'Playlist',
  'Plug',
  'Plugs',
  'PlugsConnected',
  'Plus',
  'PlusCircle',
  'PlusMinus',
  'PokerChip',
  'PoliceCar',
  'Polygon',
  'Popcorn',
  'Power',
  'Prescription',
  'Presentation',
  'PresentationChart',
  'Printer',
  'Prohibit',
  'ProhibitInset',
  'ProjectorScreen',
  'ProjectorScreenChart',
  'PushPin',
  'PushPinSimple',
  'PushPinSimpleSlash',
  'PushPinSlash',
  'PuzzlePiece',
  'QrCode',
  'Question',
  'Queue',
  'Quotes',
  'Radical',
  'Radio',
  'RadioButton',
  'Rainbow',
  'RainbowCloud',
  'Receipt',
  'Record',
  'Rectangle',
  'Recycle',
  'RedditLogo',
  'Repeat',
  'RepeatOnce',
  'Rewind',
  'RewindCircle',
  'Robot',
  'Rocket',
  'RocketLaunch',
  'Rows',
  'Rss',
  'RssSimple',
  'Rug',
  'Ruler',
  'Scales',
  'Scan',
  'Scissors',
  'Screencast',
  'ScribbleLoop',
  'Scroll',
  'Selection',
  'SelectionAll',
  'SelectionBackground',
  'SelectionForeground',
  'SelectionInverse',
  'SelectionPlus',
  'SelectionSlash',
  'Share',
  'ShareNetwork',
  'Shield',
  'ShieldCheck',
  'ShieldCheckered',
  'ShieldChevron',
  'ShieldPlus',
  'ShieldSlash',
  'ShieldStar',
  'ShieldWarning',
  'ShoppingBag',
  'ShoppingBagOpen',
  'ShoppingCart',
  'ShoppingCartSimple',
  'Shower',
  'Shuffle',
  'ShuffleAngular',
  'ShuffleSimple',
  'Sidebar',
  'SidebarSimple',
  'SignIn',
  'SignOut',
  'Signpost',
  'SimCard',
  'SketchLogo',
  'SkipBack',
  'SkipBackCircle',
  'SkipForward',
  'SkipForwardCircle',
  'Skull',
  'SlackLogo',
  'Sliders',
  'SlidersHorizontal',
  'Smiley',
  'SmileyBlank',
  'SmileyMeh',
  'SmileyNervous',
  'SmileySad',
  'SmileySticker',
  'SmileyWink',
  'SmileyXEyes',
  'SnapchatLogo',
  'Snowflake',
  'SoccerBall',
  'SortAscending',
  'SortDescending',
  'Spade',
  'Sparkle',
  'SpeakerHigh',
  'SpeakerLow',
  'SpeakerNone',
  'SpeakerSimpleHigh',
  'SpeakerSimpleLow',
  'SpeakerSimpleNone',
  'SpeakerSimpleSlash',
  'SpeakerSimpleX',
  'SpeakerSlash',
  'SpeakerX',
  'Spinner',
  'SpinnerGap',
  'Spiral',
  'SpotifyLogo',
  'Square',
  'SquareHalf',
  'SquareHalfBottom',
  'SquareLogo',
  'SquaresFour',
  'Stack',
  'StackOverflowLogo',
  'StackSimple',
  'Stamp',
  'Star',
  'StarFour',
  'StarHalf',
  'Sticker',
  'Stop',
  'StopCircle',
  'Storefront',
  'Strategy',
  'StripeLogo',
  'Student',
  'Suitcase',
  'SuitcaseSimple',
  'Sun',
  'SunDim',
  'SunHorizon',
  'Sunglasses',
  'Swap',
  'Swatches',
  'Sword',
  'Syringe',
  'TShirt',
  'Table',
  'Tabs',
  'Tag',
  'TagChevron',
  'TagSimple',
  'Target',
  'Taxi',
  'TelegramLogo',
  'Television',
  'TelevisionSimple',
  'TennisBall',
  'Terminal',
  'TerminalWindow',
  'TestTube',
  'TextAa',
  'TextAlignCenter',
  'TextAlignJustify',
  'TextAlignLeft',
  'TextAlignRight',
  'TextBolder',
  'TextH',
  'TextHFive',
  'TextHFour',
  'TextHOne',
  'TextHSix',
  'TextHThree',
  'TextHTwo',
  'TextIndent',
  'TextItalic',
  'TextOutdent',
  'TextStrikethrough',
  'TextT',
  'TextUnderline',
  'Textbox',
  'Thermometer',
  'ThermometerCold',
  'ThermometerHot',
  'ThermometerSimple',
  'ThumbsDown',
  'ThumbsUp',
  'Ticket',
  'TiktokLogo',
  'Timer',
  'ToggleLeft',
  'ToggleRight',
  'Toilet',
  'ToiletPaper',
  'Tote',
  'ToteSimple',
  'TrademarkRegistered',
  'TrafficCone',
  'TrafficSign',
  'TrafficSignal',
  'Train',
  'TrainRegional',
  'TrainSimple',
  'Translate',
  'Trash',
  'TrashSimple',
  'Tray',
  'Tree',
  'TreeEvergreen',
  'TreeStructure',
  'TrendDown',
  'TrendUp',
  'Triangle',
  'Trophy',
  'Truck',
  'TwitchLogo',
  'TwitterLogo',
  'Umbrella',
  'UmbrellaSimple',
  'Upload',
  'UploadSimple',
  'User',
  'UserCircle',
  'UserCircleGear',
  'UserCircleMinus',
  'UserCirclePlus',
  'UserFocus',
  'UserGear',
  'UserList',
  'UserMinus',
  'UserPlus',
  'UserRectangle',
  'UserSquare',
  'UserSwitch',
  'Users',
  'UsersFour',
  'UsersThree',
  'Vault',
  'Vibrate',
  'VideoCamera',
  'VideoCameraSlash',
  'Vignette',
  'Voicemail',
  'Volleyball',
  'Wall',
  'Wallet',
  'Warning',
  'WarningCircle',
  'WarningOctagon',
  'Watch',
  'WaveSawtooth',
  'WaveSine',
  'WaveSquare',
  'WaveTriangle',
  'Waves',
  'Webcam',
  'WhatsappLogo',
  'Wheelchair',
  'WifiHigh',
  'WifiLow',
  'WifiMedium',
  'WifiNone',
  'WifiSlash',
  'WifiX',
  'Wind',
  'WindowsLogo',
  'Wine',
  'Wrench',
  'X',
  'XCircle',
  'XSquare',
  'YinYang',
  'YoutubeLogo',
];
var moduleBaseUrl = 'https://framer.com/m/phosphor-icons/';
var weightOptions = ['thin', 'light', 'regular', 'bold', 'fill', 'duotone',];
var lowercaseIconKeyPairs = iconKeys.reduce((res, key,) => {
  res[key.toLowerCase()] = key;
  return res;
}, {},);
function Icon(props,) {
  const { color, selectByList, iconSearch, iconSelection, onClick, onMouseDown, onMouseUp, onMouseEnter, onMouseLeave, weight, mirrored, } =
    props;
  const isMounted = useRef(false,);
  const iconKey = useIconSelection(iconKeys, selectByList, iconSearch, iconSelection, lowercaseIconKeyPairs,);
  const [SelectedIcon, setSelectedIcon,] = useState(iconKey === 'Home' ? House_default(React,) : null,);
  async function importModule() {
    try {
      const version = '0.0.50';
      const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`;
      const module = await import(
        /* webpackIgnore: true */
        iconModuleUrl
      );
      if (isMounted.current) {
        setSelectedIcon(module.default(React,),);
      }
    } catch (err) {
      if (isMounted.current) {
        setSelectedIcon(null,);
      }
    }
  }
  useEffect(() => {
    isMounted.current = true;
    importModule();
    return () => {
      isMounted.current = false;
    };
  }, [iconKey,],);
  const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
  const emptyState = isOnCanvas ? /* @__PURE__ */ _jsx(NullState, {},) : null;
  return /* @__PURE__ */ _jsx(motion.div, {
    style: { display: 'contents', },
    onClick,
    onMouseEnter,
    onMouseLeave,
    onMouseDown,
    onMouseUp,
    children: SelectedIcon
      ? /* @__PURE__ */ _jsx('svg', {
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 256 256',
        style: {
          userSelect: 'none',
          width: '100%',
          height: '100%',
          display: 'inline-block',
          fill: color,
          flexShrink: 0,
          transform: mirrored ? 'scale(-1, 1)' : void 0,
        },
        focusable: 'false',
        color,
        children: /* @__PURE__ */ _jsx(SelectedIcon, { color, weight, },),
      },)
      : emptyState,
  },);
}
Icon.displayName = 'Phosphor';
Icon.defaultProps = {
  width: 24,
  height: 24,
  iconSelection: 'House',
  iconSearch: 'House',
  color: '#66F',
  selectByList: true,
  weight: 'regular',
  mirrored: false,
};
addPropertyControls(Icon, {
  selectByList: {
    type: ControlType.Boolean,
    title: 'Select',
    enabledTitle: 'List',
    disabledTitle: 'Search',
    defaultValue: Icon.defaultProps.selectByList,
  },
  iconSelection: {
    type: ControlType.Enum,
    options: iconKeys,
    defaultValue: Icon.defaultProps.iconSelection,
    title: 'Name',
    hidden: ({ selectByList, },) => !selectByList,
    description: 'Find every icon name on the [Phosphor site](https://phosphoricons.com/)',
  },
  iconSearch: {
    type: ControlType.String,
    title: 'Name',
    placeholder: 'Menu, Wifi, Box\u2026',
    hidden: ({ selectByList, },) => selectByList,
  },
  color: { type: ControlType.Color, title: 'Color', defaultValue: Icon.defaultProps.color, },
  weight: {
    type: ControlType.Enum,
    title: 'Weight',
    optionTitles: weightOptions.map((piece,) => piece.charAt(0,).toUpperCase() + piece.slice(1,)),
    options: weightOptions,
    defaultValue: Icon.defaultProps.weight,
  },
  mirrored: { type: ControlType.Boolean, enabledTitle: 'Yes', disabledTitle: 'No', defaultValue: Icon.defaultProps.mirrored, },
  ...defaultEvents,
},);

// https:https://framerusercontent.com/modules/YPPQaawwYaqGsNWuaEiH/SqAKJIFKTXoDzFa1Z6rs/q64yDrOL3.js
var PhosphorFonts = getFonts(Icon,);
var MotionDivWithFX = withFX(motion2.div,);
var RichTextWithFX = withFX(RichText,);
var cycleOrder = ['QJ6X5OV2Q', 'jNQqNcpjl',];
var serializationHash = 'framer-KYYCr';
var variantClassNames = { jNQqNcpjl: 'framer-v-tez7sd', QJ6X5OV2Q: 'framer-v-1b5ydyb', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var animation = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, x: 0, y: 20, };
var transition2 = { damping: 40, delay: 0, mass: 1, stiffness: 400, type: 'spring', };
var animation1 = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, transition: transition2, x: 0, y: 20, };
var transformTemplate1 = (_, t,) => `perspective(1200px) ${t}`;
var transition3 = { damping: 40, delay: 0.2, mass: 1, stiffness: 400, type: 'spring', };
var animation2 = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, transition: transition3, x: 0, y: 20, };
var transition4 = { damping: 40, delay: 0.3, mass: 1, stiffness: 400, type: 'spring', };
var animation3 = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, transition: transition4, x: 0, y: 20, };
var Transition = ({ value, children, },) => {
  const config = React2.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React2.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx2(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion2(React2.Fragment,);
var humanReadableVariantMap = { Desktop: 'QJ6X5OV2Q', Tablet: 'jNQqNcpjl', };
var getProps = ({ height, id, width, ...props },) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref !== void 0
        ? _ref
        : 'QJ6X5OV2Q',
  };
};
var createLayoutDependency = (props, variants,) => variants.join('-',) + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props,);
  const { baseVariant, classNames, gestureVariant, setGestureState, setVariant, variants, } = useVariantState({
    cycleOrder,
    defaultVariant: 'QJ6X5OV2Q',
    variant,
    variantClassNames,
  },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React2.useRef(null,);
  const defaultLayoutId = React2.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx2(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx2(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx2(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsxs(motion2.div, {
          ...restProps,
          className: cx(serializationHash, ...sharedStyleClassNames, 'framer-1b5ydyb', className, classNames,),
          'data-framer-name': 'Desktop',
          layoutDependency,
          layoutId: 'QJ6X5OV2Q',
          onHoverEnd: () => setGestureState({ isHovered: false, },),
          onHoverStart: () => setGestureState({ isHovered: true, },),
          onTap: () => setGestureState({ isPressed: false, },),
          onTapCancel: () => setGestureState({ isPressed: false, },),
          onTapStart: () => setGestureState({ isPressed: true, },),
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { backgroundColor: 'rgb(255, 255, 255)', ...style, },
          ...addPropertyOverrides({ jNQqNcpjl: { 'data-framer-name': 'Tablet', }, }, baseVariant, gestureVariant,),
          children: [
            /* @__PURE__ */ _jsxs(motion2.div, {
              className: 'framer-1wzq7ls',
              'data-framer-name': 'Header',
              layoutDependency,
              layoutId: 'OpQ9kJexP',
              children: [
                /* @__PURE__ */ _jsxs(MotionDivWithFX, {
                  __framer__animate: { transition: transition2, },
                  __framer__animateOnce: true,
                  __framer__enter: animation,
                  __framer__exit: animation1,
                  __framer__styleAppearEffectEnabled: true,
                  __framer__threshold: 0.5,
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 1,
                  className: 'framer-13c6u4s',
                  layoutDependency,
                  layoutId: 'j6rISou1p',
                  transformTemplate: transformTemplate1,
                  children: [
                    /* @__PURE__ */ _jsx2(Image, {
                      background: { alt: '', fit: 'fill', intrinsicHeight: 120, intrinsicWidth: 120, },
                      className: 'framer-emhnvy',
                      layoutDependency,
                      layoutId: 'sI_hMLheh',
                      style: {
                        borderBottomLeftRadius: 41,
                        borderBottomRightRadius: 41,
                        borderTopLeftRadius: 41,
                        borderTopRightRadius: 41,
                      },
                    },),
                    /* @__PURE__ */ _jsx2(motion2.div, {
                      className: 'framer-6eneq3',
                      'data-framer-name': 'Twitter',
                      layoutDependency,
                      layoutId: 'ODS9Kq_Yt',
                      children: /* @__PURE__ */ _jsx2(motion2.div, {
                        className: 'framer-5mjn9m',
                        'data-framer-name': 'Button Icon',
                        layoutDependency,
                        layoutId: 'p3n1GYo2e',
                        style: {
                          backgroundColor: 'var(--token-40c03004-286a-43c1-b36f-58b60663152c, rgb(242, 242, 242))',
                          borderBottomLeftRadius: '50%',
                          borderBottomRightRadius: '50%',
                          borderTopLeftRadius: '50%',
                          borderTopRightRadius: '50%',
                        },
                        children: /* @__PURE__ */ _jsx2(ComponentViewportProvider, {
                          children: /* @__PURE__ */ _jsx2(motion2.div, {
                            className: 'framer-yuqshr-container',
                            layoutDependency,
                            layoutId: 'ZEz3L23bN-container',
                            children: /* @__PURE__ */ _jsx2(Icon, {
                              color: 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                              height: '100%',
                              iconSearch: 'House',
                              iconSelection: 'TwitterLogo',
                              id: 'ZEz3L23bN',
                              layoutId: 'ZEz3L23bN',
                              mirrored: false,
                              selectByList: true,
                              style: { height: '100%', width: '100%', },
                              weight: 'fill',
                              width: '100%',
                            },),
                          },),
                        },),
                      },),
                    },),
                  ],
                },),
                /* @__PURE__ */ _jsx2(RichTextWithFX, {
                  __framer__animate: { transition: transition3, },
                  __framer__animateOnce: true,
                  __framer__enter: animation,
                  __framer__exit: animation2,
                  __framer__styleAppearEffectEnabled: true,
                  __framer__threshold: 0.5,
                  __fromCanvasComponent: true,
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 1,
                  children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                    children: /* @__PURE__ */ _jsxs(motion2.h3, {
                      style: {
                        '--font-selector': 'R0Y7SW50ZXItNjAw',
                        '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                        '--framer-font-size': '20px',
                        '--framer-font-weight': '600',
                        '--framer-letter-spacing': '-0.5px',
                        '--framer-line-height': '1.4em',
                        '--framer-text-alignment': 'left',
                        '--framer-text-color': 'var(--extracted-a0htzi, var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34)))',
                      },
                      children: [
                        'I\'m Dana Parker, a designer at ',
                        /* @__PURE__ */ _jsx2(Link, {
                          href: 'https://www.framer.com/',
                          openInNewTab: true,
                          smoothScroll: false,
                          children: /* @__PURE__ */ _jsx2(motion2.a, { children: 'Framer', },),
                        },),
                        '. I am focusing on creating the best website building tool with my talented team. A high level of craft is very important to me and my work. some change',
                      ],
                    },),
                  },),
                  className: 'framer-6vwca4',
                  fonts: ['GF;Inter-600',],
                  layoutDependency,
                  layoutId: 'MdIU0iV0K',
                  style: {
                    '--extracted-a0htzi': 'var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34))',
                    '--framer-link-hover-text-color': 'var(--token-fcce9699-25b1-4529-9491-d24458dec076, rgb(103, 102, 255))',
                    '--framer-link-text-color': 'rgba(48, 48, 64, 0.7)',
                    '--framer-link-text-decoration': 'none',
                    '--framer-paragraph-spacing': '0px',
                  },
                  transformTemplate: transformTemplate1,
                  verticalAlignment: 'top',
                  withExternalLayout: true,
                },),
              ],
            },),
            /* @__PURE__ */ _jsxs(MotionDivWithFX, {
              __framer__animate: { transition: transition4, },
              __framer__animateOnce: true,
              __framer__enter: animation,
              __framer__exit: animation3,
              __framer__styleAppearEffectEnabled: true,
              __framer__threshold: 0.5,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              className: 'framer-18oyuoj',
              'data-border': true,
              'data-framer-name': 'Entries',
              layoutDependency,
              layoutId: 'Al128SHMh',
              style: {
                '--border-bottom-width': '0px',
                '--border-color': 'rgba(34, 34, 34, 0.05)',
                '--border-left-width': '0px',
                '--border-right-width': '0px',
                '--border-style': 'solid',
                '--border-top-width': '1px',
              },
              transformTemplate: transformTemplate1,
              children: [
                /* @__PURE__ */ _jsxs(motion2.div, {
                  className: 'framer-1of4spd',
                  'data-framer-name': 'Bookmarks',
                  layoutDependency,
                  layoutId: 'fR7JbRnxe',
                  style: { borderBottomLeftRadius: 28, borderBottomRightRadius: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28, },
                  children: [
                    /* @__PURE__ */ _jsx2(RichText, {
                      __fromCanvasComponent: true,
                      children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                        children: /* @__PURE__ */ _jsx2(motion2.p, {
                          style: {
                            '--font-selector': 'R0Y7SW50ZXItNTAw',
                            '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                            '--framer-font-size': '14px',
                            '--framer-font-weight': '500',
                            '--framer-letter-spacing': '0px',
                            '--framer-line-height': '1.5em',
                            '--framer-text-alignment': 'left',
                            '--framer-text-color':
                              'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                          },
                          children: 'Bookmarks',
                        },),
                      },),
                      className: 'framer-1kjuxs8',
                      fonts: ['GF;Inter-500',],
                      layoutDependency,
                      layoutId: 'S0Z6CNkWo',
                      style: {
                        '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                        '--framer-link-hover-text-color':
                          'var(--token-6e365f09-eb16-423f-93f7-5f3b4b83d578, rgb(255, 204, 34)) /* {"name":"Yellow"} */',
                        '--framer-link-text-color': 'rgba(48, 48, 64, 0.7)',
                        '--framer-link-text-decoration': 'none',
                        '--framer-paragraph-spacing': '0px',
                      },
                      verticalAlignment: 'top',
                      withExternalLayout: true,
                    },),
                    /* @__PURE__ */ _jsxs(motion2.div, {
                      className: 'framer-e223h2',
                      'data-framer-name': 'Bookmark',
                      layoutDependency,
                      layoutId: 'Bb4DRr77N',
                      children: [
                        /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-1xokyxn',
                          layoutDependency,
                          layoutId: 'Qwexip93p',
                          children: /* @__PURE__ */ _jsx2(Image, {
                            background: { alt: '', fit: 'fill', },
                            className: 'framer-10r2vr8',
                            layoutDependency,
                            layoutId: 'Pg37sPHL_',
                            style: {
                              borderBottomLeftRadius: 12,
                              borderBottomRightRadius: 12,
                              borderTopLeftRadius: 12,
                              borderTopRightRadius: 12,
                            },
                          },),
                        },),
                        /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-47n4du',
                          layoutDependency,
                          layoutId: 'C6uSsaOq2',
                          children: /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-1w2t1oi',
                            layoutDependency,
                            layoutId: 'bdCvztvz2',
                            children: [
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.h3, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNjAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '20px',
                                      '--framer-font-weight': '600',
                                      '--framer-letter-spacing': '-0.5px',
                                      '--framer-line-height': '1.4em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-a0htzi, var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34)))',
                                    },
                                    children: 'Moderat',
                                  },),
                                },),
                                className: 'framer-1faomiy',
                                fonts: ['GF;Inter-600',],
                                layoutDependency,
                                layoutId: 'kAHupbUCf',
                                style: {
                                  '--extracted-a0htzi': 'var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'A beautiful clean typeface with punch.',
                                  },),
                                },),
                                className: 'framer-h892kc',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'PntPawgjh',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                        },),
                      ],
                    },),
                    /* @__PURE__ */ _jsxs(motion2.div, {
                      className: 'framer-vyjk6',
                      'data-framer-name': 'Bookmark Copy',
                      layoutDependency,
                      layoutId: 'ZXyBL3UxK',
                      children: [
                        /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-1nnbol7',
                          layoutDependency,
                          layoutId: 'GbsCPfY0X',
                          children: /* @__PURE__ */ _jsx2(Image, {
                            background: { alt: '', fit: 'fill', },
                            className: 'framer-1pt1hk2',
                            layoutDependency,
                            layoutId: 'lHK_YQPyU',
                            style: {
                              borderBottomLeftRadius: 12,
                              borderBottomRightRadius: 12,
                              borderTopLeftRadius: 12,
                              borderTopRightRadius: 12,
                            },
                          },),
                        },),
                        /* @__PURE__ */ _jsx2(motion2.div, {
                          className: 'framer-gu1odh',
                          layoutDependency,
                          layoutId: 'diOrHb28Y',
                          children: /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-6jxmdw',
                            layoutDependency,
                            layoutId: 'A4L0BOGT4',
                            children: [
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.h3, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNjAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '20px',
                                      '--framer-font-weight': '600',
                                      '--framer-letter-spacing': '-0.5px',
                                      '--framer-line-height': '1.4em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-a0htzi, var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34)))',
                                    },
                                    children: 'Degular',
                                  },),
                                },),
                                className: 'framer-3pk42e',
                                fonts: ['GF;Inter-600',],
                                layoutDependency,
                                layoutId: 'KXEVl56fZ',
                                style: {
                                  '--extracted-a0htzi': 'var(--token-b9c3c957-2c66-49c4-9732-fa196fddac20, rgb(0, 17, 34))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'So much character in this one.',
                                  },),
                                },),
                                className: 'framer-1u1nwqz',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'TmPJB8smR',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                        },),
                      ],
                    },),
                  ],
                },),
                /* @__PURE__ */ _jsx2(motion2.div, {
                  className: 'framer-vadw1i',
                  'data-framer-name': 'Sidebar',
                  layoutDependency,
                  layoutId: 'VzEzxbLPF',
                  children: /* @__PURE__ */ _jsxs(motion2.div, {
                    className: 'framer-1ffgcrw',
                    'data-framer-name': 'Friends',
                    layoutDependency,
                    layoutId: 'Wl_VW_8EB',
                    style: { borderBottomLeftRadius: 28, borderBottomRightRadius: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28, },
                    children: [
                      /* @__PURE__ */ _jsx2(RichText, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                          children: /* @__PURE__ */ _jsx2(motion2.p, {
                            style: {
                              '--font-selector': 'R0Y7SW50ZXItNTAw',
                              '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                              '--framer-font-size': '14px',
                              '--framer-font-weight': '500',
                              '--framer-letter-spacing': '0px',
                              '--framer-line-height': '1.5em',
                              '--framer-text-alignment': 'left',
                              '--framer-text-color':
                                'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                            },
                            children: 'Friends',
                          },),
                        },),
                        className: 'framer-11pc94f',
                        fonts: ['GF;Inter-500',],
                        layoutDependency,
                        layoutId: 'LrLtNUkIh',
                        style: {
                          '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                          '--framer-link-hover-text-color':
                            'var(--token-6e365f09-eb16-423f-93f7-5f3b4b83d578, rgb(255, 204, 34)) /* {"name":"Yellow"} */',
                          '--framer-link-text-color': 'rgba(48, 48, 64, 0.7)',
                          '--framer-link-text-decoration': 'none',
                          '--framer-paragraph-spacing': '0px',
                        },
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                      /* @__PURE__ */ _jsxs(motion2.div, {
                        className: 'framer-1j9mdi3',
                        layoutDependency,
                        layoutId: 'FZhY17jix',
                        children: [
                          /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-1c8di1n',
                            'data-framer-name': 'Friend',
                            layoutDependency,
                            layoutId: 'Od496hw91',
                            children: [
                              /* @__PURE__ */ _jsx2(Image, {
                                background: { alt: '', fit: 'fill', intrinsicHeight: 400, intrinsicWidth: 400, },
                                className: 'framer-tgjfdb',
                                layoutDependency,
                                layoutId: 'K43T__ES_',
                                style: {
                                  borderBottomLeftRadius: 20,
                                  borderBottomRightRadius: 20,
                                  borderTopLeftRadius: 20,
                                  borderTopRightRadius: 20,
                                },
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'Hunter Caron',
                                  },),
                                },),
                                className: 'framer-12jh62',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'mRzwaZ_OX',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                          /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-kl86d3',
                            'data-framer-name': 'Friend',
                            layoutDependency,
                            layoutId: 'g2haIhUiP',
                            children: [
                              /* @__PURE__ */ _jsx2(Image, {
                                background: { alt: '', fit: 'fill', intrinsicHeight: 400, intrinsicWidth: 400, },
                                className: 'framer-1peibnf',
                                layoutDependency,
                                layoutId: 'bsxC0V4HF',
                                style: {
                                  borderBottomLeftRadius: 20,
                                  borderBottomRightRadius: 20,
                                  borderTopLeftRadius: 20,
                                  borderTopRightRadius: 20,
                                },
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'Benjamin den Boer',
                                  },),
                                },),
                                className: 'framer-15j97pm',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'UZjrKwJdX',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                          /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-13oeh66',
                            'data-framer-name': 'Friend',
                            layoutDependency,
                            layoutId: 'c_MNpcuvQ',
                            children: [
                              /* @__PURE__ */ _jsx2(Image, {
                                background: { alt: '', fit: 'fill', intrinsicHeight: 400, intrinsicWidth: 400, },
                                className: 'framer-17a6c1i',
                                layoutDependency,
                                layoutId: 'fNmbk0fF8',
                                style: {
                                  borderBottomLeftRadius: 20,
                                  borderBottomRightRadius: 20,
                                  borderTopLeftRadius: 20,
                                  borderTopRightRadius: 20,
                                },
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'Edoardo Mercati',
                                  },),
                                },),
                                className: 'framer-11i4e7y',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'gGrNCSfe4',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                          /* @__PURE__ */ _jsxs(motion2.div, {
                            className: 'framer-feaqek',
                            'data-framer-name': 'Friend',
                            layoutDependency,
                            layoutId: 'ChX4_mOC8',
                            children: [
                              /* @__PURE__ */ _jsx2(Image, {
                                background: { alt: '', fit: 'fill', intrinsicHeight: 400, intrinsicWidth: 400, },
                                className: 'framer-1saurrb',
                                layoutDependency,
                                layoutId: 'TqtI5Kmc9',
                                style: {
                                  borderBottomLeftRadius: 20,
                                  borderBottomRightRadius: 20,
                                  borderTopLeftRadius: 20,
                                  borderTopRightRadius: 20,
                                },
                              },),
                              /* @__PURE__ */ _jsx2(RichText, {
                                __fromCanvasComponent: true,
                                children: /* @__PURE__ */ _jsx2(React2.Fragment, {
                                  children: /* @__PURE__ */ _jsx2(motion2.p, {
                                    style: {
                                      '--font-selector': 'R0Y7SW50ZXItNTAw',
                                      '--framer-font-family': '"Inter", "Inter Placeholder", sans-serif',
                                      '--framer-font-size': '14px',
                                      '--framer-font-weight': '500',
                                      '--framer-letter-spacing': '0px',
                                      '--framer-line-height': '1.5em',
                                      '--framer-text-alignment': 'left',
                                      '--framer-text-color':
                                        'var(--extracted-r6o4lv, var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102)))',
                                    },
                                    children: 'Anne Lee',
                                  },),
                                },),
                                className: 'framer-ate8gg',
                                fonts: ['GF;Inter-500',],
                                layoutDependency,
                                layoutId: 'H7J8l7wNT',
                                style: {
                                  '--extracted-r6o4lv': 'var(--token-fb4b67b5-91ba-4b73-b4a6-f55417ea1c0c, rgb(102, 102, 102))',
                                  '--framer-link-text-color': 'rgb(0, 153, 255)',
                                  '--framer-link-text-decoration': 'underline',
                                  '--framer-paragraph-spacing': '0px',
                                },
                                verticalAlignment: 'top',
                                withExternalLayout: true,
                              },),
                            ],
                          },),
                        ],
                      },),
                    ],
                  },),
                },),
              ],
            },),
          ],
        },),
      },),
    },),
  },);
},);
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-KYYCr.framer-q8o9fw, .framer-KYYCr .framer-q8o9fw { display: block; }',
  '.framer-KYYCr.framer-1b5ydyb { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 1200px; }',
  '.framer-KYYCr .framer-1wzq7ls { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: flex-start; max-width: 100%; overflow: visible; padding: 50px 50px 50px 50px; position: relative; width: 1200px; }',
  '.framer-KYYCr .framer-13c6u4s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-emhnvy { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 48px); overflow: visible; position: relative; width: 48px; }',
  '.framer-KYYCr .framer-6eneq3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: min-content; }',
  '.framer-KYYCr .framer-5mjn9m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 48px; justify-content: center; overflow: visible; padding: 12px 12px 12px 12px; position: relative; width: 48px; }',
  '.framer-KYYCr .framer-yuqshr-container { flex: none; height: 24px; position: relative; width: 24px; }',
  '.framer-KYYCr .framer-6vwca4, .framer-KYYCr .framer-1kjuxs8, .framer-KYYCr .framer-1faomiy, .framer-KYYCr .framer-h892kc, .framer-KYYCr .framer-3pk42e, .framer-KYYCr .framer-1u1nwqz { flex: none; height: auto; overflow: hidden; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-KYYCr .framer-18oyuoj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; max-width: 100%; overflow: visible; padding: 50px 50px 50px 50px; position: relative; width: 1200px; }',
  '.framer-KYYCr .framer-1of4spd { align-content: flex-start; align-items: flex-start; display: flex; flex: 2 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }',
  '.framer-KYYCr .framer-e223h2, .framer-KYYCr .framer-vyjk6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-1xokyxn, .framer-KYYCr .framer-1nnbol7 { flex: none; height: 52px; overflow: visible; position: relative; width: 52px; }',
  '.framer-KYYCr .framer-10r2vr8, .framer-KYYCr .framer-1pt1hk2 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 52px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }',
  '.framer-KYYCr .framer-47n4du, .framer-KYYCr .framer-gu1odh { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }',
  '.framer-KYYCr .framer-1w2t1oi, .framer-KYYCr .framer-6jxmdw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-vadw1i { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }',
  '.framer-KYYCr .framer-1ffgcrw { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-11pc94f, .framer-KYYCr .framer-12jh62, .framer-KYYCr .framer-15j97pm, .framer-KYYCr .framer-11i4e7y, .framer-KYYCr .framer-ate8gg { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }',
  '.framer-KYYCr .framer-1j9mdi3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-1c8di1n, .framer-KYYCr .framer-kl86d3, .framer-KYYCr .framer-13oeh66, .framer-KYYCr .framer-feaqek { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 100%; }',
  '.framer-KYYCr .framer-tgjfdb, .framer-KYYCr .framer-1peibnf, .framer-KYYCr .framer-17a6c1i, .framer-KYYCr .framer-1saurrb { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: visible; position: relative; width: 32px; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KYYCr.framer-1b5ydyb, .framer-KYYCr .framer-1wzq7ls, .framer-KYYCr .framer-6eneq3, .framer-KYYCr .framer-5mjn9m, .framer-KYYCr .framer-18oyuoj, .framer-KYYCr .framer-1of4spd, .framer-KYYCr .framer-e223h2, .framer-KYYCr .framer-47n4du, .framer-KYYCr .framer-1w2t1oi, .framer-KYYCr .framer-vyjk6, .framer-KYYCr .framer-gu1odh, .framer-KYYCr .framer-6jxmdw, .framer-KYYCr .framer-vadw1i, .framer-KYYCr .framer-1ffgcrw, .framer-KYYCr .framer-1j9mdi3, .framer-KYYCr .framer-1c8di1n, .framer-KYYCr .framer-kl86d3, .framer-KYYCr .framer-13oeh66, .framer-KYYCr .framer-feaqek { gap: 0px; } .framer-KYYCr.framer-1b5ydyb > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-KYYCr.framer-1b5ydyb > :first-child, .framer-KYYCr .framer-1wzq7ls > :first-child, .framer-KYYCr .framer-1of4spd > :first-child, .framer-KYYCr .framer-47n4du > :first-child, .framer-KYYCr .framer-1w2t1oi > :first-child, .framer-KYYCr .framer-gu1odh > :first-child, .framer-KYYCr .framer-6jxmdw > :first-child, .framer-KYYCr .framer-vadw1i > :first-child, .framer-KYYCr .framer-1ffgcrw > :first-child, .framer-KYYCr .framer-1j9mdi3 > :first-child { margin-top: 0px; } .framer-KYYCr.framer-1b5ydyb > :last-child, .framer-KYYCr .framer-1wzq7ls > :last-child, .framer-KYYCr .framer-1of4spd > :last-child, .framer-KYYCr .framer-47n4du > :last-child, .framer-KYYCr .framer-1w2t1oi > :last-child, .framer-KYYCr .framer-gu1odh > :last-child, .framer-KYYCr .framer-6jxmdw > :last-child, .framer-KYYCr .framer-vadw1i > :last-child, .framer-KYYCr .framer-1ffgcrw > :last-child, .framer-KYYCr .framer-1j9mdi3 > :last-child { margin-bottom: 0px; } .framer-KYYCr .framer-1wzq7ls > * { margin: 0px; margin-bottom: calc(50px / 2); margin-top: calc(50px / 2); } .framer-KYYCr .framer-6eneq3 > *, .framer-KYYCr .framer-1c8di1n > *, .framer-KYYCr .framer-kl86d3 > *, .framer-KYYCr .framer-13oeh66 > *, .framer-KYYCr .framer-feaqek > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-KYYCr .framer-6eneq3 > :first-child, .framer-KYYCr .framer-5mjn9m > :first-child, .framer-KYYCr .framer-18oyuoj > :first-child, .framer-KYYCr .framer-e223h2 > :first-child, .framer-KYYCr .framer-vyjk6 > :first-child, .framer-KYYCr .framer-1c8di1n > :first-child, .framer-KYYCr .framer-kl86d3 > :first-child, .framer-KYYCr .framer-13oeh66 > :first-child, .framer-KYYCr .framer-feaqek > :first-child { margin-left: 0px; } .framer-KYYCr .framer-6eneq3 > :last-child, .framer-KYYCr .framer-5mjn9m > :last-child, .framer-KYYCr .framer-18oyuoj > :last-child, .framer-KYYCr .framer-e223h2 > :last-child, .framer-KYYCr .framer-vyjk6 > :last-child, .framer-KYYCr .framer-1c8di1n > :last-child, .framer-KYYCr .framer-kl86d3 > :last-child, .framer-KYYCr .framer-13oeh66 > :last-child, .framer-KYYCr .framer-feaqek > :last-child { margin-right: 0px; } .framer-KYYCr .framer-5mjn9m > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-KYYCr .framer-18oyuoj > * { margin: 0px; margin-left: calc(60px / 2); margin-right: calc(60px / 2); } .framer-KYYCr .framer-1of4spd > *, .framer-KYYCr .framer-1ffgcrw > *, .framer-KYYCr .framer-1j9mdi3 > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-KYYCr .framer-e223h2 > *, .framer-KYYCr .framer-vyjk6 > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-KYYCr .framer-47n4du > *, .framer-KYYCr .framer-gu1odh > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-KYYCr .framer-1w2t1oi > *, .framer-KYYCr .framer-6jxmdw > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-KYYCr .framer-vadw1i > * { margin: 0px; margin-bottom: calc(60px / 2); margin-top: calc(60px / 2); } }',
  '.framer-KYYCr.framer-v-tez7sd.framer-1b5ydyb { width: 652px; }',
  '.framer-KYYCr.framer-v-tez7sd .framer-18oyuoj { flex-direction: column; }',
  '.framer-KYYCr.framer-v-tez7sd .framer-1of4spd { flex: none; width: 200%; }',
  '.framer-KYYCr.framer-v-tez7sd .framer-vadw1i { flex: none; width: 100%; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KYYCr.framer-v-tez7sd .framer-18oyuoj { gap: 0px; } .framer-KYYCr.framer-v-tez7sd .framer-18oyuoj > * { margin: 0px; margin-bottom: calc(60px / 2); margin-top: calc(60px / 2); } .framer-KYYCr.framer-v-tez7sd .framer-18oyuoj > :first-child { margin-top: 0px; } .framer-KYYCr.framer-v-tez7sd .framer-18oyuoj > :last-child { margin-bottom: 0px; } }',
  '.framer-KYYCr[data-border="true"]::after, .framer-KYYCr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerq64yDrOL3 = withCSS(Component2, css, 'framer-KYYCr',);
var stdin_default = Framerq64yDrOL3;
Framerq64yDrOL3.displayName = 'FullPage';
Framerq64yDrOL3.defaultProps = { height: 593, width: 1200, };
addPropertyControls2(Framerq64yDrOL3, {
  variant: { options: ['QJ6X5OV2Q', 'jNQqNcpjl',], optionTitles: ['Desktop', 'Tablet',], title: 'Variant', type: ControlType2.Enum, },
},);
addFonts(Framerq64yDrOL3, [{
  explicitInter: true,
  fonts: [{
    family: 'Inter',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZ1rib2Bg-4.woff2',
    weight: '600',
  }, {
    family: 'Inter',
    source: 'google',
    style: 'normal',
    url: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZ1rib2Bg-4.woff2',
    weight: '500',
  },],
}, ...PhosphorFonts,], { supportsExplicitInterCodegen: true, },);

// virtual:full-page
import { WithFramerBreakpoints, } from 'unframer/dist/react';
import { jsx, } from 'react/jsx-runtime';
stdin_default.Responsive = (props,) => {
  return /* @__PURE__ */ jsx(WithFramerBreakpoints, { Component: stdin_default, ...props, },);
};
var full_page_default = stdin_default;
export { full_page_default as default, };
