import { FieldDataEntryInput } from '#framer-client';
import { mcpTools, type McpToolNames } from './schema.js';
export { mcpTools, type McpToolNames };
export declare function parseIncomingFieldData(fieldData: unknown): Record<string, unknown>;
export declare function mcpToolHandler({ input, type, }: {
    input: any;
    type: McpToolNames;
}): Promise<string | import("framer-plugin").PublishInfo | {
    message: string;
    style: {
        path: string;
        name: string;
        light: string;
        dark: string | null;
        fontSize?: undefined;
        lineHeight?: undefined;
        letterSpacing?: undefined;
        paragraphSpacing?: undefined;
        transform?: undefined;
        alignment?: undefined;
        decoration?: undefined;
        balance?: undefined;
        tag?: undefined;
    };
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    style: {
        path: string;
        light: string;
        dark: string | null;
        name?: undefined;
        fontSize?: undefined;
        lineHeight?: undefined;
        letterSpacing?: undefined;
        paragraphSpacing?: undefined;
        transform?: undefined;
        alignment?: undefined;
        decoration?: undefined;
        balance?: undefined;
        tag?: undefined;
    };
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    style: {
        path: string;
        name: string;
        fontSize: `${number}px` | `${number}rem`;
        lineHeight: `${number}px` | `${number}em` | `${number}%`;
        letterSpacing: `${number}px` | `${number}em`;
        paragraphSpacing: number;
        transform: import("framer-plugin").TextTransform;
        alignment: import("framer-plugin").TextAlignment;
        decoration: import("framer-plugin").TextDecoration;
        balance: boolean;
        tag: import("framer-plugin").TextStyleTag;
        light?: undefined;
        dark?: undefined;
    };
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    results: {
        family: string;
        selector: string;
        weight: 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | null;
        style: "normal" | "italic" | null;
    }[];
    totalMatches: number;
    style?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    id: string;
    name: string;
    path: string;
    content: string;
    exports: readonly import("framer-plugin").CodeFileExport[];
    message?: undefined;
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    codeFile: {
        id: string;
        name: string;
        path: string;
        exports: readonly import("framer-plugin").CodeFileExport[];
    };
    typecheck: import("framer-plugin").TypecheckDiagnostic[];
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    collections: {
        id: string;
        name: string;
        managedBy: "user" | ("thisPlugin" | "anotherPlugin");
        readonly: boolean;
        fields: any[];
    }[];
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    pagination: {
        total: number;
        skip: any;
        limit: any;
        returned: number;
    };
    items: {
        id: string;
        slug: string;
        draft: boolean;
        fieldData: Record<string, FieldDataEntryInput>;
    }[];
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    item: {
        id: any;
        slug: any;
        draft: any;
        fieldData: any;
    };
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    deletedItem: {
        id: any;
        slug: string;
    };
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    collection?: undefined;
    fields?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    collection: {
        id: string;
        name: string;
        managedBy: "thisPlugin" | "anotherPlugin";
    };
    fields: {
        id: string;
        name: string;
        type: "string" | "number" | "boolean" | "date" | "file" | "array" | "enum" | "link" | "color" | "image" | "formattedText" | "collectionReference" | "multiCollectionReference";
    }[];
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    page?: undefined;
    hint?: undefined;
} | {
    message: string;
    page: {
        id: string;
        name: string | null;
        type: string;
        path?: undefined;
    };
    hint: string;
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
} | {
    message: string;
    page: {
        id: string;
        path: string | null;
        type: string;
        name?: undefined;
    };
    hint: string;
    style?: undefined;
    results?: undefined;
    totalMatches?: undefined;
    id?: undefined;
    name?: undefined;
    path?: undefined;
    content?: undefined;
    exports?: undefined;
    codeFile?: undefined;
    typecheck?: undefined;
    collections?: undefined;
    pagination?: undefined;
    items?: undefined;
    item?: undefined;
    deletedItem?: undefined;
    collection?: undefined;
    fields?: undefined;
}>;
//# sourceMappingURL=mcp-handlers.d.ts.map