// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f667fc580d8d9346 "ApiFlow (copy)", do not edit manually */
"use client";

import { stdin_default as stdin_default2 } from "../chunks/chunk-BKYYEYRA.js";
import "../chunks/chunk-YVFI7H4N.js";
import { stdin_default } from "../chunks/chunk-I55YHQAG.js";
import "../chunks/chunk-5WKTYKZI.js";
import "../chunks/chunk-ZYGL2A5H.js";
import "../chunks/chunk-DOAYAVFF.js";
import "../chunks/chunk-3IMWMF2U.js";
import "../chunks/chunk-WSFCRVEQ.js";

// virtual:interactive/customer-stories
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2xq58OZNQr3P9I0sin28/YeEduTN93BSgNBW5Qrxy/h45_XDIZO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var TabsFonts = getFonts(stdin_default2);
var CardsCustomerStoriesFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var CardsCustomerStoriesControls = getPropertyControls(stdin_default);
var cycleOrder = ["ZDH19H5O5", "Qmt4ya9CZ", "GuDtpnQNI", "c6Ed4HKPI"];
var serializationHash = "framer-PAHHY";
var variantClassNames = {
	c6Ed4HKPI: "framer-v-1qwcy9a",
	GuDtpnQNI: "framer-v-10v0x2a",
	Qmt4ya9CZ: "framer-v-1qy96ak",
	ZDH19H5O5: "framer-v-1husurc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: -800,
	y: 0,
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = {
	Desktop: "aDTDT_hty",
	Mobile: "VEYljc9r5",
};
var humanReadableVariantMap = {
	First: "ZDH19H5O5",
	Fourth: "c6Ed4HKPI",
	Second: "Qmt4ya9CZ",
	Third: "GuDtpnQNI",
};
var getProps = ({
	click,
	click2,
	click3,
	click4,
	height,
	id,
	variant1,
	width,
	...props
}) => {
	return {
		...props,
		bimA0vflE: click3 ?? props.bimA0vflE,
		Qhkm0Er7y:
			humanReadableEnumMap[variant1] ??
			variant1 ??
			props.Qhkm0Er7y ??
			"aDTDT_hty",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ZDH19H5O5",
		vVYzWnnJe: click ?? props.vVYzWnnJe,
		vYbut13MZ: click2 ?? props.vYbut13MZ,
		WOkXu6st6: click4 ?? props.WOkXu6st6,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		vVYzWnnJe,
		vYbut13MZ,
		bimA0vflE,
		WOkXu6st6,
		Qhkm0Er7y,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZDH19H5O5",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1y5wftw = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Qmt4ya9CZ"), 1e4);
	});
	const onAppear2e4otp = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("GuDtpnQNI"), 1e4);
	});
	const onAppear1htevee = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("c6Ed4HKPI"), 1e4);
	});
	const onAppearr5oxk6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("ZDH19H5O5"), 1e4);
	});
	const Wd_uH5B3z1e76usu = activeVariantCallback(async (...args) => {
		if (vVYzWnnJe) {
			const res = await vVYzWnnJe(...args);
			if (res === false) return false;
		}
		setVariant("ZDH19H5O5");
	});
	const Wd_uH5B3z1khcbpb = activeVariantCallback(async (...args) => {
		if (vYbut13MZ) {
			const res = await vYbut13MZ(...args);
			if (res === false) return false;
		}
		setVariant("Qmt4ya9CZ");
	});
	const Wd_uH5B3zpmk5ux = activeVariantCallback(async (...args) => {
		if (bimA0vflE) {
			const res = await bimA0vflE(...args);
			if (res === false) return false;
		}
		setVariant("GuDtpnQNI");
	});
	const Wd_uH5B3zg90a97 = activeVariantCallback(async (...args) => {
		if (WOkXu6st6) {
			const res = await WOkXu6st6(...args);
			if (res === false) return false;
		}
		setVariant("c6Ed4HKPI");
	});
	useOnVariantChange(baseVariant, {
		c6Ed4HKPI: onAppearr5oxk6,
		default: onAppear1y5wftw,
		GuDtpnQNI: onAppear1htevee,
		Qmt4ya9CZ: onAppear2e4otp,
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["Qmt4ya9CZ", "GuDtpnQNI", "c6Ed4HKPI"].includes(baseVariant))
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "Qmt4ya9CZ") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "GuDtpnQNI") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "c6Ed4HKPI") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			{
				<Variants animate={variants} initial={false}>
					{
						<Transition value={transition1}>
							{
								<motion.div
									{...restProps}
									{...gestureHandlers}
									className={cx(
										serializationHash,
										...sharedStyleClassNames,
										"framer-1husurc",
										className,
										classNames,
									)}
									data-framer-name={"First"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"ZDH19H5O5"}
									ref={ref ?? ref1}
									style={{
										...style,
									}}
									{...addPropertyOverrides(
										{
											c6Ed4HKPI: {
												"data-framer-name": "Fourth",
											},
											GuDtpnQNI: {
												"data-framer-name": "Third",
											},
											Qmt4ya9CZ: {
												"data-framer-name": "Second",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									{
										<motion.div
											className={"framer-1nwm2fq"}
											data-framer-name={"Section buttons"}
											layoutDependency={layoutDependency}
											layoutId={"TNsjI5Pms"}
										>
											{
												<ComponentViewportProvider
													height={48}
													width={`max(min(${componentViewport?.width || "100vw"}, 800px), 200px)`}
												>
													{
														<motion.div
															className={"framer-13t59ub-container"}
															layoutDependency={layoutDependency}
															layoutId={"aO4xJnjWK-container"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "aO4xJnjWK",
																kg1wL8gqw:
																	'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">   <path d="M2.25 2.25a.75.75 0 0 0 0 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 0 0-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 0 0 0-1.5H5.378A2.25 2.25 0 0 1 7.5 15h11.218a.75.75 0 0 0 .674-.421 60.358 60.358 0 0 0 2.96-7.228.75.75 0 0 0-.525-.965A60.864 60.864 0 0 0 5.68 4.509l-.232-.867A1.875 1.875 0 0 0 3.636 2.25H2.25ZM3.75 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0ZM16.5 20.25a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0Z" /> </svg>',
																layoutId: "aO4xJnjWK",
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: "h0XQJLrlb",
																Vb218_9bK: "Documentation",
																Wd_uH5B3z: Wd_uH5B3z1e76usu,
																width: "100%",
																...addPropertyOverrides(
																	{
																		c6Ed4HKPI: {
																			variant: "IIv28kAHe",
																		},
																		GuDtpnQNI: {
																			variant: "IIv28kAHe",
																		},
																		Qmt4ya9CZ: {
																			variant: "IIv28kAHe",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</motion.div>
													}
												</ComponentViewportProvider>
											}
											{
												<ComponentViewportProvider
													height={48}
													width={`max(min(${componentViewport?.width || "100vw"}, 800px), 200px)`}
												>
													{
														<motion.div
															className={"framer-19ir56w-container"}
															layoutDependency={layoutDependency}
															layoutId={"rtV7edR3d-container"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "rtV7edR3d",
																kg1wL8gqw:
																	'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">   <path fill-rule="evenodd" d="M3 2.25a.75.75 0 0 0 0 1.5v16.5h-.75a.75.75 0 0 0 0 1.5H15v-18a.75.75 0 0 0 0-1.5H3ZM6.75 19.5v-2.25a.75.75 0 0 1 .75-.75h3a.75.75 0 0 1 .75.75v2.25a.75.75 0 0 1-.75.75h-3a.75.75 0 0 1-.75-.75ZM6 6.75A.75.75 0 0 1 6.75 6h.75a.75.75 0 0 1 0 1.5h-.75A.75.75 0 0 1 6 6.75ZM6.75 9a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75ZM6 12.75a.75.75 0 0 1 .75-.75h.75a.75.75 0 0 1 0 1.5h-.75a.75.75 0 0 1-.75-.75ZM10.5 6a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75Zm-.75 3.75A.75.75 0 0 1 10.5 9h.75a.75.75 0 0 1 0 1.5h-.75a.75.75 0 0 1-.75-.75ZM10.5 12a.75.75 0 0 0 0 1.5h.75a.75.75 0 0 0 0-1.5h-.75ZM16.5 6.75v15h5.25a.75.75 0 0 0 0-1.5H21v-12a.75.75 0 0 0 0-1.5h-4.5Zm1.5 4.5a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Zm.75 2.25a.75.75 0 0 0-.75.75v.008c0 .414.336.75.75.75h.008a.75.75 0 0 0 .75-.75v-.008a.75.75 0 0 0-.75-.75h-.008ZM18 17.25a.75.75 0 0 1 .75-.75h.008a.75.75 0 0 1 .75.75v.008a.75.75 0 0 1-.75.75h-.008a.75.75 0 0 1-.75-.75v-.008Z" clip-rule="evenodd" /> </svg>',
																layoutId: "rtV7edR3d",
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: "IIv28kAHe",
																Vb218_9bK: "Help Desk",
																Wd_uH5B3z: Wd_uH5B3z1khcbpb,
																width: "100%",
																...addPropertyOverrides(
																	{
																		Qmt4ya9CZ: {
																			variant: "h0XQJLrlb",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</motion.div>
													}
												</ComponentViewportProvider>
											}
											{
												<ComponentViewportProvider
													height={48}
													width={`max(min(${componentViewport?.width || "100vw"}, 800px), 200px)`}
												>
													{
														<motion.div
															className={"framer-rjbnvi-container"}
															layoutDependency={layoutDependency}
															layoutId={"MAuUOtat9-container"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "MAuUOtat9",
																kg1wL8gqw:
																	'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">   <path d="M18.375 2.25c-1.035 0-1.875.84-1.875 1.875v15.75c0 1.035.84 1.875 1.875 1.875h.75c1.035 0 1.875-.84 1.875-1.875V4.125c0-1.036-.84-1.875-1.875-1.875h-.75ZM9.75 8.625c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v11.25c0 1.035-.84 1.875-1.875 1.875h-.75a1.875 1.875 0 0 1-1.875-1.875V8.625ZM3 13.125c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v6.75c0 1.035-.84 1.875-1.875 1.875h-.75A1.875 1.875 0 0 1 3 19.875v-6.75Z" /> </svg>',
																layoutId: "MAuUOtat9",
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: "IIv28kAHe",
																Vb218_9bK: "Blog",
																Wd_uH5B3z: Wd_uH5B3zpmk5ux,
																width: "100%",
																...addPropertyOverrides(
																	{
																		GuDtpnQNI: {
																			variant: "h0XQJLrlb",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</motion.div>
													}
												</ComponentViewportProvider>
											}
											{
												<ComponentViewportProvider
													height={48}
													width={`max(min(${componentViewport?.width || "100vw"}, 800px), 200px)`}
												>
													{
														<motion.div
															className={"framer-qupgo6-container"}
															layoutDependency={layoutDependency}
															layoutId={"mD9LkR50m-container"}
														>
															{_jsx(stdin_default2, {
																height: "100%",
																id: "mD9LkR50m",
																kg1wL8gqw:
																	'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">   <path d="M16.5 7.5h-9v9h9v-9Z" />   <path fill-rule="evenodd" d="M8.25 2.25A.75.75 0 0 1 9 3v.75h2.25V3a.75.75 0 0 1 1.5 0v.75H15V3a.75.75 0 0 1 1.5 0v.75h.75a3 3 0 0 1 3 3v.75H21A.75.75 0 0 1 21 9h-.75v2.25H21a.75.75 0 0 1 0 1.5h-.75V15H21a.75.75 0 0 1 0 1.5h-.75v.75a3 3 0 0 1-3 3h-.75V21a.75.75 0 0 1-1.5 0v-.75h-2.25V21a.75.75 0 0 1-1.5 0v-.75H9V21a.75.75 0 0 1-1.5 0v-.75h-.75a3 3 0 0 1-3-3v-.75H3A.75.75 0 0 1 3 15h.75v-2.25H3a.75.75 0 0 1 0-1.5h.75V9H3a.75.75 0 0 1 0-1.5h.75v-.75a3 3 0 0 1 3-3h.75V3a.75.75 0 0 1 .75-.75ZM6 6.75A.75.75 0 0 1 6.75 6h10.5a.75.75 0 0 1 .75.75v10.5a.75.75 0 0 1-.75.75H6.75a.75.75 0 0 1-.75-.75V6.75Z" clip-rule="evenodd" /> </svg>',
																layoutId: "mD9LkR50m",
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: "IIv28kAHe",
																Vb218_9bK: "Changelog",
																Wd_uH5B3z: Wd_uH5B3zg90a97,
																width: "100%",
																...addPropertyOverrides(
																	{
																		c6Ed4HKPI: {
																			variant: "h0XQJLrlb",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</motion.div>
													}
												</ComponentViewportProvider>
											}
										</motion.div>
									}
									{isDisplayed() && (
										<ComponentViewportProvider
											height={335}
											width={`min(${componentViewport?.width || "100vw"}, 1000px)`}
										>
											{
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation}
													className={"framer-oz2qgs-container"}
													data-framer-appear-id={"oz2qgs"}
													data-framer-name={"Retail"}
													initial={animation1}
													layoutDependency={layoutDependency}
													layoutId={"hEQLWLEiI-container"}
													name={"Retail"}
													optimized={true}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "hEQLWLEiI",
														j1XFDHXr2:
															"Turn Notion into a professional docs website",
														J3WQIyWE_: `"Integrating ApiFlow's AI voice API into our stores has been a game-changer. We've reduced our operational costs by 40% and significantly enhanced the shopping experience for our customers. "`,
														KA7akYL6j:
															"Publish awesome websites using Notion to manage content. Save 500+ hours of dev work. No design or code skills required.",
														layoutId: "hEQLWLEiI",
														name: "Retail",
														NrPTfcfPh: "CTO at BigCompany",
														style: {
															maxWidth: "100%",
															width: "100%",
														},
														variant: "aDTDT_hty",
														w2AZSnOj8: "Jack Jones",
														width: "100%",
													})}
												</MotionDivWithFXWithOptimizedAppearEffect>
											}
										</ComponentViewportProvider>
									)}
									{isDisplayed1() && (
										<ComponentViewportProvider
											{...addPropertyOverrides(
												{
													Qmt4ya9CZ: {
														height: 335,
														width: `min(${componentViewport?.width || "100vw"}, 1000px)`,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											{
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation}
													className={"framer-hyaqnx-container"}
													data-framer-appear-id={"hyaqnx"}
													data-framer-name={"Healthcare"}
													initial={animation1}
													layoutDependency={layoutDependency}
													layoutId={"BjOsDBouY-container"}
													name={"Healthcare"}
													optimized={true}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "BjOsDBouY",
														j1XFDHXr2: "Improving Patient Care with ApiFlow",
														J3WQIyWE_: `"ApiFlow's AI voice API has revolutionized our administrative processes. By automating routine tasks like appointment scheduling and billing inquiries, we've cut administrative costs by 50%."`,
														KA7akYL6j:
															"A major healthcare provider adopted ApiFlow's AI voice API to automate routine administrative tasks such as appointment scheduling, patient registration, and billing inquiries. This automation freed up healthcare staff to focus on more complex responsibilities, leading to a 50% reduction in administrative costs and improved patient care through more efficient and accurate data management.",
														layoutId: "BjOsDBouY",
														name: "Healthcare",
														NrPTfcfPh:
															"Chief Administrative Officer at HealthPlus",
														NY610Fasy: addImageAlt(
															{
																src: "https://framerusercontent.com/images/RwJYO348qAEWdigjrVxcKEE155I.svg",
															},
															"",
														),
														style: {
															maxWidth: "100%",
															width: "100%",
														},
														variant: Qhkm0Er7y,
														w2AZSnOj8: "Dr. Emily Roberts",
														width: "100%",
													})}
												</MotionDivWithFXWithOptimizedAppearEffect>
											}
										</ComponentViewportProvider>
									)}
									{isDisplayed2() && (
										<ComponentViewportProvider
											{...addPropertyOverrides(
												{
													GuDtpnQNI: {
														height: 335,
														width: `min(${componentViewport?.width || "100vw"}, 1000px)`,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											{
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation}
													className={"framer-z6se6n-container"}
													data-framer-appear-id={"z6se6n"}
													data-framer-name={"B2B"}
													initial={animation1}
													layoutDependency={layoutDependency}
													layoutId={"X8KeWh24V-container"}
													name={"B2B"}
													optimized={true}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "X8KeWh24V",
														j1XFDHXr2:
															"Boosting Sales Efficiency and Customer Engagement",
														J3WQIyWE_: `"Using ApiFlow's AI voice API has transformed our sales process. The AI voice agents handle initial inquiries and qualify leads, allowing our sales team to focus on closing deals. We've seen a 30% increase in sales efficiency."`,
														KA7akYL6j:
															"A B2B sales company implemented ApiFlow's AI voice API to enhance their sales process. The AI voice agents handled initial customer inquiries, qualified leads, and scheduled follow-up calls, allowing sales representatives to focus on closing deals. This led to a 30% increase in sales efficiency and a 25% boost in customer engagement, ultimately driving higher revenue.",
														layoutId: "X8KeWh24V",
														name: "B2B",
														NrPTfcfPh: "Customer Support at TechSolutions",
														NY610Fasy: addImageAlt(
															{
																src: "https://framerusercontent.com/images/RI6iObLNqFGzuPqHlfzJC8nvlag.svg",
															},
															"",
														),
														style: {
															maxWidth: "100%",
															width: "100%",
														},
														variant: Qhkm0Er7y,
														w2AZSnOj8: "Jessica Martinez",
														width: "100%",
													})}
												</MotionDivWithFXWithOptimizedAppearEffect>
											}
										</ComponentViewportProvider>
									)}
									{isDisplayed3() && (
										<ComponentViewportProvider
											{...addPropertyOverrides(
												{
													c6Ed4HKPI: {
														height: 335,
														width: `min(${componentViewport?.width || "100vw"}, 1000px)`,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											{
												<MotionDivWithFXWithOptimizedAppearEffect
													__perspectiveFX={false}
													__smartComponentFX={true}
													__targetOpacity={1}
													animate={animation}
													className={"framer-16ldg55-container"}
													data-framer-appear-id={"16ldg55"}
													data-framer-name={"Ai Startups"}
													initial={animation1}
													layoutDependency={layoutDependency}
													layoutId={"WzVgqaiqx-container"}
													name={"Ai Startups"}
													optimized={true}
												>
													{_jsx(stdin_default, {
														height: "100%",
														id: "WzVgqaiqx",
														j1XFDHXr2:
															"Optimizing Technical Support and Reducing Response Times",
														J3WQIyWE_: `"ApiFlow's AI voice API has drastically improved our technical support system. The AI-powered voice agents provide instant troubleshooting assistance, reducing our response times by 60% and cutting support costs by 35%."`,
														KA7akYL6j:
															"A tech company integrated ApiFlow's AI voice API into their technical support system. The AI-powered voice agents provided instant troubleshooting assistance and resolved common technical issues without human intervention. This resulted in a 60% reduction in response times and a 35% decrease in support costs, while maintaining high levels of customer satisfaction.",
														layoutId: "WzVgqaiqx",
														name: "Ai Startups",
														NrPTfcfPh: "CTO at BigCompany",
														NY610Fasy: addImageAlt(
															{
																src: "https://framerusercontent.com/images/GX4rQcDnl0SX41IBDeAIKsOFXk.svg",
															},
															"",
														),
														style: {
															maxWidth: "100%",
															width: "100%",
														},
														variant: Qhkm0Er7y,
														w2AZSnOj8: "Jack Jones",
														width: "100%",
													})}
												</MotionDivWithFXWithOptimizedAppearEffect>
											}
										</ComponentViewportProvider>
									)}
								</motion.div>
							}
						</Transition>
					}
				</Variants>
			}
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PAHHY.framer-kvezl8, .framer-PAHHY .framer-kvezl8 { display: block; }",
	".framer-PAHHY.framer-1husurc { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1122px; }",
	".framer-PAHHY .framer-1nwm2fq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px; height: min-content; justify-content: center; max-width: 800px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PAHHY .framer-13t59ub-container, .framer-PAHHY .framer-19ir56w-container, .framer-PAHHY .framer-rjbnvi-container, .framer-PAHHY .framer-qupgo6-container { flex: 1 0 0px; height: 48px; min-width: 200px; position: relative; width: 1px; }",
	".framer-PAHHY .framer-oz2qgs-container, .framer-PAHHY .framer-hyaqnx-container, .framer-PAHHY .framer-z6se6n-container, .framer-PAHHY .framer-16ldg55-container { flex: none; height: auto; max-width: 1000px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PAHHY.framer-1husurc, .framer-PAHHY .framer-1nwm2fq { gap: 0px; } .framer-PAHHY.framer-1husurc > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-PAHHY.framer-1husurc > :first-child { margin-top: 0px; } .framer-PAHHY.framer-1husurc > :last-child { margin-bottom: 0px; } .framer-PAHHY .framer-1nwm2fq > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-PAHHY .framer-1nwm2fq > :first-child { margin-left: 0px; } .framer-PAHHY .framer-1nwm2fq > :last-child { margin-right: 0px; } }",
];
var Framerh45_XDIZO = withCSS(Component, css, "framer-PAHHY");
var stdin_default3 = Framerh45_XDIZO;
Framerh45_XDIZO.displayName = "Interactive/Customer stories";
Framerh45_XDIZO.defaultProps = {
	height: 415,
	width: 1122,
};
addPropertyControls(Framerh45_XDIZO, {
	variant: {
		options: ["ZDH19H5O5", "Qmt4ya9CZ", "GuDtpnQNI", "c6Ed4HKPI"],
		optionTitles: ["First", "Second", "Third", "Fourth"],
		title: "Variant",
		type: ControlType.Enum,
	},
	vVYzWnnJe: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	vYbut13MZ: {
		title: "Click 2",
		type: ControlType.EventHandler,
	},
	bimA0vflE: {
		title: "Click 3",
		type: ControlType.EventHandler,
	},
	WOkXu6st6: {
		title: "Click 4",
		type: ControlType.EventHandler,
	},
	Qhkm0Er7y: CardsCustomerStoriesControls?.["variant"] && {
		...CardsCustomerStoriesControls["variant"],
		defaultValue: "aDTDT_hty",
		description: void 0,
		hidden: void 0,
		title: "Variant",
	},
});
addFonts(
	Framerh45_XDIZO,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TabsFonts,
		...CardsCustomerStoriesFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:interactive/customer-stories
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ZDH19H5O5",
};
stdin_default3.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={{
				I0Vjsk230: {
					path: "/pricing",
				},
				If1LKvdh8: {
					path: "/blog/:slug",
				},
				MYlLV6Tip: {
					path: "/docs",
				},
				NSnQ_g8yw: {
					path: "/:slug",
				},
				augiA20Il: {
					path: "/",
				},
				cvVskSlKE: {
					path: "/sign-up",
				},
				dqRVpj9Kn: {
					path: "/docs/:slug",
				},
				iUM2Wrnwp: {
					path: "/contact-sales-2",
				},
				j_IHQLq_9: {
					path: "/sign-in",
				},
				lreH5keWI: {
					path: "/support",
				},
				qNb6QfkBq: {
					path: "/contact-sales",
				},
				so7P3QBWY: {
					path: "/404",
				},
				tBghjsyop: {
					path: "/blog",
				},
			}}
			framerSiteId={
				"f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405"
			}
			locale={locale}
			locales={locales}
		>
			{
				<WithFramerBreakpoints
					Component={stdin_default3}
					variants={defaultResponsiveVariants}
					{...rest}
				/>
			}
		</ContextProviders>
	);
};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={{
				I0Vjsk230: {
					path: "/pricing",
				},
				If1LKvdh8: {
					path: "/blog/:slug",
				},
				MYlLV6Tip: {
					path: "/docs",
				},
				NSnQ_g8yw: {
					path: "/:slug",
				},
				augiA20Il: {
					path: "/",
				},
				cvVskSlKE: {
					path: "/sign-up",
				},
				dqRVpj9Kn: {
					path: "/docs/:slug",
				},
				iUM2Wrnwp: {
					path: "/contact-sales-2",
				},
				j_IHQLq_9: {
					path: "/sign-in",
				},
				lreH5keWI: {
					path: "/support",
				},
				qNb6QfkBq: {
					path: "/contact-sales",
				},
				so7P3QBWY: {
					path: "/404",
				},
				tBghjsyop: {
					path: "/blog",
				},
			}}
			framerSiteId={
				"f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
Object.assign(ComponentWithRoot, stdin_default3);
export { ComponentWithRoot as default };
