// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "ApiFlow (copy)", do not edit manually */
'use client';
import { className as className3, css as css3, fonts as fonts3, } from '../chunk-TGMNVGOX.js';
import { className as className2, css as css2, fonts as fonts2, } from '../chunk-ISS7W3XJ.js';
import { className, css, fonts, } from '../chunk-ZRDVOIMG.js';
import '../chunk-MLKGABMK.js';

// virtual:cards/blog-card
import { Fragment as Fragment2, } from 'react';
import { ContextProviders, } from 'unframer';

// https :https://framerusercontent.com/modules/jbkTuDiyVcx21mUBJ19B/nlCkuwBdyY438fZa4GaW/QK36RbJuJ.js
import { jsx as _jsx, jsxs as _jsxs, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';
var enabledGestures = { lmPHjoU0y: { hover: true, }, };
var serializationHash = 'framer-7QGce';
var variantClassNames = { lmPHjoU0y: 'framer-v-1ne6iib', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: 'spring', };
var toResponsiveImage = (value,) => {
  if (typeof value === 'object' && value !== null && typeof value.src === 'string') {
    return value;
  }
  return typeof value === 'string' ? { src: value, } : void 0;
};
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion.create(React.Fragment,);
var getProps = ({ click, date, description, height, id, image, link, title, width, ...props },) => {
  var _ref, _ref1, _ref2, _ref3;
  return {
    ...props,
    ccSVqR0N7: (_ref = image !== null && image !== void 0 ? image : props.ccSVqR0N7) !== null && _ref !== void 0 ? _ref : {
      src: 'https://framerusercontent.com/images/2OQjOCJdXRtxvP0clOODVVr4bq4.jpg?scale-down-to=512',
      srcSet:
        'https://framerusercontent.com/images/2OQjOCJdXRtxvP0clOODVVr4bq4.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/2OQjOCJdXRtxvP0clOODVVr4bq4.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/2OQjOCJdXRtxvP0clOODVVr4bq4.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/2OQjOCJdXRtxvP0clOODVVr4bq4.jpg 3984w',
    },
    K_G_RvC9u: (_ref1 = title !== null && title !== void 0 ? title : props.K_G_RvC9u) !== null && _ref1 !== void 0
      ? _ref1
      : 'Here goes the title of the article and it will be long',
    Lzm9iQLvn: link !== null && link !== void 0 ? link : props.Lzm9iQLvn,
    OHaD85dYv: (_ref2 = description !== null && description !== void 0 ? description : props.OHaD85dYv) !== null && _ref2 !== void 0
      ? _ref2
      : 'And here is the a short description of the article that we are about to read',
    Vaoq_Msyt: (_ref3 = date !== null && date !== void 0 ? date : props.Vaoq_Msyt) !== null && _ref3 !== void 0 ? _ref3 : 'June 20, 2024',
    VDu7Z5qXk: click !== null && click !== void 0 ? click : props.VDu7Z5qXk,
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const {
    style,
    className: className4,
    layoutId,
    variant,
    ccSVqR0N7,
    K_G_RvC9u,
    OHaD85dYv,
    Vaoq_Msyt,
    Lzm9iQLvn,
    VDu7Z5qXk,
    ...restProps
  } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ defaultVariant: 'lmPHjoU0y', enabledGestures, variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const { activeVariantCallback, delay, } = useActiveVariantCallback(baseVariant,);
  const onTap15fmku8 = activeVariantCallback(async (...args) => {
    if (VDu7Z5qXk) {
      const res = await VDu7Z5qXk(...args,);
      if (res === false) return false;
    }
  },);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [className, className3, className2,];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsx(Link, {
          href: Lzm9iQLvn,
          nodeId: 'lmPHjoU0y',
          children: /* @__PURE__ */ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(serializationHash, ...sharedStyleClassNames, 'framer-1ne6iib', className4, classNames,)} framer-njkgze`,
            'data-border': true,
            'data-framer-name': 'Variant 1',
            layoutDependency,
            layoutId: 'lmPHjoU0y',
            ref: ref !== null && ref !== void 0 ? ref : ref1,
            style: {
              '--border-bottom-width': '1px',
              '--border-color': 'var(--token-1691cb44-c002-4542-9545-8a0801f91af2, rgb(231, 231, 231))',
              '--border-left-width': '1px',
              '--border-right-width': '1px',
              '--border-style': 'dotted',
              '--border-top-width': '1px',
              ...style,
            },
            variants: {
              'lmPHjoU0y-hover': { '--border-color': 'var(--token-4a18edb7-e149-464f-8c02-aa015661ab43, rgb(255, 160, 122))', },
            },
            ...addPropertyOverrides({ 'lmPHjoU0y-hover': { 'data-framer-name': void 0, }, }, baseVariant, gestureVariant,),
            children: [
              /* @__PURE__ */ _jsx(motion.div, {
                className: 'framer-169u9pa',
                layoutDependency,
                layoutId: 'rOKdLgngr',
                children: /* @__PURE__ */ _jsx(Image, {
                  background: {
                    alt: '',
                    fit: 'fill',
                    loading: getLoadingLazyAtYPosition(
                      ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 + 0 + 0,
                    ),
                    pixelHeight: 2656,
                    pixelWidth: 3984,
                    sizes: (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw',
                    ...toResponsiveImage(ccSVqR0N7,),
                  },
                  className: 'framer-m86a3e',
                  layoutDependency,
                  layoutId: 'YBv_yXuH3',
                  ...addPropertyOverrides(
                    {
                      'lmPHjoU0y-hover': {
                        background: {
                          alt: '',
                          fit: 'fill',
                          loading: getLoadingLazyAtYPosition(
                            ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + 0 + 0 + -8,
                          ),
                          pixelHeight: 2656,
                          pixelWidth: 3984,
                          sizes: `calc(${
                            (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || '100vw'
                          } + 16px)`,
                          ...toResponsiveImage(ccSVqR0N7,),
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                },),
              },),
              /* @__PURE__ */ _jsxs(motion.div, {
                className: 'framer-il5aw8',
                'data-border': true,
                layoutDependency,
                layoutId: 'DakVN7nE5',
                style: {
                  '--border-bottom-width': '0px',
                  '--border-color': 'var(--token-1691cb44-c002-4542-9545-8a0801f91af2, rgb(231, 231, 231))',
                  '--border-left-width': '0px',
                  '--border-right-width': '0px',
                  '--border-style': 'dotted',
                  '--border-top-width': '1px',
                },
                children: [
                  /* @__PURE__ */ _jsxs(motion.div, {
                    className: 'framer-ks1xkh',
                    layoutDependency,
                    layoutId: 'T3JvFK2ji',
                    children: [
                      /* @__PURE__ */ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx(React.Fragment, {
                          children: /* @__PURE__ */ _jsx(motion.p, {
                            className: 'framer-styles-preset-1o7aipf',
                            'data-styles-preset': 'x1n9RoGI8',
                            children: 'Here goes the title of the article and it will be long',
                          },),
                        },),
                        className: 'framer-klc264',
                        'data-highlight': true,
                        fonts: ['Inter',],
                        layoutDependency,
                        layoutId: 'Hj4i_tXrx',
                        onTap: onTap15fmku8,
                        style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', },
                        text: K_G_RvC9u,
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                      /* @__PURE__ */ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /* @__PURE__ */ _jsx(React.Fragment, {
                          children: /* @__PURE__ */ _jsx(motion.p, {
                            className: 'framer-styles-preset-1aj6jmn',
                            'data-styles-preset': 'TeHXylmO7',
                            children: 'And here is the a short description of the article that we are about to read',
                          },),
                        },),
                        className: 'framer-12jhylw',
                        fonts: ['Inter',],
                        layoutDependency,
                        layoutId: 'qapkBQIZd',
                        style: {
                          '--framer-link-text-color': 'rgb(0, 153, 255)',
                          '--framer-link-text-decoration': 'underline',
                          opacity: 0.9,
                        },
                        text: OHaD85dYv,
                        verticalAlignment: 'top',
                        withExternalLayout: true,
                      },),
                    ],
                  },),
                  /* @__PURE__ */ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /* @__PURE__ */ _jsx(React.Fragment, {
                      children: /* @__PURE__ */ _jsx(motion.p, {
                        className: 'framer-styles-preset-1dbggqt',
                        'data-styles-preset': 'gj4zreqLr',
                        style: { '--framer-text-alignment': 'left', },
                        children: 'June 20, 2024',
                      },),
                    },),
                    className: 'framer-1lm5x7i',
                    fonts: ['Inter',],
                    layoutDependency,
                    layoutId: 'AOqVZ0D69',
                    style: { '--framer-link-text-color': 'rgb(0, 153, 255)', '--framer-link-text-decoration': 'underline', opacity: 0.8, },
                    text: Vaoq_Msyt,
                    verticalAlignment: 'top',
                    withExternalLayout: true,
                  },),
                ],
              },),
            ],
          },),
        },),
      },),
    },),
  },);
},);
var css4 = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-7QGce.framer-njkgze, .framer-7QGce .framer-njkgze { display: block; }',
  '.framer-7QGce.framer-1ne6iib { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 315px; }',
  '.framer-7QGce .framer-169u9pa { flex: none; height: 210px; overflow: hidden; position: relative; width: 100%; }',
  '.framer-7QGce .framer-m86a3e { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }',
  '.framer-7QGce .framer-il5aw8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 32px; position: relative; width: 100%; }',
  '.framer-7QGce .framer-ks1xkh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }',
  '.framer-7QGce .framer-klc264 { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '.framer-7QGce .framer-12jhylw, .framer-7QGce .framer-1lm5x7i { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }',
  '@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-7QGce.framer-1ne6iib, .framer-7QGce .framer-il5aw8, .framer-7QGce .framer-ks1xkh { gap: 0px; } .framer-7QGce.framer-1ne6iib > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-7QGce.framer-1ne6iib > :first-child, .framer-7QGce .framer-il5aw8 > :first-child, .framer-7QGce .framer-ks1xkh > :first-child { margin-top: 0px; } .framer-7QGce.framer-1ne6iib > :last-child, .framer-7QGce .framer-il5aw8 > :last-child, .framer-7QGce .framer-ks1xkh > :last-child { margin-bottom: 0px; } .framer-7QGce .framer-il5aw8 > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-7QGce .framer-ks1xkh > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }',
  '.framer-7QGce.framer-v-1ne6iib.hover .framer-m86a3e { bottom: -8px; left: -8px; right: -8px; top: -8px; }',
  ...css,
  ...css3,
  ...css2,
  '.framer-7QGce[data-border="true"]::after, .framer-7QGce [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerQK36RbJuJ = withCSS(Component, css4, 'framer-7QGce',);
var stdin_default = FramerQK36RbJuJ;
FramerQK36RbJuJ.displayName = 'Cards/Blog card';
FramerQK36RbJuJ.defaultProps = { height: 412, width: 315, };
addPropertyControls(FramerQK36RbJuJ, {
  ccSVqR0N7: {
    __defaultAssetReference:
      'data:framer/asset-reference,2OQjOCJdXRtxvP0clOODVVr4bq4.jpg?originalFilename=photo-1623282033815-40b05d96c903%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxfHxhcGl8ZW58MHx8fHwxNzE5MTE2ODg1fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto',
    title: 'Image',
    type: ControlType.ResponsiveImage,
  },
  K_G_RvC9u: {
    defaultValue: 'Here goes the title of the article and it will be long',
    displayTextArea: false,
    title: 'Title',
    type: ControlType.String,
  },
  OHaD85dYv: {
    defaultValue: 'And here is the a short description of the article that we are about to read',
    displayTextArea: false,
    title: 'Description',
    type: ControlType.String,
  },
  Vaoq_Msyt: { defaultValue: 'June 20, 2024', displayTextArea: false, title: 'Date', type: ControlType.String, },
  Lzm9iQLvn: { title: 'Link', type: ControlType.Link, },
  VDu7Z5qXk: { title: 'Click', type: ControlType.EventHandler, },
},);
addFonts(FramerQK36RbJuJ, [
  {
    explicitInter: true,
    fonts: [{
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F',
      url: 'https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
      url: 'https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+1F00-1FFF',
      url: 'https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0370-03FF',
      url: 'https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF',
      url: 'https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange:
        'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
      url: 'https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2',
      weight: '400',
    }, {
      family: 'Inter',
      source: 'framer',
      style: 'normal',
      unicodeRange: 'U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB',
      url: 'https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2',
      weight: '400',
    },],
  },
  ...getFontsFromSharedStyle(fonts,),
  ...getFontsFromSharedStyle(fonts3,),
  ...getFontsFromSharedStyle(fonts2,),
], { supportsExplicitInterCodegen: true, },);

// virtual:cards/blog-card
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [{ 'id': 'M_lnJlsvf', 'name': 'Italian (Italy)', 'slug': 'it', 'code': 'it-IT', },];
stdin_default.Responsive = ({ locale, ...props },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        x: {
          elements: {},
          page: /* @__PURE__ */ jsx(
            WithFramerBreakpoints,
            {
              Component: stdin_default,
              ...props,
            },
          ),
          path: '/',
        },
      },
      framerSiteId: 'f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routeId: 'x',
      routes: {
        x: {
          elements: {},
          page: /* @__PURE__ */ jsx(stdin_default, { ...rest, },),
          path: '/',
        },
      },
      framerSiteId: 'f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default,);
export { ComponentWithRoot as default, };
