// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 080b0b6d577bdc21 "Unframer Simplicity demo", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-PUNT4OMX.js";
import "./chunks/chunk-FY4DB67J.js";
import "./chunks/chunk-YBHXTZ5U.js";
import "./chunks/chunk-QYC47C72.js";
import { className, css, fonts } from "./chunks/chunk-BEKPESE7.js";
import { stdin_default } from "./chunks/chunk-U2BTSRYM.js";
import "./chunks/chunk-ZKAXZ4P5.js";
import { routes } from "./chunks/chunk-HEB6EHGG.js";

// virtual:section-testimonials
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8yWQJevMrmbyJU3TjtDM/hPO6HSvGx2gWTY1sxcWH/BLpQs2pt2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ElementsBadgeFonts = getFonts(stdin_default);
var CardsTestimonialFonts = getFonts(stdin_default2);
var cycleOrder = ["jEif1shEi", "PBicSvuJH", "Deb_EOg_O"];
var serializationHash = "framer-aY2Rp";
var variantClassNames = {
	Deb_EOg_O: "framer-v-e9gmpu",
	jEif1shEi: "framer-v-19j2h69",
	PBicSvuJH: "framer-v-ixxb1t",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "jEif1shEi",
	Phone: "Deb_EOg_O",
	Tablet: "PBicSvuJH",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "jEif1shEi",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jEif1shEi",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-19j2h69",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"jEif1shEi"}
						ref={ref ?? ref1}
						style={{
							backgroundColor:
								"var(--token-f4cf9e3e-da35-4e33-897c-29a30a250c5f, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								Deb_EOg_O: {
									"data-framer-name": "Phone",
								},
								PBicSvuJH: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-mme95t"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"TqDH5GeM1"}
						>
							<motion.div
								className={"framer-ratzws"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"hx8mtCB9e"}
							>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
											PBicSvuJH: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-swkefi-container"}
										layoutDependency={layoutDependency}
										layoutId={"pZHVqlJs3-container"}
									>
										{_jsx(stdin_default, {
											D_QyhowU2: "About Unframer",
											height: "100%",
											id: "pZHVqlJs3",
											layoutId: "pZHVqlJs3",
											variant: "ih1f0O9Of",
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-6rgfz9"}
									fonts={["FS;Satoshi-medium"]}
									layoutDependency={layoutDependency}
									layoutId={"NlMr1RQE2"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "55px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.04em",
												"--framer-line-height": "1.1em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
											}}
										>
											{"Download Framer components as simple files"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-11b7jjo"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"VpmONdNEB"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1qe6evr"}
											data-styles-preset={"wHLHeTMJ0"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{
												"Works with any React framework (Next.js, Remix, Vite, etc)"
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-14gcpcg"}
								data-framer-name={"Grid"}
								layoutDependency={layoutDependency}
								layoutId={"PsYEpIbLc"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 1080,
										intrinsicWidth: 1920,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												80 +
												(((componentViewport?.height || 952) - 160 - 857.5) /
													2 +
													0 +
													0) +
												0 +
												331.5 +
												11368683772161603e-29,
										),
										pixelHeight: 2160,
										pixelWidth: 3840,
										positionX: "center",
										positionY: "center",
										sizes: `min(${componentViewport?.width || "100vw"} - 160px, 1200px)`,
										src: "https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048",
										srcSet:
											"https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg 3840w",
									}}
									className={"framer-1b509h1"}
									data-framer-name={"BG"}
									layoutDependency={layoutDependency}
									layoutId={"EZDR5UQtb"}
									style={{
										mask: "radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
										opacity: 0.75,
										WebkitMask:
											"radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
									}}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 1080,
													intrinsicWidth: 1920,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															80 +
															(((componentViewport?.height || 3030) -
																160 -
																1957.5) /
																2 +
																0 +
																0) +
															0 +
															331.5 +
															3410605131648481e-28,
													),
													pixelHeight: 2160,
													pixelWidth: 3840,
													positionX: "center",
													positionY: "center",
													sizes: `min(${componentViewport?.width || "100vw"} - 48px, 1200px)`,
													src: "https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048",
													srcSet:
														"https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg 3840w",
												},
											},
											PBicSvuJH: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 1080,
													intrinsicWidth: 1920,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															80 +
															(((componentViewport?.height || 1179) -
																160 -
																1132.5) /
																2 +
																0 +
																0) +
															0 +
															331.5 +
															-0.2947019867548306,
													),
													pixelHeight: 2160,
													pixelWidth: 3840,
													positionX: "center",
													positionY: "center",
													sizes: `min(${componentViewport?.width || "100vw"} - 64px, 1200px)`,
													src: "https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048",
													srcSet:
														"https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/wwbsS5B2jq7ReaUidHboPOGp8.jpg 3840w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													0,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-xjw21j-container"}
										layoutDependency={layoutDependency}
										layoutId={"pK2x_5R_u-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/582SZU7UbOm092FEpvORB5g3Qg.png",
													srcSet:
														"https://framerusercontent.com/images/582SZU7UbOm092FEpvORB5g3Qg.png?scale-down-to=1024 771w,https://framerusercontent.com/images/582SZU7UbOm092FEpvORB5g3Qg.png?scale-down-to=2048 1542w,https://framerusercontent.com/images/582SZU7UbOm092FEpvORB5g3Qg.png 1856w",
												},
												"",
											),
											ECqJZ1hHM: "Component Dependency",
											height: "100%",
											id: "pK2x_5R_u",
											layoutId: "pK2x_5R_u",
											oRy6t91PU: "Sarah Johnson",
											style: {
												width: "100%",
											},
											VePkjXSEB: '"Includes all your components dependencies"',
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													275,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-h6r4sx-container"}
										layoutDependency={layoutDependency}
										layoutId={"SLidao9ZK-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/zfmF1iFYDX2iAwx2tDdmHAHKsKY.png",
													srcSet:
														"https://framerusercontent.com/images/zfmF1iFYDX2iAwx2tDdmHAHKsKY.png?scale-down-to=512 512w,https://framerusercontent.com/images/zfmF1iFYDX2iAwx2tDdmHAHKsKY.png 1024w",
												},
												"",
											),
											ECqJZ1hHM: "Framer Integration",
											height: "100%",
											id: "SLidao9ZK",
											layoutId: "SLidao9ZK",
											oRy6t91PU: "Viri Ramirez",
											style: {
												width: "100%",
											},
											VePkjXSEB:
												'"Works with Framer locales, fetch, Forms, color styles"',
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													550,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													275,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-17wjtwg-container"}
										layoutDependency={layoutDependency}
										layoutId={"ykeGQy3l4-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/Inuou987yLKbSzFSEWH9F4znyc.png",
													srcSet:
														"https://framerusercontent.com/images/Inuou987yLKbSzFSEWH9F4znyc.png?scale-down-to=512 512w,https://framerusercontent.com/images/Inuou987yLKbSzFSEWH9F4znyc.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Inuou987yLKbSzFSEWH9F4znyc.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Inuou987yLKbSzFSEWH9F4znyc.png 2464w",
												},
												"",
											),
											ECqJZ1hHM: "Dark Mode Support",
											height: "100%",
											id: "ykeGQy3l4",
											layoutId: "ykeGQy3l4",
											oRy6t91PU: "Anna Paige",
											style: {
												width: "100%",
											},
											VePkjXSEB: '"Supports dark mode via `dark` class"',
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										275
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													825,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													275,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1byzxvn-container"}
										layoutDependency={layoutDependency}
										layoutId={"QPpscyL2t-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/rDEgo0yhj2Qldk12p9Px3Vo65g8.png",
													srcSet:
														"https://framerusercontent.com/images/rDEgo0yhj2Qldk12p9Px3Vo65g8.png?scale-down-to=512 512w,https://framerusercontent.com/images/rDEgo0yhj2Qldk12p9Px3Vo65g8.png 1024w",
												},
												"",
											),
											ECqJZ1hHM: "TypeScript Compatibility",
											height: "100%",
											id: "QPpscyL2t",
											layoutId: "QPpscyL2t",
											oRy6t91PU: "David Rye",
											style: {
												width: "100%",
											},
											VePkjXSEB:
												'"Has TypeScript support, inferred from component variables"',
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										275
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													1100,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													550,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1wddgsn-container"}
										layoutDependency={layoutDependency}
										layoutId={"prIVEmwEG-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/GdyCKGcpQKWl89G3amhIWEqGBg.png",
													srcSet:
														"https://framerusercontent.com/images/GdyCKGcpQKWl89G3amhIWEqGBg.png?scale-down-to=512 512w,https://framerusercontent.com/images/GdyCKGcpQKWl89G3amhIWEqGBg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/GdyCKGcpQKWl89G3amhIWEqGBg.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/GdyCKGcpQKWl89G3amhIWEqGBg.png 2848w",
												},
												"",
											),
											ECqJZ1hHM: "Co-founder of Wednseday",
											height: "100%",
											id: "prIVEmwEG",
											layoutId: "prIVEmwEG",
											oRy6t91PU: "Pablo Yuri",
											style: {
												width: "100%",
											},
											VePkjXSEB:
												"\u201CSimplicity made managing my to-dos effortless. My productivity has never been higher.\u201D",
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={251}
									width={`max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 48px) / 3, 200px)`}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 952) - 160 - 857.5) / 2 +
											0 +
											0) +
										0 +
										331.5 +
										0 +
										275
									}
									{...addPropertyOverrides(
										{
											Deb_EOg_O: {
												width: `max(min(${componentViewport?.width || "100vw"} - 48px, 1200px), 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 3030) -
														160 -
														1957.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													1375,
											},
											PBicSvuJH: {
												width: `max((min(${componentViewport?.width || "100vw"} - 64px, 1200px) - 24px) / 2, 200px)`,
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 1179) -
														160 -
														1132.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													550,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1nyiuex-container"}
										layoutDependency={layoutDependency}
										layoutId={"Qf2_J_yZu-container"}
									>
										{_jsx(stdin_default2, {
											c5PhFvhFc: addImageAlt(
												{
													src: "https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png",
													srcSet:
														"https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png?scale-down-to=512 512w,https://framerusercontent.com/images/4kkJXfh7d6qHmjiQbZTSC4nqJPw.png 1024w",
												},
												"",
											),
											ECqJZ1hHM: "CEO of Thursday",
											height: "100%",
											id: "Qf2_J_yZu",
											layoutId: "Qf2_J_yZu",
											oRy6t91PU: "James Preslee",
											style: {
												width: "100%",
											},
											VePkjXSEB:
												"\u201CThe cross-device sync is seamless. I can access my lists anywhere, and they\u2019re always up to date.\u201D",
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aY2Rp.framer-pthwpv, .framer-aY2Rp .framer-pthwpv { display: block; }",
	".framer-aY2Rp.framer-19j2h69 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 80px; position: relative; width: 1200px; }",
	".framer-aY2Rp .framer-mme95t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-aY2Rp .framer-ratzws { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-aY2Rp .framer-swkefi-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-aY2Rp .framer-6rgfz9 { flex: none; height: auto; max-width: 584px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-aY2Rp .framer-11b7jjo { flex: none; height: auto; max-width: 515px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-aY2Rp .framer-14gcpcg { display: grid; flex: none; gap: 24px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(200px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-aY2Rp .framer-1b509h1 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-aY2Rp .framer-xjw21j-container, .framer-aY2Rp .framer-h6r4sx-container, .framer-aY2Rp .framer-17wjtwg-container, .framer-aY2Rp .framer-1byzxvn-container, .framer-aY2Rp .framer-1wddgsn-container, .framer-aY2Rp .framer-1nyiuex-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-aY2Rp.framer-19j2h69, .framer-aY2Rp .framer-mme95t, .framer-aY2Rp .framer-ratzws { gap: 0px; } .framer-aY2Rp.framer-19j2h69 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-aY2Rp.framer-19j2h69 > :first-child, .framer-aY2Rp .framer-mme95t > :first-child, .framer-aY2Rp .framer-ratzws > :first-child { margin-top: 0px; } .framer-aY2Rp.framer-19j2h69 > :last-child, .framer-aY2Rp .framer-mme95t > :last-child, .framer-aY2Rp .framer-ratzws > :last-child { margin-bottom: 0px; } .framer-aY2Rp .framer-mme95t > * { margin: 0px; margin-bottom: calc(64px / 2); margin-top: calc(64px / 2); } .framer-aY2Rp .framer-ratzws > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-aY2Rp.framer-v-ixxb1t.framer-19j2h69 { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-aY2Rp.framer-v-ixxb1t .framer-6rgfz9 { max-width: 561px; }",
	".framer-aY2Rp.framer-v-ixxb1t .framer-11b7jjo, .framer-aY2Rp.framer-v-e9gmpu .framer-11b7jjo { --framer-text-wrap-override: balance; max-width: unset; }",
	".framer-aY2Rp.framer-v-ixxb1t .framer-14gcpcg { grid-template-columns: repeat(2, minmax(200px, 1fr)); }",
	".framer-aY2Rp.framer-v-ixxb1t .framer-1b509h1 { top: calc(49.963208241353954% - 100% / 2); }",
	".framer-aY2Rp.framer-v-e9gmpu.framer-19j2h69 { padding: 80px 24px 80px 24px; width: 390px; }",
	".framer-aY2Rp.framer-v-e9gmpu .framer-6rgfz9 { --framer-text-wrap: balance; max-width: unset; }",
	".framer-aY2Rp.framer-v-e9gmpu .framer-14gcpcg { grid-template-columns: repeat(1, minmax(200px, 1fr)); }",
	...css,
];
var FramerBLpQs2pt2 = withCSS(Component, css2, "framer-aY2Rp");
var stdin_default3 = FramerBLpQs2pt2;
FramerBLpQs2pt2.displayName = "Section Testimonials";
FramerBLpQs2pt2.defaultProps = {
	height: 952,
	width: 1200,
};
addPropertyControls(FramerBLpQs2pt2, {
	variant: {
		options: ["jEif1shEi", "PBicSvuJH", "Deb_EOg_O"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerBLpQs2pt2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsBadgeFonts,
		...CardsTestimonialFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-testimonials
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Deb_EOg_O",
	md: "PBicSvuJH",
	xl: "jEif1shEi",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"080b0b6d577bdc210bd0cd32f7edde6108e985399928f17be1208fac1508931c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionTestimonialsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"080b0b6d577bdc210bd0cd32f7edde6108e985399928f17be1208fac1508931c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var section_testimonials_default = ComponentWithRoot;
export { section_testimonials_default as default };
