// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 080b0b6d577bdc21 "Unframer Simplicity demo", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-BEKPESE7.js";
import { stdin_default } from "./chunks/chunk-U2BTSRYM.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ZKAXZ4P5.js";
import { routes } from "./chunks/chunk-HEB6EHGG.js";

// virtual:section-how-it-works
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/R1HMVNBOLEo7nK3QW2nb/GWOQdPopNa6BzxAvuof9/prCc0aVtv.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/ilKlUCpmIocoR6yhN8w4/jU0Amj07NGVmnRvSJ0xE/v6szLN4kE.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Inter-500",
	"GF;Inter-700",
	"GF;Inter-700italic",
	"GF;Inter-500italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/inter/v19/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuI6fMZ1rib2Bg-4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/inter/v19/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZ1rib2Bg-4.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/inter/v19/UcCM3FwrK3iLTcvneQg7Ca725JhhKnNqk4j1ebLhAm8SrXTcPtxhiJ-Ek-7MeA.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/inter/v19/UcCM3FwrK3iLTcvneQg7Ca725JhhKnNqk4j1ebLhAm8SrXTc69thiJ-Ek-7MeA.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	`.framer-eyZpp .framer-styles-preset-1relapz:not(.rich-text-wrapper), .framer-eyZpp .framer-styles-preset-1relapz.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-19a7d54a-8908-466b-aff3-afd2d858cefc, rgba(255, 255, 255, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-eyZpp .framer-styles-preset-1relapz:not(.rich-text-wrapper), .framer-eyZpp .framer-styles-preset-1relapz.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-19a7d54a-8908-466b-aff3-afd2d858cefc, rgba(255, 255, 255, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-eyZpp .framer-styles-preset-1relapz:not(.rich-text-wrapper), .framer-eyZpp .framer-styles-preset-1relapz.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-19a7d54a-8908-466b-aff3-afd2d858cefc, rgba(255, 255, 255, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-eyZpp";

// /:https://framerusercontent.com/modules/R1HMVNBOLEo7nK3QW2nb/GWOQdPopNa6BzxAvuof9/prCc0aVtv.js
var ElementsBadgeFonts = getFonts(stdin_default);
var cycleOrder = ["yfUTb3bKB", "p00CGBTti", "Xcd0R0qpv"];
var serializationHash = "framer-4k7qI";
var variantClassNames = {
	p00CGBTti: "framer-v-34q867",
	Xcd0R0qpv: "framer-v-wu6x6",
	yfUTb3bKB: "framer-v-1txg3nl",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "yfUTb3bKB",
	Phone: "Xcd0R0qpv",
	Tablet: "p00CGBTti",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "yfUTb3bKB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yfUTb3bKB",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1txg3nl",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"yfUTb3bKB"}
						ref={ref ?? ref1}
						style={{
							backgroundColor:
								"var(--token-f4cf9e3e-da35-4e33-897c-29a30a250c5f, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								p00CGBTti: {
									"data-framer-name": "Tablet",
								},
								Xcd0R0qpv: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-26phku"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"qr3WdxNy4"}
						>
							<motion.div
								className={"framer-o9dj4w"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"ffzbPWZAO"}
							>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										80 +
										(((componentViewport?.height || 979) - 160 - 994.5) / 2 +
											0 +
											0) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											p00CGBTti: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 1689.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
											Xcd0R0qpv: {
												y:
													(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 200) - 160 - 2384.5) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion.div
										className={"framer-1hmgtw3-container"}
										layoutDependency={layoutDependency}
										layoutId={"yGLY3owe0-container"}
									>
										{_jsx(stdin_default, {
											D_QyhowU2: "Create React Components from Framer",
											height: "100%",
											id: "yGLY3owe0",
											layoutId: "yGLY3owe0",
											variant: "ih1f0O9Of",
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-13numsb"}
									fonts={["FS;Satoshi-medium"]}
									layoutDependency={layoutDependency}
									layoutId={"Q62gyQFF_"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											style={{
												"--font-selector": "RlM7U2F0b3NoaS1tZWRpdW0=",
												"--framer-font-family":
													'"Satoshi", "Satoshi Placeholder", sans-serif',
												"--framer-font-size": "55px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.04em",
												"--framer-line-height": "1.1em",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
											}}
										>
											{"Generate React components effortlessly."}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1s60nnl"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"aOJ88xlle"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1qe6evr"}
											data-styles-preset={"wHLHeTMJ0"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{
												"A streamlined three-step process to convert Framer designs into React components."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1e99kdl"}
								layoutDependency={layoutDependency}
								layoutId={"KzK40JeD0"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 1080,
										intrinsicWidth: 1920,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												80 +
												(((componentViewport?.height || 979) - 160 - 994.5) /
													2 +
													0 +
													0) +
												0 +
												331.5 +
												-0.7620689655171304,
										),
										pixelHeight: 2160,
										pixelWidth: 3840,
										positionX: "center",
										positionY: "center",
										sizes: `min(${componentViewport?.width || "100vw"} - 160px, 1072px)`,
										src: "https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048",
										srcSet:
											"https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg 3840w",
									}}
									className={"framer-1z0sefd"}
									data-framer-name={"BG"}
									layoutDependency={layoutDependency}
									layoutId={"gswOsh4As"}
									style={{
										mask: "radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
										opacity: 0.75,
										WebkitMask:
											"radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
									}}
									{...addPropertyOverrides(
										{
											p00CGBTti: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 1080,
													intrinsicWidth: 1920,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															80 +
															(((componentViewport?.height || 200) -
																160 -
																1689.5) /
																2 +
																0 +
																0) +
															0 +
															331.5 +
															-0.4996320824133136,
													),
													pixelHeight: 2160,
													pixelWidth: 3840,
													positionX: "center",
													positionY: "center",
													sizes: `min(${componentViewport?.width || "100vw"} - 64px, 1072px)`,
													src: "https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048",
													srcSet:
														"https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg 3840w",
												},
											},
											Xcd0R0qpv: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 1080,
													intrinsicWidth: 1920,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															80 +
															(((componentViewport?.height || 200) -
																160 -
																2384.5) /
																2 +
																0 +
																0) +
															0 +
															331.5 +
															-2.3597701149421937,
													),
													pixelHeight: 2160,
													pixelWidth: 3840,
													positionX: "center",
													positionY: "center",
													sizes: `min(${componentViewport?.width || "100vw"} - 48px, 1072px)`,
													src: "https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048",
													srcSet:
														"https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/ZVpsyKlX8sfUnM4ni3AL3ObpSik.jpg 3840w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<motion.div
									className={"framer-1s9vhw7"}
									data-border={true}
									data-framer-name={"Card"}
									layoutDependency={layoutDependency}
									layoutId={"Fc8UL5ScH"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backdropFilter: "blur(20px)",
										backgroundColor:
											"var(--token-115c046d-423c-4ec9-aef7-c8228c767968, rgb(8, 8, 8))",
										borderBottomLeftRadius: 32,
										borderBottomRightRadius: 32,
										borderTopLeftRadius: 32,
										borderTopRightRadius: 32,
										WebkitBackdropFilter: "blur(20px)",
									}}
								>
									<motion.div
										background={{
											alt: "",
											fit: "fill",
										}}
										className={"framer-164xepg"}
										layoutDependency={layoutDependency}
										layoutId={"IiqwHWAuR"}
										style={{
											mask: "radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 70.2931447072072%, rgba(0, 0, 0, 0) 100%) add",
											WebkitMask:
												"radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 70.2931447072072%, rgba(0, 0, 0, 0) 100%) add",
										}}
									>
										<SVG
											className={"framer-jz54jo"}
											data-framer-name={"Icon"}
											layout={"position"}
											layoutDependency={layoutDependency}
											layoutId={"mvuWAsATV"}
											opacity={0.08}
											style={{
												opacity: 0.08,
											}}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 110 110"><g id="ss10871673027_1"><path d="M 0 0 L 110 0 L 110 110 L 0 110 Z" fill="transparent"></path><path d="M 50.703 35.234 L 50.703 0 L 34.375 0 C 15.39 0 0 15.39 0 34.375 L 0 50.703 L 35.234 50.703 C 43.778 50.703 50.703 43.778 50.703 35.234 Z M 0 59.297 L 0 75.625 C 0 94.61 15.39 110 34.375 110 L 50.703 110 L 50.703 74.766 C 50.703 66.222 43.778 59.297 35.234 59.297 Z M 59.297 110 L 110 110 L 110 59.297 L 74.766 59.297 C 66.222 59.297 59.297 66.222 59.297 74.766 Z M 110 50.703 L 110 34.375 C 110 15.39 94.61 0 75.625 0 L 59.297 0 L 59.297 35.234 C 59.297 43.778 66.222 50.703 74.766 50.703 Z" fill="rgb(255, 255, 255)"></path></g></svg>'
											}
											svgContentId={10871673027}
											withExternalLayout={true}
										/>
									</motion.div>
									<motion.div
										className={"framer-1mjvlp2"}
										data-border={true}
										data-framer-name={"Number"}
										layoutDependency={layoutDependency}
										layoutId={"VjsWGBqRi"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-6d3c1665-ba9b-4f2f-aebb-92428292a7a5, rgb(23, 23, 23))",
											borderBottomLeftRadius: 80,
											borderBottomRightRadius: 80,
											borderTopLeftRadius: 80,
											borderTopRightRadius: 80,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1to88pp"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"cmVQ0OcQG"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											transformTemplate={transformTemplate1}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1qe6evr"}
													data-styles-preset={"wHLHeTMJ0"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"1"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-7nlvh2"}
										layoutDependency={layoutDependency}
										layoutId={"OhpyJMDGf"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-s46z6e"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"rL0MHWY4L"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1relapz"}
													data-styles-preset={"v6szLN4kE"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"Install Framer Plugin"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1454csd"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"wydklV56t"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1fgmqi7"}
													data-styles-preset={"CWRpkcDNO"}
												>
													{
														"Add the Framer plugin to your design environment to prepare for component extraction."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-1dqizkn"}
									data-border={true}
									data-framer-name={"Card"}
									layoutDependency={layoutDependency}
									layoutId={"nHhC3zG2c"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backdropFilter: "blur(20px)",
										backgroundColor:
											"var(--token-115c046d-423c-4ec9-aef7-c8228c767968, rgba(255, 255, 255, 0.04))",
										borderBottomLeftRadius: 32,
										borderBottomRightRadius: 32,
										borderTopLeftRadius: 32,
										borderTopRightRadius: 32,
										WebkitBackdropFilter: "blur(20px)",
									}}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 979) - 160 - 994.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													0 +
													40 +
													0,
											),
											pixelHeight: 668,
											pixelWidth: 728,
											sizes: `calc(max((min(${componentViewport?.width || "100vw"} - 160px, 1072px) - 64px) / 3, 50px) - 48px)`,
											src: "https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png",
											srcSet:
												"https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png?scale-down-to=512 512w,https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png 728w",
										}}
										className={"framer-1ec08u3"}
										layoutDependency={layoutDependency}
										layoutId={"ohDUqBJRp"}
										style={{
											mask: "radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
											WebkitMask:
												"radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
										}}
										{...addPropertyOverrides(
											{
												p00CGBTti: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 200) -
																	160 -
																	1689.5) /
																	2 +
																	0 +
																	0) +
																0 +
																331.5 +
																0 +
																0 +
																40 +
																0,
														),
														pixelHeight: 668,
														pixelWidth: 728,
														sizes: `calc(max((min(${componentViewport?.width || "100vw"} - 64px, 1072px) - 32px) / 2, 50px) - 48px)`,
														src: "https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png",
														srcSet:
															"https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png?scale-down-to=512 512w,https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png 728w",
													},
												},
												Xcd0R0qpv: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 200) -
																	160 -
																	2384.5) /
																	2 +
																	0 +
																	0) +
																0 +
																331.5 +
																0 +
																695 +
																40 +
																0,
														),
														pixelHeight: 668,
														pixelWidth: 728,
														sizes: `calc(max(min(${componentViewport?.width || "100vw"} - 48px, 1072px), 50px) - 48px)`,
														src: "https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png",
														srcSet:
															"https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png?scale-down-to=512 512w,https://framerusercontent.com/images/tWcAuMcGwKolzkjnyutsFhQMOlc.png 728w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<motion.div
										className={"framer-np2fxt"}
										data-border={true}
										data-framer-name={"Number"}
										layoutDependency={layoutDependency}
										layoutId={"CVyPMzviz"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-6d3c1665-ba9b-4f2f-aebb-92428292a7a5, rgb(23, 23, 23))",
											borderBottomLeftRadius: 80,
											borderBottomRightRadius: 80,
											borderTopLeftRadius: 80,
											borderTopRightRadius: 80,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1vd6lsb"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"giOr1Jz0K"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											transformTemplate={transformTemplate1}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1qe6evr"}
													data-styles-preset={"wHLHeTMJ0"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"2"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-jzwczf"}
										layoutDependency={layoutDependency}
										layoutId={"Rjhd2uoCy"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-mm30kz"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ySdnofJlw"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1relapz"}
													data-styles-preset={"v6szLN4kE"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"Run the Unframer CLI"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1518ltk"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"muRgK9H01"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1fgmqi7"}
													data-styles-preset={"CWRpkcDNO"}
												>
													{
														"Execute the Unframer command-line interface to transform your Framer design into component code."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-1mnf7bs"}
									data-border={true}
									data-framer-name={"Card"}
									layoutDependency={layoutDependency}
									layoutId={"x72llBwwo"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backdropFilter: "blur(20px)",
										backgroundColor:
											"var(--token-115c046d-423c-4ec9-aef7-c8228c767968, rgba(255, 255, 255, 0.04))",
										borderBottomLeftRadius: 32,
										borderBottomRightRadius: 32,
										borderTopLeftRadius: 32,
										borderTopRightRadius: 32,
										WebkitBackdropFilter: "blur(20px)",
									}}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													80 +
													(((componentViewport?.height || 979) - 160 - 994.5) /
														2 +
														0 +
														0) +
													0 +
													331.5 +
													0 +
													0 +
													40 +
													0,
											),
											pixelHeight: 668,
											pixelWidth: 728,
											sizes: `calc(max((min(${componentViewport?.width || "100vw"} - 160px, 1072px) - 64px) / 3, 50px) - 48px)`,
											src: "https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png",
											srcSet:
												"https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png?scale-down-to=512 512w,https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png 728w",
										}}
										className={"framer-1q5250a"}
										layoutDependency={layoutDependency}
										layoutId={"qfvVlPyVV"}
										style={{
											mask: "radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
											WebkitMask:
												"radial-gradient(50% 50% at 50% 50%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 100%) add",
										}}
										{...addPropertyOverrides(
											{
												p00CGBTti: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 200) -
																	160 -
																	1689.5) /
																	2 +
																	0 +
																	0) +
																0 +
																331.5 +
																0 +
																695 +
																40 +
																0,
														),
														pixelHeight: 668,
														pixelWidth: 728,
														sizes: `calc(max((min(${componentViewport?.width || "100vw"} - 64px, 1072px) - 32px) / 2, 50px) - 48px)`,
														src: "https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png",
														srcSet:
															"https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png?scale-down-to=512 512w,https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png 728w",
													},
												},
												Xcd0R0qpv: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																80 +
																(((componentViewport?.height || 200) -
																	160 -
																	2384.5) /
																	2 +
																	0 +
																	0) +
																0 +
																331.5 +
																0 +
																1390 +
																40 +
																0,
														),
														pixelHeight: 668,
														pixelWidth: 728,
														sizes: `calc(max(min(${componentViewport?.width || "100vw"} - 48px, 1072px), 50px) - 48px)`,
														src: "https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png",
														srcSet:
															"https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png?scale-down-to=512 512w,https://framerusercontent.com/images/sUdPzmKAlZDa1aUhd2GicVWtxks.png 728w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<motion.div
										className={"framer-6ymp3i"}
										data-border={true}
										data-framer-name={"Number"}
										layoutDependency={layoutDependency}
										layoutId={"yCwsOzC3u"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-84dd2d93-207f-43bc-ad9f-d0f489fa6f14, rgba(255, 255, 255, 0.08))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor:
												"var(--token-6d3c1665-ba9b-4f2f-aebb-92428292a7a5, rgb(23, 23, 23))",
											borderBottomLeftRadius: 80,
											borderBottomRightRadius: 80,
											borderTopLeftRadius: 80,
											borderTopRightRadius: 80,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-j7z4er"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"DhP_htW0f"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											transformTemplate={transformTemplate1}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1qe6evr"}
													data-styles-preset={"wHLHeTMJ0"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"3"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1q4bd7x"}
										layoutDependency={layoutDependency}
										layoutId={"sCfSzn3KG"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-fsevcb"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"xhBZeaayA"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1relapz"}
													data-styles-preset={"v6szLN4kE"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-a47e5f39-ab8e-4e9f-95d6-dca87be48225, rgb(255, 255, 255)))",
													}}
												>
													{"Import and Render Components"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-125uoaq"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"P7f4qYdSs"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1fgmqi7"}
													data-styles-preset={"CWRpkcDNO"}
												>
													{
														"Seamlessly integrate the generated React components into your project and render them with ease."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4k7qI.framer-xxnwvw, .framer-4k7qI .framer-xxnwvw { display: block; }",
	".framer-4k7qI.framer-1txg3nl { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 80px; position: relative; width: 1200px; }",
	".framer-4k7qI .framer-26phku { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1072px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4k7qI .framer-o9dj4w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4k7qI .framer-1hmgtw3-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-4k7qI .framer-13numsb { flex: none; height: auto; max-width: 584px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-4k7qI .framer-1s60nnl, .framer-4k7qI .framer-1454csd, .framer-4k7qI .framer-1518ltk, .framer-4k7qI .framer-125uoaq { flex: none; height: auto; max-width: 515px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-4k7qI .framer-1e99kdl { display: grid; flex: none; gap: 32px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4k7qI .framer-1z0sefd { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(49.88505747126439% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-4k7qI .framer-1s9vhw7, .framer-4k7qI .framer-1dqizkn, .framer-4k7qI .framer-1mnf7bs { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: auto; justify-content: center; justify-self: start; overflow: visible; padding: 40px 24px 40px 24px; position: relative; width: 100%; }",
	".framer-4k7qI .framer-164xepg, .framer-4k7qI .framer-1q5250a { aspect-ratio: 1.0925196850393701 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 253px); position: relative; width: 100%; }",
	".framer-4k7qI .framer-jz54jo { flex: none; height: 110px; left: calc(49.729729729729755% - 110px / 2); position: absolute; top: calc(50.00000000000002% - 110px / 2); width: 110px; }",
	".framer-4k7qI .framer-1mjvlp2 { flex: none; height: 32px; left: 139px; overflow: hidden; position: absolute; top: -16px; width: 48px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-4k7qI .framer-1to88pp, .framer-4k7qI .framer-1vd6lsb, .framer-4k7qI .framer-j7z4er { flex: none; height: auto; left: 50%; position: absolute; top: 50%; white-space: pre; width: auto; }",
	".framer-4k7qI .framer-7nlvh2, .framer-4k7qI .framer-jzwczf, .framer-4k7qI .framer-1q4bd7x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-4k7qI .framer-s46z6e, .framer-4k7qI .framer-mm30kz, .framer-4k7qI .framer-fsevcb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-4k7qI .framer-1ec08u3 { aspect-ratio: 1.0905511811023623 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 254px); position: relative; width: 100%; }",
	".framer-4k7qI .framer-np2fxt, .framer-4k7qI .framer-6ymp3i { flex: none; height: 32px; left: calc(50.00000000000002% - 48px / 2); overflow: hidden; position: absolute; top: -16px; width: 48px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4k7qI.framer-1txg3nl, .framer-4k7qI .framer-26phku, .framer-4k7qI .framer-o9dj4w, .framer-4k7qI .framer-1s9vhw7, .framer-4k7qI .framer-7nlvh2, .framer-4k7qI .framer-1dqizkn, .framer-4k7qI .framer-jzwczf, .framer-4k7qI .framer-1mnf7bs, .framer-4k7qI .framer-1q4bd7x { gap: 0px; } .framer-4k7qI.framer-1txg3nl > *, .framer-4k7qI .framer-26phku > * { margin: 0px; margin-bottom: calc(64px / 2); margin-top: calc(64px / 2); } .framer-4k7qI.framer-1txg3nl > :first-child, .framer-4k7qI .framer-26phku > :first-child, .framer-4k7qI .framer-o9dj4w > :first-child, .framer-4k7qI .framer-1s9vhw7 > :first-child, .framer-4k7qI .framer-7nlvh2 > :first-child, .framer-4k7qI .framer-1dqizkn > :first-child, .framer-4k7qI .framer-jzwczf > :first-child, .framer-4k7qI .framer-1mnf7bs > :first-child, .framer-4k7qI .framer-1q4bd7x > :first-child { margin-top: 0px; } .framer-4k7qI.framer-1txg3nl > :last-child, .framer-4k7qI .framer-26phku > :last-child, .framer-4k7qI .framer-o9dj4w > :last-child, .framer-4k7qI .framer-1s9vhw7 > :last-child, .framer-4k7qI .framer-7nlvh2 > :last-child, .framer-4k7qI .framer-1dqizkn > :last-child, .framer-4k7qI .framer-jzwczf > :last-child, .framer-4k7qI .framer-1mnf7bs > :last-child, .framer-4k7qI .framer-1q4bd7x > :last-child { margin-bottom: 0px; } .framer-4k7qI .framer-o9dj4w > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-4k7qI .framer-1s9vhw7 > *, .framer-4k7qI .framer-1dqizkn > *, .framer-4k7qI .framer-1mnf7bs > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-4k7qI .framer-7nlvh2 > *, .framer-4k7qI .framer-jzwczf > *, .framer-4k7qI .framer-1q4bd7x > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
	".framer-4k7qI.framer-v-34q867.framer-1txg3nl { padding: 80px 32px 80px 32px; width: 810px; }",
	".framer-4k7qI.framer-v-34q867 .framer-13numsb { max-width: 561px; }",
	".framer-4k7qI.framer-v-34q867 .framer-1s60nnl, .framer-4k7qI.framer-v-34q867 .framer-1454csd, .framer-4k7qI.framer-v-34q867 .framer-1518ltk, .framer-4k7qI.framer-v-34q867 .framer-125uoaq, .framer-4k7qI.framer-v-wu6x6 .framer-1s60nnl, .framer-4k7qI.framer-v-wu6x6 .framer-1454csd, .framer-4k7qI.framer-v-wu6x6 .framer-1518ltk, .framer-4k7qI.framer-v-wu6x6 .framer-125uoaq { --framer-text-wrap-override: balance; max-width: unset; }",
	".framer-4k7qI.framer-v-34q867 .framer-1e99kdl { grid-template-columns: repeat(2, minmax(50px, 1fr)); }",
	".framer-4k7qI.framer-v-34q867 .framer-1z0sefd { top: calc(49.963208241353954% - 100% / 2); }",
	".framer-4k7qI.framer-v-34q867 .framer-164xepg, .framer-4k7qI.framer-v-34q867 .framer-1ec08u3, .framer-4k7qI.framer-v-34q867 .framer-1q5250a, .framer-4k7qI.framer-v-wu6x6 .framer-164xepg, .framer-4k7qI.framer-v-wu6x6 .framer-1ec08u3, .framer-4k7qI.framer-v-wu6x6 .framer-1q5250a { height: var(--framer-aspect-ratio-supported, 183px); }",
	".framer-4k7qI.framer-v-wu6x6.framer-1txg3nl { padding: 80px 24px 80px 24px; width: 390px; }",
	".framer-4k7qI.framer-v-wu6x6 .framer-13numsb { --framer-text-wrap: balance; max-width: unset; }",
	".framer-4k7qI.framer-v-wu6x6 .framer-1e99kdl { grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-4k7qI.framer-v-wu6x6 .framer-s46z6e, .framer-4k7qI.framer-v-wu6x6 .framer-mm30kz, .framer-4k7qI.framer-v-wu6x6 .framer-fsevcb { --framer-text-wrap-override: balance; }",
	...css,
	...css3,
	...css2,
	'.framer-4k7qI[data-border="true"]::after, .framer-4k7qI [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerprCc0aVtv = withCSS(Component, css4, "framer-4k7qI");
var stdin_default2 = FramerprCc0aVtv;
FramerprCc0aVtv.displayName = "Section How It Works";
FramerprCc0aVtv.defaultProps = {
	height: 979,
	width: 1200,
};
addPropertyControls(FramerprCc0aVtv, {
	variant: {
		options: ["yfUTb3bKB", "p00CGBTti", "Xcd0R0qpv"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerprCc0aVtv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsBadgeFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-how-it-works
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "s1KQAuUYo",
	md: "sRbSQTUZm",
	xl: "tZ3Nk88mM",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"080b0b6d577bdc210bd0cd32f7edde6108e985399928f17be1208fac1508931c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionHowItWorksFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"080b0b6d577bdc210bd0cd32f7edde6108e985399928f17be1208fac1508931c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var section_how_it_works_default = ComponentWithRoot;
export { section_how_it_works_default as default };
