/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Wide' | 'Narrow'
    "thumbnail"?: {src: string, srcSet?: string, alt?: string}
    "lessons"?: string
    "minutes"?: string
    "title"?: string
    "descriptionVisible"?: boolean
    "description"?: string
    "click2"?: Function
}

const TrainingsDetailHeroFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

TrainingsDetailHeroFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants: VariantsMap}) => any

export default TrainingsDetailHeroFramerComponent

