// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 518a2b8ad72f6929 "Workbase App Test Unframer", do not edit manually */
'use client';
import { Icon, } from './chunks/chunk-IJCPCLBS.js';

// virtual:trainings-chevron
import { Fragment as Fragment2, } from 'react';
import { ContextProviders, } from 'unframer';

// /:https://framerusercontent.com/modules/utxCESHbFbfxqogTGa7c/e5SUWvSCTlioGEPK9OI4/O0Za3NJK6.js
import { jsx as _jsx, } from 'react/jsx-runtime';
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from 'unframer';
import { LayoutGroup, motion, MotionConfigContext, } from 'unframer';
import * as React from 'react';
var IconFonts = getFonts(Icon,);
var enabledGestures = { aj8eFfhbI: { hover: true, }, H1iKxdzpa: { hover: true, }, };
var cycleOrder = ['H1iKxdzpa', 'aj8eFfhbI', 'BJtHgzdtf',];
var serializationHash = 'framer-900ua';
var variantClassNames = { aj8eFfhbI: 'framer-v-1typrub', BJtHgzdtf: 'framer-v-1pv8syk', H1iKxdzpa: 'framer-v-12yfkgo', };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach((variant,) => variant && Object.assign(nextOverrides, overrides[variant],));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: 'spring', };
var Transition = ({ value, children, },) => {
  const config = React.useContext(MotionConfigContext,);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition, }), [JSON.stringify(transition,),],);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children, },);
};
var Variants = motion.create(React.Fragment,);
var humanReadableVariantMap = { 'Down - Open': 'BJtHgzdtf', Down: 'H1iKxdzpa', Up: 'aj8eFfhbI', };
var getProps = ({ height, id, width, ...props },) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return {
    ...props,
    variant:
      (_ref =
            (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null &&
              _humanReadableVariantMap_props_variant !== void 0
              ? _humanReadableVariantMap_props_variant
              : props.variant) !== null && _ref !== void 0
        ? _ref
        : 'H1iKxdzpa',
  };
};
var createLayoutDependency = (props, variants,) => {
  if (props.layoutDependency) return variants.join('-',) + props.layoutDependency;
  return variants.join('-',);
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref,) {
  const { activeLocale, setLocale, } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props,);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({ cycleOrder, defaultVariant: 'H1iKxdzpa', enabledGestures, variant, variantClassNames, },);
  const layoutDependency = createLayoutDependency(props, variants,);
  const ref1 = React.useRef(null,);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /* @__PURE__ */ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /* @__PURE__ */ _jsx(Transition, {
        value: transition1,
        children: /* @__PURE__ */ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(serializationHash, ...sharedStyleClassNames, 'framer-12yfkgo', className, classNames,),
          'data-framer-name': 'Down',
          layoutDependency,
          layoutId: 'H1iKxdzpa',
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style, },
          ...addPropertyOverrides(
            {
              'aj8eFfhbI-hover': { 'data-framer-name': void 0, },
              'H1iKxdzpa-hover': { 'data-framer-name': void 0, },
              aj8eFfhbI: { 'data-framer-name': 'Up', },
              BJtHgzdtf: { 'data-framer-name': 'Down - Open', },
            },
            baseVariant,
            gestureVariant,
          ),
          children: /* @__PURE__ */ _jsx(ComponentViewportProvider, {
            children: /* @__PURE__ */ _jsx(motion.div, {
              className: 'framer-1q11yzs-container',
              layoutDependency,
              layoutId: 'HkbN9KS6v-container',
              style: { rotate: 0, },
              variants: { aj8eFfhbI: { rotate: 180, }, },
              children: /* @__PURE__ */ _jsx(Icon, {
                color: 'var(--token-0f51fcfd-e97a-4e3b-8e90-4dde88da0e0b, rgb(82, 82, 91))',
                customPath: '',
                height: '100%',
                id: 'HkbN9KS6v',
                layoutId: 'HkbN9KS6v',
                style: { height: '100%', width: '100%', },
                variant: 'Chevron Down',
                variantText: '',
                width: '100%',
                ...addPropertyOverrides(
                  {
                    'aj8eFfhbI-hover': { color: 'var(--token-abc765bb-4f1b-45aa-9bdc-0add1aff8e20, rgb(24, 24, 27))', },
                    'H1iKxdzpa-hover': { color: 'var(--token-abc765bb-4f1b-45aa-9bdc-0add1aff8e20, rgb(24, 24, 27))', },
                    BJtHgzdtf: { color: 'var(--token-abc765bb-4f1b-45aa-9bdc-0add1aff8e20, rgb(24, 24, 27))', },
                  },
                  baseVariant,
                  gestureVariant,
                ),
              },),
            },),
          },),
        },),
      },),
    },),
  },);
},);
var css = [
  '@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }',
  '.framer-900ua.framer-1s8omdc, .framer-900ua .framer-1s8omdc { display: block; }',
  '.framer-900ua.framer-12yfkgo { cursor: pointer; height: 47px; overflow: visible; position: relative; width: 32px; }',
  '.framer-900ua .framer-1q11yzs-container { flex: none; height: 32px; left: calc(50.00000000000002% - 32px / 2); position: absolute; top: calc(55.31914893617024% - 32px / 2); width: 32px; }',
  '.framer-900ua.framer-v-1pv8syk.framer-12yfkgo { cursor: unset; }',
  '.framer-900ua.framer-v-1pv8syk .framer-1q11yzs-container { top: calc(65.95744680851065% - 32px / 2); }',
];
var FramerO0Za3NJK6 = withCSS(Component, css, 'framer-900ua',);
var stdin_default = FramerO0Za3NJK6;
FramerO0Za3NJK6.displayName = 'Trainings: Chevron';
FramerO0Za3NJK6.defaultProps = { height: 47, width: 32, };
addPropertyControls(FramerO0Za3NJK6, {
  variant: {
    options: ['H1iKxdzpa', 'aj8eFfhbI', 'BJtHgzdtf',],
    optionTitles: ['Down', 'Up', 'Down - Open',],
    title: 'Variant',
    type: ControlType.Enum,
  },
},);
addFonts(FramerO0Za3NJK6, [{ explicitInter: true, fonts: [], }, ...IconFonts,], { supportsExplicitInterCodegen: true, },);

// virtual:trainings-chevron
import { WithFramerBreakpoints, } from 'unframer';
import { jsx, } from 'react/jsx-runtime';
var locales = [];
stdin_default.Responsive = ({ locale, ...rest },) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        'AqIAlNhpQ': { 'path': '/trainings', },
        'UgbHu5iGd': { 'path': '/trainings/lesson', },
        'ZlRuzQRq_': { 'path': '/trainings/module', },
        'augiA20Il': { 'path': '/', },
        'uVmLxeTxC': { 'path': '/trainings/detail', },
      },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          ...rest,
        },
      ),
      framerSiteId: '518a2b8ad72f69290843c62cd885a1e84f986f02594e125e33c81a75b1b1bd3e',
      locale,
      locales,
    },
  );
};
function ComponentWithRoot({ locale, ...rest },) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        'AqIAlNhpQ': {
          'path': '/trainings',
        },
        'UgbHu5iGd': {
          'path': '/trainings/lesson',
        },
        'ZlRuzQRq_': {
          'path': '/trainings/module',
        },
        'augiA20Il': {
          'path': '/',
        },
        'uVmLxeTxC': {
          'path': '/trainings/detail',
        },
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest, },),
      framerSiteId: '518a2b8ad72f69290843c62cd885a1e84f986f02594e125e33c81a75b1b1bd3e',
      locale,
      locales,
    },
  );
}
Object.assign(ComponentWithRoot, stdin_default,);
export { ComponentWithRoot as default, };
