// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f667fc580d8d9346 "ApiFlow (copy)", do not edit manually */
"use client";

import { stdin_default } from "../chunks/chunk-ZCPWFOW3.js";
import "../chunks/chunk-WSFCRVEQ.js";

// virtual:navigation/icon
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ufJIpzVk3",
	sm: "h7DS_KM0Q",
};
stdin_default.Responsive = ({ locale, ...rest }) => {
	return /* @__PURE__ */ jsx(ContextProviders, {
		routes: {
			I0Vjsk230: {
				path: "/pricing",
			},
			If1LKvdh8: {
				path: "/blog/:slug",
			},
			MYlLV6Tip: {
				path: "/docs",
			},
			NSnQ_g8yw: {
				path: "/:slug",
			},
			augiA20Il: {
				path: "/",
			},
			cvVskSlKE: {
				path: "/sign-up",
			},
			dqRVpj9Kn: {
				path: "/docs/:slug",
			},
			iUM2Wrnwp: {
				path: "/contact-sales-2",
			},
			j_IHQLq_9: {
				path: "/sign-in",
			},
			lreH5keWI: {
				path: "/support",
			},
			qNb6QfkBq: {
				path: "/contact-sales",
			},
			so7P3QBWY: {
				path: "/404",
			},
			tBghjsyop: {
				path: "/blog",
			},
		},
		children: /* @__PURE__ */ jsx(WithFramerBreakpoints, {
			Component: stdin_default,
			variants: defaultResponsiveVariants,
			...rest,
		}),
		framerSiteId:
			"f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405",
		locale,
		locales,
	});
};
function ComponentWithRoot({ locale, ...rest }) {
	return /* @__PURE__ */ jsx(ContextProviders, {
		routes: {
			I0Vjsk230: {
				path: "/pricing",
			},
			If1LKvdh8: {
				path: "/blog/:slug",
			},
			MYlLV6Tip: {
				path: "/docs",
			},
			NSnQ_g8yw: {
				path: "/:slug",
			},
			augiA20Il: {
				path: "/",
			},
			cvVskSlKE: {
				path: "/sign-up",
			},
			dqRVpj9Kn: {
				path: "/docs/:slug",
			},
			iUM2Wrnwp: {
				path: "/contact-sales-2",
			},
			j_IHQLq_9: {
				path: "/sign-in",
			},
			lreH5keWI: {
				path: "/support",
			},
			qNb6QfkBq: {
				path: "/contact-sales",
			},
			so7P3QBWY: {
				path: "/404",
			},
			tBghjsyop: {
				path: "/blog",
			},
		},
		children: /* @__PURE__ */ jsx(stdin_default, {
			...rest,
		}),
		framerSiteId:
			"f667fc580d8d9346cf49d633d75940b95292fa43c24dd7765c9a175ec73f7405",
		locale,
		locales,
	});
}
Object.assign(ComponentWithRoot, stdin_default);
export { ComponentWithRoot as default };
