/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Closed' | 'Open' | 'Preview - Mobile'
    "linkText"?: string
    "link"?: string
    "name"?: string
    "username"?: string
    "verified"?: boolean
    "profilePicture"?: {src: string, srcSet?: string, alt?: string}
    "bioPlain"?: string
}

const TwitterProfilePreviewFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

TwitterProfilePreviewFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default TwitterProfilePreviewFramerComponent

